using System.Text.Json;

namespace Relic.Core.Server;

/// <summary>
/// The display catalogue behind the Gameplay page (config/tweakdata.json, generated by
/// build/make_catalog.py): the English names and sprite names of the monsters, items, domains and
/// quests that the agent's gameplay settings name by id. Nothing here interprets it — the page joins it
/// by id with what the agent answers and draws "#id" for an id the file lacks — so the document is kept
/// as parsed JSON and no section is bound to a class.
/// <para>Only the copy shipped next to the exe is read. Unlike <see cref="GameData"/> there is no
/// per-user folder that outranks it: the file is generated together with the sprites of the same build,
/// and a copy left in such a folder would hide the entries and icons the running build ships.</para>
/// </summary>
public sealed class TweakData
{
    public const string StatusOk = "ok";
    public const string StatusMissing = "missing";
    public const string StatusError = "error";

    /// <summary><see cref="StatusOk"/>, <see cref="StatusMissing"/> (no such file) or
    /// <see cref="StatusError"/> (it cannot be read, is not JSON, or its root is not an object).</summary>
    public string Status { get; }

    /// <summary>The whole document as the file holds it — set only when <see cref="Status"/> is
    /// <see cref="StatusOk"/>.</summary>
    public JsonElement? Data { get; }

    /// <summary>Why the file cannot be used — set only when <see cref="Status"/> is
    /// <see cref="StatusError"/>.</summary>
    public string? Error { get; }

    private TweakData(string status, JsonElement? data = null, string? error = null)
    {
        Status = status;
        Data = data;
        Error = error;
    }

    /// <summary>Where the build ships the file: <c>config/tweakdata.json</c> next to the exe.</summary>
    public static string ShippedPath => Path.Combine(AppContext.BaseDirectory, "config", "tweakdata.json");

    /// <summary>Read the catalogue. Never throws: a file that is not there, or that cannot be used, is a
    /// status — the page then shows ids instead of names. <paramref name="path"/> is for the spike, which
    /// runs from its own output folder where no config/ exists.</summary>
    public static TweakData Load(string? path = null)
    {
        string text;
        try { text = File.ReadAllText(path ?? ShippedPath); }
        catch (Exception ex) when (ex is FileNotFoundException or DirectoryNotFoundException)
        {
            return new TweakData(StatusMissing);
        }
        catch (Exception ex) { return new TweakData(StatusError, error: ex.Message); }
        try
        {
            using var doc = JsonDocument.Parse(text);
            // The sections are addressed by name, so a root that is not an object is as unusable as a file
            // that does not parse: asking for its properties refuses it in the parser's own words.
            _ = doc.RootElement.EnumerateObject();
            return new TweakData(StatusOk, doc.RootElement.Clone());
        }
        catch (Exception ex) { return new TweakData(StatusError, error: ex.Message); }
    }

    /// <summary>What the <c>tweakdata.get</c> rpc answers: <c>{status: "ok", data}</c>,
    /// <c>{status: "missing"}</c> or <c>{status: "error", error}</c> — only the keys that apply, so the page
    /// never meets a null where it expects a catalogue.</summary>
    public object ToReply() => Status switch
    {
        StatusOk => new { status = Status, data = Data },
        StatusError => new { status = Status, error = Error },
        _ => new { status = Status },
    };
}
