#!/usr/bin/env python3
"""Turns the field offsets recorded in the generated 1.6 headers into compile-time assertions.

Every field the generator wrote carries the offset the dump says it lives at. Nothing else checks that the C++
struct actually puts it there, so a layout that is off by a few bytes reads a neighbouring field instead - it
compiles, it runs, and it hands the game a number where a pointer belongs. That is how map teleport can kill the
1.6 client: an empty base-class struct still takes a byte in C++, so every field after it sits 8 bytes too far
and `_scenePointDics` is read out of the middle of a Vector3.

Writes `<appdata>/il2cpp-types-asserts.h`; a mismatch is then a build error naming the struct and the field.

    python gen_field_asserts.py 16
"""
import os, re, sys

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.normpath(os.path.join(HERE, "..", "mod", "cheat-library", "src"))

# An IL2CPP object is klass + monitor before its first field, so the dump's absolute offsets are 0x10 ahead
# of the offsets inside the generated __Fields struct.
HEADER_BYTES = 0x10

STRUCT = re.compile(r"struct(?:\s+__declspec\(align\(\d+\)\))?\s+([A-Za-z_][A-Za-z0-9_]*__Fields)\s*\{")
MEMBER = re.compile(
    r"^\s*(?:struct\s+|union\s+|enum\s+)?[A-Za-z_][A-Za-z0-9_:<>, ]*?[\s\*]+"
    r"([A-Za-z_][A-Za-z0-9_]*)\s*(?:\[[^\]]*\])?\s*;\s*//\s*(0x[0-9A-Fa-f]+)")


def structs_of(path):
    with open(path, "r", encoding="utf-8", errors="replace") as f:
        lines = f.read().split("\n")

    out, name, depth = [], None, 0
    fields = []
    for line in lines:
        if name is None:
            m = STRUCT.search(line)
            if m:
                name, depth, fields = m.group(1), line.count("{") - line.count("}"), []
            continue

        depth += line.count("{") - line.count("}")
        if depth <= 0:
            if fields:
                out.append((name, fields))
            name = None
            continue

        m = MEMBER.match(line)
        if m and depth == 1:   # only the struct's own members, never a nested anonymous one
            fields.append((m.group(1), int(m.group(2), 16)))
    return out


# member names the CRT defines as macros (<sys/stat.h>: `#define _stat _stat64i32`), which offsetof cannot name
MACRO_NAMES = {"_stat", "_fstat", "_wstat", "stat", "fstat"}


def known_bad(directory):
    """Fields whose C++ layout is known not to match the dump yet - listed so the build still runs."""
    path = os.path.join(directory, "field-offsets.known-bad.txt")
    if not os.path.exists(path):
        return set()
    with open(path, "r", encoding="utf-8") as f:
        return {line.strip() for line in f if line.strip() and not line.startswith("#")}


def main(version):
    directory = os.path.join(SRC, "appdata-%s" % version)
    entries = []
    for name in sorted(os.listdir(directory)):
        if name.startswith("il2cpp-types") and name.endswith(".h") and "asserts" not in name:
            entries += structs_of(os.path.join(directory, name))

    skip = known_bad(directory)
    out = os.path.join(directory, "il2cpp-types-asserts.h")
    count = skipped = 0
    with open(out, "w", encoding="utf-8", newline="\r\n") as f:
        f.write("// Generated by tools/gen_field_asserts.py - do not edit.\n//\n"
                "// Each assertion pins a generated struct member to the offset the game's own metadata dump\n"
                "// reports for it. A struct whose C++ layout drifts from the game's stops the build here\n"
                "// instead of handing a feature a pointer read out of the middle of another field.\n"
                "//\n"
                "// Fields listed in field-offsets.known-bad.txt are skipped: their layout is already wrong and\n"
                "// the features that read them are unreliable on this game version, but the build must still\n"
                "// run. The point of the list is that it can only shrink - anything NEW breaks the build.\n\n"
                "#pragma once\n\n#include <cstddef>\n\nnamespace app\n{\n")
        for struct, fields in entries:
            for field, absolute in fields:
                if absolute < HEADER_BYTES:
                    continue
                if "%s::%s" % (struct, field) in skip or field in MACRO_NAMES:
                    skipped += 1
                    continue
                f.write('    static_assert(offsetof(%s, %s) == 0x%X, "%s::%s moved - the game puts it at 0x%X");\n'
                        % (struct, field, absolute - HEADER_BYTES, struct, field, absolute))
                count += 1
        f.write("}\n")

    print("%s: %d structs, %d assertions (%d known-bad skipped) -> %s"
          % (version, len(entries), count, skipped, os.path.relpath(out, SRC)))


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else "16")
