#!/usr/bin/env python3
"""make_hd_icons.py - the HD icon set the interactive map embeds next to its 30x30 icons.

"Show HD icons" makes the map ask for "HD" + <clear name>; ImageLoader falls back to the normal icon when
that resource is missing. This tool writes the HD set the build actually needs and regenerates the matching
block of res.rc (between the two marker comments) and the iconsHD <Image> items of cheat-library.vcxproj(.filters),
so all three stay in step.

What is included: every icon a shipped map dataset uses (map_teyvat / map_enkanomiya / map_undeground_mines /
map_gaa16_scene4 / map_gaa28_scene9) plus the character and weapon art of the Ascension Materials window
(ascension_materials.json) - that window has no normal icons at all.

Where the art comes from, first match wins:
  1. tools/hd_icon_overrides/<File>.png   tracked corrections and art upstream never had (see SOURCES.md)
  2. heavy_ref/res/iconsHD/<File>.png     the upstream Akebi HD originals (gitignored, ~256 px)
A label's <File> is the file its NORMAL icon resource points at in res.rc (several resource names share one
file, e.g. OCEANIDBOAR -> OceanidSummons.png), else the clear name itself (materials art, labels whose
normal icon is still missing).

Resource names: the clear name with Unicode Roman numerals folded to ASCII ("SealLocationⅠ" ->
"SEALLOCATIONI"), exactly what InteractiveMap's LabelIcon() asks for; rc.exe only takes ASCII identifiers.

Output: mod/cheat-library/res/iconsHD/<File>.png, fitted into SIZE x SIZE (128: the icon-size slider tops out at
96 px), premultiplied-alpha LANCZOS so edges do not darken, deterministic bytes. Stale outputs are removed.

    python make_hd_icons.py            # write iconsHD/ + res.rc block, print what is missing
    python make_hd_icons.py --check    # change nothing, exit 1 if the outputs or res.rc are out of date
"""
import argparse, io, json, os, re, sys
from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
RES = os.path.normpath(os.path.join(HERE, '..', 'mod', 'cheat-library', 'res'))
UPSTREAM = os.path.normpath(os.path.join(HERE, '..', 'heavy_ref', 'res', 'iconsHD'))
OVERRIDES = os.path.join(HERE, 'hd_icon_overrides')
OUT = os.path.join(RES, 'iconsHD')
RC = os.path.join(RES, 'res.rc')
SIZE = 128
DATASETS = ['map_teyvat.json', 'map_enkanomiya.json', 'map_undeground_mines.json',
            'map_gaa16_scene4.json', 'map_gaa28_scene9.json']
BEGIN = '// Relic: iconsHD begin - generated by tools/make_hd_icons.py, do not edit by hand'
END = '// Relic: iconsHD end'
PROJECTS = [os.path.normpath(os.path.join(RES, '..', p))
            for p in ('cheat-library.vcxproj', 'cheat-library.vcxproj.filters')]
ROMAN ={'Ⅰ': 'I', 'Ⅱ': 'II', 'Ⅲ': 'III', 'Ⅳ': 'IV', 'Ⅴ': 'V'}


def resource_name(clear_name):
    """The ASCII name LabelIcon() looks up, or None when rc.exe could not carry it."""
    for k, v in ROMAN.items():
        clear_name = clear_name.replace(k, v)
    return clear_name if re.fullmatch(r'[A-Za-z0-9_]+', clear_name) else None


def file_index(directory):
    if not os.path.isdir(directory):
        return {}
    return {os.path.splitext(f)[0].lower(): os.path.join(directory, f)
            for f in os.listdir(directory) if f.lower().endswith('.png')}


def sync_project(text, names):
    """The project's iconsHD <Image> items become exactly `names` (IDE listing only - rc.exe reads res.rc)."""
    nl = '\r\n' if '\r\n' in text else '\n'
    item = re.compile(r'([ \t]*)<Image Include="(?:res\\)?iconsHD\\[^"]+"\s*(?:/>|>(.*?)</Image>)[ \t]*\r?\n', re.S)
    first = item.search(text)
    if first is None:
        return text
    indent = first.group(1)
    rest = item.sub('', text[first.start():])
    filt = re.search(r'<Filter>([^<]+)</Filter>', first.group(2) or '')
    lines = []
    for name in sorted(names, key=str.lower):
        path = 'res\\iconsHD\\' + name
        if filt:
            lines.append('%s<Image Include="%s">%s%s  <Filter>%s</Filter>%s%s</Image>%s'
                         % (indent, path, nl, indent, filt.group(1), nl, indent, nl))
        else:
            lines.append('%s<Image Include="%s" />%s' % (indent, path, nl))
    return text[:first.start()] + ''.join(lines) + rest


def fit(path):
    with Image.open(path) as im:
        im = im.convert('RGBA')
        w, h = im.size
        if max(w, h) > SIZE:
            scale = SIZE / max(w, h)
            size = (max(1, round(w * scale)), max(1, round(h * scale)))
            im = im.convert('RGBa').resize(size, Image.LANCZOS).convert('RGBA')
        if im.size[0] != im.size[1]:            # square canvas, centred, like the normal icons
            side = max(im.size)
            canvas = Image.new('RGBA', (side, side), (0, 0, 0, 0))
            canvas.paste(im, ((side - im.size[0]) // 2, (side - im.size[1]) // 2))
            im = canvas
        buf = io.BytesIO()
        im.save(buf, format='PNG', optimize=True)
        return buf.getvalue()


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--check', action='store_true')
    args = ap.parse_args()

    with open(RC, encoding='utf-8', newline='') as f:
        rc = f.read()
    nl = '\r\n' if '\r\n' in rc else '\n'
    normal = {m.group(1).upper(): os.path.splitext(m.group(2))[0]      # NAME -> file stem
              for m in re.finditer(r'^(\w+)\s+PNG\s+"icons\\\\([^"]+)"', rc, re.M)}

    wanted, unnamed, no_normal = {}, [], []     # resource name (upper) -> (file stem, where from)
    for ds in DATASETS:
        with open(os.path.join(RES, ds), encoding='utf-8') as f:
            data = json.load(f)
        for label in data['labels'].values():
            name = resource_name(label['clear_name'])
            if name is None:
                unnamed.append('%r (%s)' % (label['clear_name'], ds))
                continue
            token = name.upper()
            if token not in normal and token not in wanted:
                no_normal.append('%s (%s)' % (name, ds))
            wanted.setdefault(token, (normal.get(token, name), ds))
    with open(os.path.join(RES, 'ascension_materials.json'), encoding='utf-8') as f:
        mats = json.load(f)
    for kind in ('character', 'weapon'):
        for material in mats[kind].values():
            name = resource_name(material['clear_name'])
            if name is None:
                unnamed.append('%r (ascension_materials.json)' % material['clear_name'])
                continue
            wanted.setdefault(name.upper(), (name, 'ascension_materials.json'))

    over, up = file_index(OVERRIDES), file_index(UPSTREAM)
    if not up:
        sys.exit('upstream HD originals not found at %s (gitignored heavy_ref)' % UPSTREAM)

    outputs, entries, missing, from_override = {}, [], [], set()
    for token in sorted(wanted):
        stem, where = wanted[token]
        src = over.get(stem.lower()) or up.get(stem.lower())
        if src is None:
            missing.append('%s (%s)' % (stem, where))
            continue
        if stem.lower() in over:
            from_override.add(stem)
        outputs.setdefault(stem + '.png', src)
        entries.append('HD%-32s PNG                     "iconsHD\\\\%s.png"' % (token, stem))

    block = nl.join([BEGIN] + entries + [END])
    if BEGIN in rc:
        new_rc = re.sub(re.escape(BEGIN) + r'.*?' + re.escape(END), lambda m: block, rc, flags=re.S)
    else:                                        # first run: right after the last normal icon line
        lines = rc.split(nl)
        last = max(i for i, l in enumerate(lines) if re.match(r'^\w+\s+PNG\s+"icons\\', l))
        new_rc = nl.join(lines[:last + 1] + ['', block] + lines[last + 1:])

    rendered = {name: fit(src) for name, src in sorted(outputs.items())}
    current = {f for f in os.listdir(OUT) if f.lower().endswith('.png')} if os.path.isdir(OUT) else set()
    stale = sorted(current - set(rendered))
    changed = []
    for name, data in rendered.items():
        path = os.path.join(OUT, name)
        if not os.path.exists(path) or open(path, 'rb').read() != data:
            changed.append(name)

    print('HD icons: %d files, %.2f MB, %d resource names; from hd_icon_overrides: %s'
          % (len(rendered), sum(map(len, rendered.values())) / 1e6, len(entries),
             ', '.join(sorted(from_override)) or '-'))
    for title, items in (('no HD art (the normal icon is used)', missing),
                         ('no normal icon resource either', no_normal),
                         ('clear name rc.exe cannot carry', unnamed)):
        print('%s: %d%s' % (title, len(items), (' - ' + '; '.join(items)) if items else ''))

    projects = {}
    for proj in PROJECTS:
        with open(proj, encoding='utf-8', newline='') as f:
            old = f.read()
        new = sync_project(old, rendered)
        if new != old:
            projects[proj] = new

    if args.check:
        dirty = new_rc != rc or changed or stale or projects
        print('out of date' if dirty else 'up to date')
        sys.exit(1 if dirty else 0)

    os.makedirs(OUT, exist_ok=True)
    for name in changed:
        with open(os.path.join(OUT, name), 'wb') as f:
            f.write(rendered[name])
    for name in stale:
        os.remove(os.path.join(OUT, name))
    if new_rc != rc:
        with open(RC, 'w', encoding='utf-8', newline='') as f:
            f.write(new_rc)
    for proj, text in projects.items():
        with open(proj, 'w', encoding='utf-8', newline='') as f:
            f.write(text)
    print('wrote %d, removed %d, res.rc %s, project files updated: %d'
          % (len(changed), len(stale), 'updated' if new_rc != rc else 'unchanged', len(projects)))


if __name__ == '__main__':
    main()
