using System.Diagnostics;
using System.Globalization;
using System.Security.Cryptography.X509Certificates;
using System.Text;
using Microsoft.Win32;
using Relic.Core.Fiddler;
using Relic.Core.Install;
using Relic.Core.Isolation;
using Relic.Core.Play;
using Relic.Core.Server;
using Relic.Core.Util;

namespace Relic.Core.State;

/// <summary>What an uninstall should take with it beyond Relic's own program folder.</summary>
/// <param name="RemoveGames">Delete the downloaded game versions (tens of GB, opt-in).</param>
/// <param name="RemoveFiddler">Uninstall Fiddler and undo everything Relic configured in it —
/// prefs key, its data folder, and above all the trusted MITM root certificate.</param>
public sealed record CleanupOptions(bool RemoveGames = false, bool RemoveFiddler = true);

/// <summary>Outcome of a cleanup run: what went, what was left ON PURPOSE (a step that needs rights the
/// uninstaller never asks for, with the manual line), and what deliberately stayed behind (with the reason).</summary>
public sealed class CleanupReport
{
    public List<string> Removed { get; } = new();
    /// <summary>Left in place by design, not by failure — never turns the run into an error.</summary>
    public List<string> Kept { get; } = new();
    public List<string> Warnings { get; } = new();

    /// <summary>False when something had to be left behind — the caller turns this into an exit code.</summary>
    public bool Ok => Warnings.Count == 0;

    public string Text
    {
        get
        {
            var sb = new StringBuilder();
            foreach (string r in Removed) sb.AppendLine(L.T("core.uninstall.report.removed", new { item = r }));
            foreach (string k in Kept) sb.AppendLine(L.T("core.uninstall.report.kept", new { item = k }));
            foreach (string w in Warnings) sb.AppendLine(L.T("core.uninstall.report.warning", new { item = w }));
            return sb.ToString();
        }
    }
}

/// <summary>
/// Removes every trace Relic leaves OUTSIDE its own program folder, so the Inno uninstaller (which
/// only ever owned <c>{app}</c>) really does leave a clean machine behind. Without this, a reinstall
/// reads the surviving <c>%LOCALAPPDATA%\Relic\state.json</c> and believes multi-GB versions are
/// still installed after their folders are long gone.
///
/// Everything here is per-user (HKCU + the user profile) and needs no elevation, like the rest of
/// the launcher. The one genuinely dangerous step is the profile store: swapping is all-or-nothing,
/// so if a version's profile is still loaded, the OFFICIAL client's account data lives in
/// <c>profiles\live</c> and deleting that folder would destroy it. The live profile is therefore
/// restored FIRST, and if that cannot be done safely the profile store is kept and reported.
/// </summary>
public static class Uninstaller
{
    /// <summary>Everything Relic persists: state, logs, config, secrets, WebView2, profile slots.</summary>
    public static string AppDataDir => Path.Combine(
        Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData), "Relic");

    private static string ProfilesDir => Path.Combine(AppDataDir, "profiles");

    /// <summary>Fiddler's own per-user data folder (scripts, captures) — it is created by Fiddler,
    /// but Relic is what puts CustomRules.js in it.</summary>
    private static string FiddlerDataDir => Path.Combine(
        Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments), "Fiddler2");

    private const string FiddlerPrefsKey = @"HKCU\Software\Microsoft\Fiddler2";

    /// <summary>The marker FiddlerRules.Render writes into every CustomRules.js WE generate — the
    /// file is only deleted when it carries this, so a hand-written script of the user's survives.</summary>
    private const string RulesMarker = "Generated by Relic";

    // ── the run ──

    public static CleanupReport Run(CleanupOptions opt)
    {
        var r = new CleanupReport();
        var state = RelicState.Load();

        StopRunningRelic(r);
        StopFiddler(r);
        RemoveLocalAgent(r);
        RestoreLiveProfile(r, out bool profilesSafeToDelete);
        RemoveShortcuts(r, state);
        RemoveStartupEntry(r);
        RemoveFiddlerTraces(r, opt.RemoveFiddler);
        if (opt.RemoveGames) RemoveGames(r, state);

        // LAST: it holds the log we are writing into, and the profile slots checked above.
        RemoveAppData(r, profilesSafeToDelete);
        return r;
    }

    // ── step 1: nothing of ours may still be running ──

    /// <summary>Kill any other Relic instance (the tray one, typically). Killed rather than asked to
    /// close: a graceful shutdown can write state.json back out after we delete it.</summary>
    private static void StopRunningRelic(CleanupReport r)
    {
        int self = Environment.ProcessId;
        foreach (var p in Process.GetProcessesByName("Relic"))
        {
            try
            {
                if (p.Id == self) continue;
                p.Kill(entireProcessTree: true);
                p.WaitForExit(5000);
                r.Removed.Add(L.T("core.uninstall.removed.runningInstance", new { pid = p.Id }));
            }
            catch (Exception ex) { Log.Error($"could not stop Relic pid={p.Id} (non-fatal)", ex); }
            finally { p.Dispose(); }
        }
    }

    private static void StopFiddler(CleanupReport r)
    {
        try
        {
            if (!FiddlerAutomation.IsRunning) return;
            FiddlerAutomation.StopFiddler();
            r.Removed.Add(L.T("core.uninstall.removed.fiddlerStopped"));
        }
        catch (Exception ex) { Log.Error("stopping Fiddler at uninstall (non-fatal)", ex); }
    }

    /// <summary>The agent on this PC (Server Admin mode, Windows + Docker Desktop): its pythonw — found by
    /// the pid file OR by its listening port, an autostarted one has no pid file — its HKCU Run value and
    /// its folder, entry by entry. Without this step RemoveAppData deletes the folder while pythonw still
    /// holds agent.log open (a half-deleted folder) and leaves an orphan Run value pointing at a script that
    /// no longer exists. The firewall rule is the one thing that needs elevation, which the uninstaller
    /// never asks for: it is reported as kept, with the netsh line. The docker stacks are never touched.</summary>
    private static void RemoveLocalAgent(CleanupReport r)
    {
        try
        {
            if (!LocalAgent.IsInstalled && !Directory.Exists(LocalAgent.Root)) return;
            int port = LocalAgent.ReadConfig()?.ListenPort ?? ServerAddress.DefaultAgentPort;
            var rep = LocalAgent.Uninstall(port, removeFirewall: false, s => Log.Info("uninstall: " + s));
            r.Removed.Add(L.T("core.uninstall.removed.localAgent"));
            // A locked file (a hotpatch pack a client is being served) is a real leftover, like any other.
            foreach (string left in rep.Leftovers) r.Warnings.Add(left);
            if (LocalAgent.FirewallRuleExists(port))
                r.Kept.Add(L.T("core.uninstall.kept.firewallRule", new { port }));
        }
        catch (Exception ex) { Log.Error("removing the local agent at uninstall (non-fatal)", ex); }
    }

    // ── step 2: the official client's account data must be back in place ──

    /// <summary>
    /// Put the "live" profile back into the registry + LocalLow before the profile store is deleted.
    /// If a version's profile is still loaded, <c>profiles\live</c> is the ONLY copy of the official
    /// client's account data — deleting it would lose it permanently, so on any doubt the store is
    /// kept and the user is told.
    /// </summary>
    private static void RestoreLiveProfile(CleanupReport r, out bool safeToDelete)
    {
        safeToDelete = false;
        try
        {
            var profiles = ProfileStore.ForGenshin();
            if (profiles.LiveIsActive())
            {
                safeToDelete = true;   // the disk already holds live — nothing of value in the slots
                return;
            }

            using var gate = new Semaphore(1, 1, PlaySession.SessionGateName);
            if (!gate.WaitOne(0))
            {
                r.Warnings.Add(L.T("core.uninstall.warn.sessionActive", new { dir = ProfilesDir }));
                return;
            }
            try
            {
                if (!ProcessGuard.NoneRunningSustainedAsync().GetAwaiter().GetResult())
                {
                    r.Warnings.Add(L.T("core.uninstall.warn.clientRunning", new { dir = ProfilesDir }));
                    return;
                }

                if (profiles.RepairIfTorn())
                {
                    r.Removed.Add(L.T("core.uninstall.removed.tornRepaired"));
                }
                else if (profiles.IsTainted())
                {
                    // The official client ran on the still-loaded profile (ProfileStore.MarkTainted):
                    // live goes back without exporting the slot, whose mix would be deleted anyway.
                    string active = profiles.ActiveId();
                    Log.Info($"uninstall: profile '{active}' is tainted (the official client ran on it) — restoring live without exporting it");
                    profiles.RestoreLiveDiscarding();
                    r.Removed.Add(L.T("core.uninstall.removed.profileDiscarded", new { profile = active }));
                }
                else
                {
                    string active = profiles.ActiveId();
                    profiles.SwapTo(ProfileStore.LiveId, activeId: active);
                    r.Removed.Add(L.T("core.uninstall.removed.profileRestored", new { profile = active }));
                }
                safeToDelete = true;
            }
            finally { gate.Release(); }
        }
        catch (Exception ex)
        {
            Log.Error("restoring the live profile at uninstall", ex);
            r.Warnings.Add(L.T("core.uninstall.warn.restoreFailed", new { error = ex.Message, dir = ProfilesDir }));
        }
    }

    // ── step 3: shortcuts + autostart ──

    /// <summary>Remove every desktop shortcut that points at Relic.exe — the per-version "Game 1.6"
    /// ones InstallService creates are unknown to the Inno uninstaller, and matching by TARGET rather
    /// than by name also catches shortcuts whose registration was already lost from state.json.</summary>
    private static void RemoveShortcuts(CleanupReport r, RelicState state)
    {
        try
        {
            string exe = Environment.ProcessPath ?? "";
            int n = exe.Length > 0 ? Shortcut.DeletePointingTo(exe) : 0;
            if (n > 0) r.Removed.Add(L.T("core.uninstall.removed.shortcuts", new { count = n }));
        }
        catch (Exception ex) { Log.Error("deleting the shortcuts (non-fatal)", ex); }

        // Belt and braces for a build whose exe path no longer matches (moved install dir):
        // the names we recorded ourselves.
        foreach (var inst in state.Installed)
        {
            if (string.IsNullOrWhiteSpace(inst.ShortcutName)) continue;
            TryDeleteFile(r, Path.Combine(Shortcut.DesktopDir, inst.ShortcutName + ".lnk"), quiet: true);
        }
    }

    private static void RemoveStartupEntry(CleanupReport r)
    {
        // The RunOnce logon-recovery value (armed while a private profile is loaded) is normally gone
        // by now — RestoreLiveProfile's LoadProfile(live) removed it — but a value pointing at an exe
        // that is about to be deleted must never survive an uninstall, whatever happened above.
        try { Startup.DisarmLogonRecovery(); }
        catch (Exception ex) { Log.Error("deleting the logon-recovery entry (non-fatal)", ex); }
        try
        {
            if (!Startup.IsEnabled()) return;
            Startup.Set(false, "");
            r.Removed.Add(L.T("core.uninstall.removed.autostart"));
        }
        catch (Exception ex) { Log.Error("deleting the autostart entry (non-fatal)", ex); }
    }

    // ── step 4: Fiddler ──

    private static void RemoveFiddlerTraces(CleanupReport r, bool removeFiddler)
    {
        // Always: the redirect script IS ours. Only when it still carries our marker, so a script
        // the user wrote by hand afterwards is never thrown away.
        try
        {
            string rules = FiddlerAutomation.CustomRulesPath;
            if (File.Exists(rules) && File.ReadAllText(rules).Contains(RulesMarker, StringComparison.Ordinal))
            {
                File.Delete(rules);
                r.Removed.Add(rules);
            }
        }
        catch (Exception ex) { Log.Error("deleting CustomRules.js (non-fatal)", ex); }

        if (!removeFiddler) return;

        RemoveFiddlerRootCert(r);
        UninstallFiddler(r);
        TryRegDelete(r, FiddlerPrefsKey, L.T("core.uninstall.removed.fiddlerPrefs"));
        TryDeleteDir(r, FiddlerDataDir);
    }

    /// <summary>
    /// Untrust (and delete) the Fiddler MITM root certificate.
    ///
    /// The trust is REMOVED through the registry rather than through <c>X509Store.Remove</c> because
    /// the CurrentUser Root store is protected in BOTH directions: the API raises its own consent
    /// dialog for a delete too, and an uninstall that stops on a modal prompt is an uninstall that
    /// half-runs. This does not weaken the "never silently plant the cert blob" invariant — that rule
    /// exists to stop us GRANTING machine-wide interception without the user knowing; taking it away
    /// can only ever reduce what the machine trusts.
    /// </summary>
    private static void RemoveFiddlerRootCert(CleanupReport r)
    {
        var thumbs = new List<string>();
        try
        {
            using var root = new X509Store(StoreName.Root, StoreLocation.CurrentUser);
            root.Open(OpenFlags.ReadOnly);
            foreach (var c in root.Certificates)
                if (c.Subject.Contains(FiddlerAutomation.CertSubjectMarker, StringComparison.OrdinalIgnoreCase))
                    thumbs.Add(c.Thumbprint);
        }
        catch (Exception ex) { Log.Error("reading the Root store (non-fatal)", ex); }

        foreach (string t in thumbs)
        {
            TryRegDelete(r, $@"HKCU\Software\Microsoft\SystemCertificates\Root\Certificates\{t}",
                L.T("core.uninstall.removed.rootCert", new { thumb = t[..Math.Min(8, t.Length)] }));
        }

        // The matching PRIVATE key in CurrentUser\My — a live MITM signing key that must not outlive
        // the tool that needed it. This store is not protected, so the API path is silent here.
        try
        {
            using var my = new X509Store(StoreName.My, StoreLocation.CurrentUser);
            my.Open(OpenFlags.ReadWrite);
            var mine = my.Certificates
                .Where(c => c.Subject.Contains(FiddlerAutomation.CertSubjectMarker, StringComparison.OrdinalIgnoreCase))
                .ToArray();
            foreach (var c in mine) my.Remove(c);
            if (mine.Length > 0) r.Removed.Add(L.T("core.uninstall.removed.certKey"));
        }
        catch (Exception ex) { Log.Error("removing the Fiddler certificate from My (non-fatal)", ex); }

        // A cert trusted MACHINE-wide (an older install done by hand, as administrator) lives in
        // HKLM and cannot be removed without elevation — say so instead of reporting a clean sweep.
        try
        {
            if (FiddlerAutomation.IsRootCertTrusted())
                r.Warnings.Add(L.T("core.uninstall.warn.machineCert"));
        }
        catch (Exception ex) { Log.Error("final certificate check (non-fatal)", ex); }
    }

    /// <summary>Run Fiddler's own NSIS uninstaller silently. Per-user installs (what Relic produces)
    /// need no elevation; a per-machine one would, so that case is reported instead of prompting.</summary>
    private static void UninstallFiddler(CleanupReport r)
    {
        string? dir = Path.GetDirectoryName(FiddlerAutomation.InstalledFiddlerExe);
        if (dir is null) return;

        string perUserRoot = FiddlerAutomation.DefaultInstallDir;
        if (!dir.StartsWith(perUserRoot, StringComparison.OrdinalIgnoreCase))
        {
            r.Warnings.Add(L.T("core.uninstall.warn.fiddlerMachineWide", new { dir }));
            return;
        }

        string? uninst = FindUninstallString() ?? FirstExisting(
            Path.Combine(dir, "uninstall.exe"), Path.Combine(dir, "Uninstall.exe"));
        if (uninst is null)
        {
            r.Warnings.Add(L.T("core.uninstall.warn.noFiddlerUninstaller", new { dir }));
            return;
        }

        try
        {
            var psi = new ProcessStartInfo(uninst)
            {
                UseShellExecute = false,
                CreateNoWindow = true,
                Arguments = "/S",
                WorkingDirectory = dir,
            };
            // Same reason as the install: the NSIS manifest asks for "highestAvailable", so on an
            // admin account Windows would pop a UAC prompt for something that only ever touches the
            // user profile. RunAsInvoker answers that request with our own token.
            psi.Environment["__COMPAT_LAYER"] = "RunAsInvoker";
            using var p = Process.Start(psi);
            p?.WaitForExit(60_000);
            // NSIS relaunches itself from %TEMP% and detaches, so give the real worker a moment.
            for (int i = 0; i < 15 && FiddlerAutomation.IsInstalled; i++) Thread.Sleep(1000);
            if (FiddlerAutomation.IsInstalled)
            {
                TryDeleteDir(r, dir);
                if (Directory.Exists(dir))
                    r.Warnings.Add(L.T("core.uninstall.warn.fiddlerLeftover", new { dir }));
            }
            else
            {
                r.Removed.Add(L.T("core.uninstall.removed.fiddler"));
            }
        }
        catch (Exception ex)
        {
            Log.Error("uninstalling Fiddler (non-fatal)", ex);
            r.Warnings.Add(L.T("core.uninstall.warn.fiddlerUninstallFailed", new { error = ex.Message }));
        }
    }

    /// <summary>Fiddler's UninstallString from the per-user uninstall list (the key name has changed
    /// across Fiddler releases, so match on DisplayName instead of guessing it).</summary>
    private static string? FindUninstallString()
    {
        try
        {
            using var list = Registry.CurrentUser.OpenSubKey(
                @"Software\Microsoft\Windows\CurrentVersion\Uninstall");
            if (list is null) return null;
            foreach (string name in list.GetSubKeyNames())
            {
                using var k = list.OpenSubKey(name);
                if (k?.GetValue("DisplayName") is not string dn ||
                    !dn.StartsWith("Fiddler", StringComparison.OrdinalIgnoreCase)) continue;
                if (k.GetValue("UninstallString") is not string us || us.Length == 0) continue;
                string exe = us.StartsWith('"') ? us[1..(us.IndexOf('"', 1) is var e && e > 1 ? e : us.Length)]
                                                : us.Split(' ')[0];
                if (File.Exists(exe)) return exe;
            }
        }
        catch (Exception ex) { Log.Error("reading Fiddler's UninstallString (non-fatal)", ex); }
        return null;
    }

    // ── step 5: the downloaded games (opt-in) ──

    /// <summary>Delete the installed versions. Both the registered ones and any <c>Genshin &lt;id&gt;</c>
    /// folder left in the install root by an earlier install whose state was already lost — that
    /// orphan is exactly what makes a "clean" reinstall look half-installed.</summary>
    private static void RemoveGames(CleanupReport r, RelicState state)
    {
        var roots = new HashSet<string>(StringComparer.OrdinalIgnoreCase);

        foreach (var inst in state.Installed)
        {
            // Only ever the path WE compute for that id — never an arbitrary string from state.json.
            if (string.IsNullOrWhiteSpace(inst.GameDir)) continue;
            if (!string.Equals(Path.GetFileName(Path.TrimEndingDirectorySeparator(inst.GameDir)),
                    $"Genshin {inst.Id}", StringComparison.OrdinalIgnoreCase)) continue;
            TryDeleteDir(r, inst.GameDir);
            string? parent = Path.GetDirectoryName(Path.TrimEndingDirectorySeparator(inst.GameDir));
            if (parent is not null) roots.Add(parent);
        }

        roots.Add(state.Settings.InstallRoot);
        roots.Add(Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.UserProfile), "Relic Games"));

        foreach (string root in roots)
        {
            if (!Directory.Exists(root)) continue;
            try
            {
                foreach (string d in Directory.GetDirectories(root, "Genshin *"))
                    TryDeleteDir(r, d);
                if (Directory.GetFileSystemEntries(root).Length == 0)
                    TryDeleteDir(r, root);
            }
            catch (Exception ex) { Log.Error($"cleaning the install folder {root} (non-fatal)", ex); }
        }
    }

    // ── step 6: our own data folder ──

    private static void RemoveAppData(CleanupReport r, bool profilesSafeToDelete)
    {
        if (!Directory.Exists(AppDataDir)) return;

        if (profilesSafeToDelete)
        {
            // Nothing may write here afterwards: a single Log line would recreate the folder we are
            // deleting and leave the machine looking un-cleaned again.
            Log.Disabled = true;
            TryDeleteDir(r, AppDataDir);
            return;
        }

        // The profile store still holds the only copy of the official client's account data.
        foreach (string entry in SafeEnumerate(AppDataDir))
        {
            if (string.Equals(Path.GetFileName(entry), "profiles", StringComparison.OrdinalIgnoreCase)) continue;
            if (Directory.Exists(entry)) TryDeleteDir(r, entry, quiet: true);
            else TryDeleteFile(r, entry, quiet: true);
        }
        r.Removed.Add(L.T("core.uninstall.removed.appDataPartial", new { dir = AppDataDir }));
        try
        {
            File.WriteAllText(Path.Combine(AppDataDir, "READ-ME.txt"),
                L.T("core.uninstall.readme.title") + "\r\n\r\n" +
                L.T("core.uninstall.readme.why") + "\r\n\r\n" +
                L.T("core.uninstall.readme.what") + "\r\n");
        }
        catch (Exception ex) { Log.Error("writing READ-ME.txt (non-fatal)", ex); }
    }

    // ── probe (what the uninstaller shows the user BEFORE it starts) ──

    /// <summary>
    /// Write a tiny key=value file the Inno uninstaller reads to build its options page — how many
    /// GB of games would be deleted, whether Fiddler is even installed. Kept out of the Pascal script
    /// because the install root and the version list only exist in state.json.
    /// </summary>
    public static void WriteProbe(string path)
    {
        var state = RelicState.Load();
        var sb = new StringBuilder();

        var dirs = new List<string>();
        foreach (var inst in state.Installed)
            if (!string.IsNullOrWhiteSpace(inst.GameDir) && Directory.Exists(inst.GameDir))
                dirs.Add(inst.GameDir);
        foreach (string root in new[] { state.Settings.InstallRoot })
        {
            if (!Directory.Exists(root)) continue;
            try
            {
                foreach (string d in Directory.GetDirectories(root, "Genshin *"))
                    if (!dirs.Contains(d, StringComparer.OrdinalIgnoreCase)) dirs.Add(d);
            }
            catch (Exception ex) { Log.Error($"probe: enumerating {root} (non-fatal)", ex); }
        }

        long bytes = dirs.Sum(DirectorySize);
        sb.AppendLine($"installRoot={state.Settings.InstallRoot}");
        sb.AppendLine($"games={string.Join('|', dirs.Select(d => Path.GetFileName(Path.TrimEndingDirectorySeparator(d))))}");
        sb.AppendLine($"gameCount={dirs.Count}");
        sb.AppendLine($"gamesBytes={bytes.ToString(CultureInfo.InvariantCulture)}");
        sb.AppendLine($"gamesText={Human(bytes)}");
        sb.AppendLine($"fiddler={(FiddlerAutomation.IsInstalled ? 1 : 0)}");
        sb.AppendLine($"certTrusted={(FiddlerAutomation.IsRootCertTrusted() ? 1 : 0)}");

        Directory.CreateDirectory(Path.GetDirectoryName(path)!);
        File.WriteAllText(path, sb.ToString(), Encoding.UTF8);
    }

    private static long DirectorySize(string dir)
    {
        try
        {
            long total = 0;
            var opts = new EnumerationOptions { RecurseSubdirectories = true, IgnoreInaccessible = true };
            foreach (string f in Directory.EnumerateFiles(dir, "*", opts))
            {
                try { total += new FileInfo(f).Length; } catch { /* vanished mid-walk */ }
            }
            return total;
        }
        catch (Exception ex) { Log.Error($"measuring {dir} (non-fatal)", ex); return 0; }
    }

    private static string Human(long bytes)
    {
        string[] u = { "B", "KB", "MB", "GB", "TB" };
        double n = bytes; int i = 0;
        while (n >= 1024 && i < u.Length - 1) { n /= 1024; i++; }
        return string.Create(CultureInfo.InvariantCulture, $"{n:0.0} {u[i]}");
    }

    // ── helpers ──

    private static IEnumerable<string> SafeEnumerate(string dir)
    {
        try { return Directory.GetFileSystemEntries(dir); }
        catch (Exception ex) { Log.Error($"enumerating {dir} (non-fatal)", ex); return Array.Empty<string>(); }
    }

    private static string? FirstExisting(params string[] paths) => paths.FirstOrDefault(File.Exists);

    private static void TryDeleteFile(CleanupReport r, string path, bool quiet = false)
    {
        try
        {
            if (!File.Exists(path)) return;
            File.SetAttributes(path, FileAttributes.Normal);
            File.Delete(path);
            if (!quiet) r.Removed.Add(path);
        }
        catch (Exception ex)
        {
            Log.Error($"deleting {path}", ex);
            r.Warnings.Add(L.T("core.uninstall.warn.deleteFailed", new { path, error = ex.Message }));
        }
    }

    /// <summary>Recursive delete with one retry — a virus scanner or an Explorer window holding a
    /// handle for a moment must not be what leaves the machine half-cleaned.</summary>
    private static void TryDeleteDir(CleanupReport r, string path, bool quiet = false)
    {
        for (int attempt = 1; attempt <= 2; attempt++)
        {
            try
            {
                if (!Directory.Exists(path)) return;
                Directory.Delete(path, recursive: true);
                if (!quiet) r.Removed.Add(path);
                return;
            }
            catch (Exception ex) when (attempt == 1 && ex is IOException or UnauthorizedAccessException)
            {
                Log.Error($"deleting {path} — retrying", ex);
                Thread.Sleep(750);
            }
            catch (Exception ex)
            {
                Log.Error($"deleting {path}", ex);
                r.Warnings.Add(L.T("core.uninstall.warn.deleteFailed", new { path, error = ex.Message }));
                return;
            }
        }
        if (Directory.Exists(path))
            r.Warnings.Add(L.T("core.uninstall.warn.deleteInUse", new { path }));
    }

    private static void TryRegDelete(CleanupReport r, string key, string label)
    {
        var res = Proc.Run("reg", "query", key);
        if (!res.Ok) return;                       // not there — nothing to report
        var del = Proc.Run("reg", "delete", key, "/f");
        if (del.Ok) r.Removed.Add(label);
        else r.Warnings.Add(L.T("core.uninstall.warn.regDeleteFailed", new { key, error = del.Err.Trim() }));
    }
}
