// Relic: the 3.3 reference build has no metadata dump under dumps_ref/ (its appdata is upstream v1.2.3 as
// published), so there is nothing to pin the generated layouts against here. 1.6 and 2.8 carry the real
// assertions, regenerated by tools/gen_field_asserts.py; 3.3 is kept buildable, never shipped.
#pragma once
