// Generated C++ file by Il2CppInspector - http://www.djkaty.com - https://github.com/djkaty
// Relic: game 1.6 (OS) offsets generated by tools/gen_appdata16.py from dumps_ref/1.6/match16.json (tools/matcher16.py)
// -- every line carries its matching rule and confidence; 0x0 = RELIC-TODO-16 (null pointer at run time). Do not edit by hand:
//    hand decisions go to tools/offsets-16.overrides.json (apply_overrides.py --ver 16).
// Target Unity version: 2017.4.15 - 2017.4.40

// ******************************************************************************
// * IL2CPP application-specific method definition addresses and signatures
// ******************************************************************************
using namespace app;


// Map hooks
DO_APP_FUNC(0x00B06D90, void, MoleMole_InLevelMapPageContext_OnMarkClicked, (InLevelMapPageContext* __this, MonoMapMark* mark, MethodInfo* method));  // 1.6: M-fp (high) BPDBBEDHBCP$$KDDNLOHDDGM | fp 0.38 (7 shared strings/calls), runner-up 0.69
DO_APP_FUNC(0x00AD6BC0, void, MoleMole_InLevelMapPageContext_OnMapClicked, (InLevelMapPageContext* __this, Vector2 screenPos, MethodInfo* method));  // 1.6: M-fp (high) BPDBBEDHBCP$$AKNOFKKGIEB | fp 0.47 (4 shared strings/calls), runner-up 0.44
DO_APP_FUNC(0x01C32A30, bool, MoleMole_MapModule_IsAreaUnlock, (MoleMole_MapModule* __this, uint32_t sceneID, uint32_t areaID, MethodInfo* method));  // 1.6: M-pos (medium) MHGOONJMBFO$$JACLCECKIBA | declaration-order alignment (lists align 0.86); fp 0.00; runner-up 0.28


// should be 'op_Implicit' not 'get_value'
DO_APP_FUNC(0x00A89020, uint16_t, MoleMole_SimpleSafeUInt16_get_Value__RAW, (void* __this_unused, SimpleSafeUInt16 v, MethodInfo* method));  // 1.6: M-sig (high) IEJDJMDLBJF$$GJADJEFIFBE | only compatible signature in IEJDJMDLBJF; fp 0.00, 0 shared; method lists align 0.92
DO_APP_FUNC(0x038CC030, uint32_t, MoleMole_SimpleSafeUInt32_get_Value__RAW, (void* __this_unused, SimpleSafeUInt32 v, MethodInfo* method));  // 1.6: M-sig (high) BMGMMFKLOLL$$GJADJEFIFBE | only compatible signature in BMGMMFKLOLL; fp 0.00, 0 shared; method lists align 0.93
DO_APP_FUNC(0x04B18EE0, String*, Marshal_PtrToStringAnsi__RAW, (void* __this_unused, void* ptr, MethodInfo* method));  // 1.6: M-name (high) System.Runtime.InteropServices.Marshal$$PtrToStringAnsi


// Map utility
DO_APP_FUNC(0x02D97E80, Rect, MonoInLevelMapPage_get_mapRect, (MonoInLevelMapPage* __this, MethodInfo* method));  // 1.6: M-name (high) MoleMole.MonoInLevelMapPage$$get_mapRect
DO_APP_FUNC(0x02D97E10, Transform*, MonoInLevelMapPage_get_mapBackground, (MonoInLevelMapPage* __this, MethodInfo* method));  // 1.6: M-name (high) MoleMole.MonoInLevelMapPage$$get_mapBackground


// Teleport hooks
DO_APP_FUNC(0x01CC5520, void, GameManager_Update, (GameManager* __this, MethodInfo* method));  // 1.6: M-name (high) MoleMole.GameManager$$Update
DO_APP_FUNC(0x01219CE0, void, MoleMole_LoadingManager_SceneGoto, (MoleMole_LoadingManager* __this, PlayerEnterSceneNotify* notify, MethodInfo* method));  // 1.6: M-pos (medium) FFHBJKFKMOC$$DCCJNANGCDE | declaration-order alignment (lists align 0.96); fp 0.20; runner-up 0.73
DO_APP_FUNC(0x0121ADE0, void, MoleMole_LoadingManager_PerformPlayerTransmit, (MoleMole_LoadingManager* __this, Vector3 targetPos, EnterType__Enum enterType, uint32_t token, EvtTransmitAvatar_EvtTransmitAvatar_TransmitType__Enum transType, uint32_t enterReason, MethodInfo* method));  // 1.6: M-sig (high) FFHBJKFKMOC$$EFIKHJBGOBM | only compatible signature in FFHBJKFKMOC; fp 0.12, 0 shared; method lists align 0.96
DO_APP_FUNC(0x0121CF60, void, MoleMole_LoadingManager_RequestSceneTransToPoint, (MoleMole_LoadingManager* __this, uint32_t sceneId, uint32_t pointId, void* finishCallBackInForceDrag, MethodInfo* method));  // 1.6: M-sig (high) FFHBJKFKMOC$$KAELCGPCAPC | only compatible signature in FFHBJKFKMOC; fp 0.14, 2 shared; method lists align 0.96
DO_APP_FUNC(0x0121FA10, bool, MoleMole_LoadingManager_NeedTransByServer, (MoleMole_LoadingManager* __this, uint32_t sceneId, Vector3 position, MethodInfo* method));  // 1.6: M-sig (high) FFHBJKFKMOC$$PJHJHHBDGMJ | only compatible signature in FFHBJKFKMOC; fp 0.22, 1 shared; method lists align 0.96
DO_APP_FUNC(0x018CDBE0, Vector3, MoleMole_LocalEntityInfoData_get_initPos, (LocalEntityInfoData* __this, MethodInfo* method)); // shared offset // 1.6: M-pos (medium) FNJKAGOFALK$$DLEEIKCNNHL | declaration-order alignment (lists align 0.94); fp 0.00; runner-up 0.41


// Unlimited stamina
DO_APP_FUNC(0x01C73400, void, MoleMole_LevelSyncCombatPlugin_RequestSceneEntityMoveReq, (LevelSyncCombatPlugin* __this, uint32_t entityId, MotionInfo* syncInfo, bool isReliable, uint32_t HAOCOEMOMBG, MethodInfo* method));  // 1.6: M-pos (medium) IPCPELCOPAM$$KGDJCMHPHIB | declaration-order alignment (lists align 0.75); fp 0.00; runner-up 0.55
DO_APP_FUNC(0x03429B20, void, MoleMole_DataItem_HandleNormalProp, (DataItem* __this, uint32_t type, int64_t value, DataPropOp__Enum state, MethodInfo* method));  // 1.6: M-sig (high) HBLAHJFGLLD$$BKOBFCGMDBE | only compatible signature in HBLAHJFGLLD; fp 0.36, 2 shared; method lists align 0.93


// God mode
DO_APP_FUNC(0x025C1F60, void, VCHumanoidMove_NotifyLandVelocity, (VCHumanoidMove* __this, Vector3 velocity, float reachMaxDownVelocityTime, MethodInfo* method));  // 1.6: M-pos (medium) MoleMole.VCHumanoidMove$$OCHJLJNLEHH | declaration-order alignment (lists align 0.89); fp 0.32; runner-up 0.56
DO_APP_FUNC(0x00FF5470, bool, Miscs_CheckTargetAttackable, (void* __this_unused, BaseEntity* attackerEntity, BaseEntity* targetEntity, MethodInfo* method));  // 1.6: M-name (high) MoleMole.Miscs$$CheckTargetAttackable  // Relic 1.6: static -> leading dummy `this` (the hook handler carries it too)
DO_APP_FUNC(0x017A14A0, void, MoleMole_LCBaseCombat_FireBeingHitEvent, (LCBaseCombat* __this, uint32_t attackeeRuntimeID, AttackResult* attackResult, MethodInfo* method));  // 1.6: M-pos (medium) PMBPGLIKLGN$$GNIKHGEJCLD | declaration-order alignment (lists align 0.91); fp 0.00; runner-up 0.55
DO_APP_FUNC(0x00A345C0, bool, MoleMole_ActorAbilityPlugin_HanlderModifierThinkTimerUp, (ActorAbilityPlugin* __this, float delay, Object* arg, MethodInfo* method));  // 1.6: M-sig (high) AEOLLPABFCP$$DHLLLLHOCCH | only compatible signature in AEOLLPABFCP; fp 0.00, 0 shared; method lists align 0.82


// Cooldown cheats
DO_APP_FUNC(0x015B3F90, bool, MoleMole_HumanoidMoveFSM_CheckSprintCooldown, (/* HumanoidMoveFSM */void* __this, MethodInfo* method));  // 1.6: M-pos (medium) NCPJNIIMLOG$$LOMMILFHOCA | declaration-order alignment (lists align 0.94); fp 0.00; runner-up 0.30
DO_APP_FUNC(0x0166E180, bool, MoleMole_LCAvatarCombat_IsEnergyMax, (void* __this, MethodInfo* method));  // 1.6: M-pos (medium) DIIAFDKMCEE$$AOMDOBHNLNC | declaration-order alignment (lists align 0.91); fp 0.00; runner-up 0.20
DO_APP_FUNC(0x0166FFE0, void, MoleMole_LCAvatarCombat_ChangeEnergy_1, (LCAvatarCombat* __this, ElementType__Enum type, float value, DataPropOp__Enum state, MethodInfo* method));  // 1.6: M-pos (medium) DIIAFDKMCEE$$DPOBJOEEFNE | declaration-order alignment (lists align 0.91); fp 0.00; runner-up 0.63
DO_APP_FUNC(0x01674FC0, bool, MoleMole_LCAvatarCombat_OnSkillStart, (LCAvatarCombat* __this, uint32_t skillID, float cdMultipler, MethodInfo* method));  // 1.6: M-sig (high) DIIAFDKMCEE$$LPCFKIJFOGP | only compatible signature in DIIAFDKMCEE; fp 0.43, 0 shared; method lists align 0.91
DO_APP_FUNC(0x01674D40, bool, MoleMole_LCAvatarCombat_IsSkillInCD_1, (LCAvatarCombat* __this, LCAvatarCombat_LCAvatarCombat_SkillInfo* skillInfo, MethodInfo* method));  // 1.6: M-pos (medium) DIIAFDKMCEE$$LLLIEMDAFLH | declaration-order alignment (lists align 0.91); fp 0.00; runner-up 0.60
DO_APP_FUNC(0x00A59900, void, MoleMole_ActorAbilityPlugin_AddDynamicFloatWithRange, (MoleMole_ActorAbilityPlugin* __this, String* key, float value, float min, float max, bool forceDoAtRemote, MethodInfo* method));  // 1.6: M-pos (medium) AEOLLPABFCP$$KDMMLHECGBN | declaration-order alignment (lists align 0.82); fp 0.22; runner-up 0.52
  
// Rapid fire
DO_APP_FUNC(0x0179FCB0, void, MoleMole_LCBaseCombat_DoHitEntity, (LCBaseCombat* __this, uint32_t targetID, AttackResult* attackResult, bool ignoreCheckCanBeHitInMP, MethodInfo* method));  // 1.6: M-fp (medium) PMBPGLIKLGN$$EHGCFNBABCF | fp 0.32 (2 shared strings/calls), runner-up 0.52
DO_APP_FUNC(0x0289AC70, void, MoleMole_Formula_CalcAttackResult__RAW, (void* __this_unused, CombatProperty* attackCombatProperty, CombatProperty* defenseCombatProperty, AttackResult* attackResult, BaseEntity* attackerEntity, BaseEntity* attackeeEntity, MethodInfo* method));  // 1.6: M-sig (high) CIDPEKCCCNL$$IFHAIIDELNA | only compatible signature in CIDPEKCCCNL; fp 0.11, 4 shared; method lists align 0.88
DO_APP_FUNC(0x035AD380, void, MoleMole_VCAnimatorEvent_HandleProcessItem, (MoleMole_VCAnimatorEvent* __this, MoleMole_VCAnimatorEvent_MoleMole_VCAnimatorEvent_AnimatorEventPatternProcessItem* processItem, AnimatorStateInfo processStateInfo, MoleMole_VCAnimatorEvent_MoleMole_VCAnimatorEvent_TriggerMode__Enum mode, MethodInfo* method));  // 1.6: M-sig (high) AJJDAJJHKNL$$OFMKAACLEOM | only compatible signature in AJJDAJJHKNL; fp 0.68, 4 shared; method lists align 0.95


// World cheats
DO_APP_FUNC(0x015397F0, void, MoleMole_VCMonsterAIController_TryDoSkill, (/* VCMonsterAIController */ void* __this, uint32_t skillID, MethodInfo* method)); // Manual // 1.6: M-pos (medium) ENANLPGPCFE$$ICCCIJPKBCK | declaration-order alignment (lists align 0.85); fp 0.14; runner-up 0.23
DO_APP_FUNC(0x01E10490, void, MoleMole_LCSelectPickup_AddInteeBtnByID, (void* __this, BaseEntity* entity, MethodInfo* method));  // 1.6: M-sig (high) GFKHGAFJPPE$$OCBKPBCIOKD | only compatible signature in GFKHGAFJPPE; fp 0.23, 3 shared; method lists align 0.95
DO_APP_FUNC(0x01E10E30, bool, MoleMole_LCSelectPickup_IsInPosition, (void* __this, BaseEntity* entity, MethodInfo* method));  // 1.6: M-pos (medium) GFKHGAFJPPE$$PLCFDAHJJOK | declaration-order alignment (lists align 0.95); fp 0.00; runner-up 0.51
DO_APP_FUNC(0x01E10D00, bool, MoleMole_LCSelectPickup_IsOutPosition, (void* __this, BaseEntity* entity, MethodInfo* method));  // 1.6: M-pos (medium) GFKHGAFJPPE$$OGCJOHACFOE | declaration-order alignment (lists align 0.95); fp 0.00; runner-up 0.51
DO_APP_FUNC(0x0143F090, void, MoleMole_ItemModule_PickItem, (MoleMole_ItemModule* __this, uint32_t entityID, MethodInfo* method));  // 1.6: M-sig (high) GEJMEJDKBIM$$GIOEKOGJDJP | only compatible signature in GEJMEJDKBIM; fp 0.23, 4 shared; method lists align 0.91
DO_APP_FUNC(0x011A6AE0, void, MoleMole_LevelSceneElementViewPlugin_Tick, (LevelSceneElementViewPlugin* __this, float inDeltaTime, MethodInfo* method));  // 1.6: M-name (high) GHBKMJCJELB$$Tick


// Dialog skipping
DO_APP_FUNC(0x029FEAF0, bool, MoleMole_TalkDialogContext_get_canClick, (TalkDialogContext* __this, MethodInfo* method)); // delete // 1.6: M-fp (high) JAHCJKMMDNL$$GPIIGNLJCEE | fp 0.60 (3 shared strings/calls), runner-up 0.24
DO_APP_FUNC(0x0, bool, MoleMole_TalkDialogContext_get_canAutoClick, (TalkDialogContext* __this, MethodInfo* method));  // RELIC-TODO-16 3 compatible signatures in JAHCJKMMDNL, no clear winner (best 0.46 vs 0.26)
DO_APP_FUNC(0x02A026C0, void, MoleMole_TalkDialogContext_OnDialogSelectItem, (TalkDialogContext* __this, Notify* notify, MethodInfo* method));  // 1.6: M-pos (medium) JAHCJKMMDNL$$PNHIPBHHNFO | declaration-order alignment (lists align 0.91); fp 0.08; runner-up 0.53
DO_APP_FUNC(0x01EFE5D0, void, MoleMole_InLevelCutScenePageContext_OnFreeClick, (InLevelCutScenePageContext* __this, MethodInfo* method));  // 1.6: M-pos (medium) LLDEKOIJFCF$$KGGEGAEAFHN | declaration-order alignment (lists align 0.92); fp 0.12; runner-up 0.25
DO_APP_FUNC(0x01EFFD10, void, MoleMole_InLevelCutScenePageContext_UpdateView, (InLevelCutScenePageContext* __this, MethodInfo* method));  // 1.6: M-name (high) LLDEKOIJFCF$$UpdateView
DO_APP_FUNC(0x01EFD330, void, MoleMole_InLevelCutScenePageContext_ClearView, (InLevelCutScenePageContext* __this, MethodInfo* method));  // 1.6: M-name (high) LLDEKOIJFCF$$ClearView
// Skip Cutscene | RyujinZX#6666
DO_APP_FUNC(0x03821240, void, CriwareMediaPlayer_Update, (CriwareMediaPlayer* __this, MethodInfo* method));  // 1.6: M-name (high) MoleMole.CriwareMediaPlayer$$Update
DO_APP_FUNC(0x038210C0, void, CriwareMediaPlayer_Skip, (CriwareMediaPlayer* __this, MethodInfo* method));  // 1.6: M-name (high) MoleMole.CriwareMediaPlayer$$Skip


// Protection bypass
DO_APP_FUNC(0x053E3B00, Byte__Array*, Application_RecordUserData__RAW, (void* __this_unused, int32_t nType, MethodInfo* method));  // 1.6: M-name (high) UnityEngine.Application$$RecordUserData


// Networking
DO_APP_FUNC(0x02C972F0, void, Kcp_KcpNative_kcp_packet_destroy__RAW, (void* __this_unused, KcpPacket_1* packet, MethodInfo* method));  // 1.6: M-sig (high) HGOCAMCEDFA$$ABCCIADHHDL | only compatible signature in HGOCAMCEDFA; fp 0.00, 0 shared; method lists align 0.89
DO_APP_FUNC(0x02C97BD0, KcpPacket_1*, Kcp_KcpNative_kcp_packet_create__RAW, (void* __this_unused, uint8_t* data, int32_t len, MethodInfo* method));  // 1.6: M-pos (medium) HGOCAMCEDFA$$NBJIGFDDKNJ | declaration-order alignment (lists align 0.89); fp 0.00; runner-up 0.40
DO_APP_FUNC(0x02C976C0, int32_t, Kcp_KcpNative_kcp_client_send_packet, (void* __this_unused, void* kcp_client, KcpPacket_1* packet, MethodInfo* method));  // 1.6: M-sig (high) HGOCAMCEDFA$$GKEIKELLHGD | only compatible signature in HGOCAMCEDFA; fp 0.00, 0 shared; method lists align 0.89  // Relic 1.6: static -> leading dummy `this` (the hook handler carries it too)
DO_APP_FUNC(0x02B19A00, bool, MoleMole_KcpClient_TryDequeueEvent, (void* __this, ClientKcpEvent* evt, MethodInfo* method));  // 1.6: M-sig (high) JPBBNJMIGOM$$DHDDBAELGNA | only compatible signature in JPBBNJMIGOM; fp 0.00, 0 shared; method lists align 0.96
DO_APP_FUNC(0x0156D6A0, void, MoleMole_Packet_XorEncrypt__RAW, (void* __this_unused, Byte__Array** bytes, int32_t length, MethodInfo* method));  // 1.6: M-sig (high) AAIHKALKIGE$$PMNMIALOFNJ | only compatible signature in AAIHKALKIGE; fp 0.00, 0 shared; method lists align 0.86


// Lua functions
DO_APP_FUNC(0x0397B9F0, Byte__Array*, LuaManager_LoadCustomLuaFile, (LuaManager* __this, String** filePath, bool* recycleBytes, MethodInfo* method));  // 1.6: M-name (high) MoleMole.LuaManager$$LoadCustomLuaFile
DO_APP_FUNC(0x04561390, void, Lua_xlua_pushasciistring, (void* __this_unused, void* L, String* str, MethodInfo* method));  // 1.6: M-name (high) XLua.LuaDLL.Lua$$xlua_pushasciistring  // Relic 1.6: static -> leading dummy `this` (the hook handler carries it too)
DO_APP_FUNC(0x03776F80, void, MoleMole_LuaShellManager_DoString, (void* __this, Byte__Array* byteArray, MethodInfo* method));  // 1.6: M-pos (medium) NEJMLHJLJNI$$LPBOBJHOBDB | declaration-order alignment (lists align 0.86); fp 0.00; runner-up 0.22
DO_APP_FUNC(0x04557EC0, void*, LuaEnv_DoString, (void* __this, Byte__Array* chunk, String* chunkName, void* env, MethodInfo* method));  // 1.6: M-name (high) XLua.LuaEnv$$DoString
DO_APP_FUNC(0x03776B50, void, MoleMole_LuaShellManager_ReportLuaShellResult, (void* __this, String* type, String* value, MethodInfo* method)); // Anticheat info // 1.6: M-sig (high) NEJMLHJLJNI$$IAHLDNOJGKB | only compatible signature in NEJMLHJLJNI; fp 0.37, 0 shared; method lists align 0.86


// Debug hooks
DO_APP_FUNC(0x021D97D0, AttackResult_1*, MoleMole_AttackResult_FillProtoAttackResult, (AttackResult* __this, uint32_t attackerID, uint32_t defenseId, AttackResult_1* protoAttackResult, MethodInfo* method));  // 1.6: M-sig (high) HEBLMKMEBIF$$JOPPENKKLJN | only compatible signature in HEBLMKMEBIF; fp 0.13, 1 shared; method lists align 0.92
DO_APP_FUNC(0x01C71FB0, void, MoleMole_LevelSyncCombatPlugin_SendFaceToDir, (void* __this, uint32_t runtimeID, Vector3 forward, MethodInfo* method));  // 1.6: M-sig (medium) IPCPELCOPAM$$ELOJKDANDFC | only compatible signature in IPCPELCOPAM; fp 0.60, 1 shared; method lists align 0.75
DO_APP_FUNC(0x00CFDE50, void, MoleMole_BaseEntity_FireEvent, (BaseEntity* __this, BaseEvent* e, bool immediately, MethodInfo* method));  // 1.6: M-pos (medium) DNPPAIELOMJ$$PBMOFELBKFH | declaration-order alignment (lists align 0.83); fp 0.29; runner-up 0.59
DO_APP_FUNC(0x00A707D0, bool, MoleMole_ActorAbilityPlugin_OnEvent, (void* __this, BaseEvent* e, MethodInfo* method));  // 1.6: M-name (high) AEOLLPABFCP$$OnEvent


// Kill aura
DO_APP_FUNC(0x023EEC30, void, MoleMole_EvtCrash_Init, (EvtCrash* __this, uint32_t targetID, MethodInfo* method)); // Manual offset // 1.6: M-sig (high) MFKLHADCFAO$$NHIEHNGEPPP | only compatible signature in MFKLHADCFAO; fp 0.00, 0 shared; method lists align 0.87
DO_APP_FUNC(0x01718600, void, MoleMole_EventManager_FireEvent, (MoleMole_EventManager* __this, BaseEvent* e, bool immediately, MethodInfo* method));  // 1.6: M-pos (medium) CADNPCCFBBB$$PBMOFELBKFH | declaration-order alignment (lists align 0.76); fp 0.00; runner-up 0.52
DO_APP_FUNC(0x047B6BA0, bool, MoleMole_FixedBoolStack_get_value, (FixedBoolStack* __this, MethodInfo* method));  // 1.6: M-name (high) System.Runtime.Remoting.Metadata.SoapMethodAttribute$$get_UseAttribute

// 2.8 changed to 'MoleMole_EventHelper_Allocate_144'
DO_APP_FUNC(0x0303C370, EvtCrash*, MoleMole_EventHelper_Allocate_103__RAW, (void* __this_unused, MethodInfo* method));  // 1.6: M-generic (high) EPLPMHCDMGN$$HEPNAMDNOHJ<object> (+118 instantiations sharing the body) | shared generic body of EPLPMHCDMGN.HEPNAMDNOHJ<T>
DO_APP_FUNC_METHODINFO(0x08FE8850, MoleMole_EventHelper_Allocate_103__MethodInfo);  // 1.6: slot via class map (high) Method$EPLPMHCDMGN.HEPNAMDNOHJ<MFKLHADCFAO>()

DO_APP_FUNC(0x008BF1C0, void, MoleMole_BaseMoveSyncPlugin_ConvertSyncTaskToMotionInfo, (BaseMoveSyncPlugin* __this, MethodInfo* method));  // 1.6: M-pos (medium) KCBKAOPKCIH$$NPLLFAAMFDN | declaration-order alignment (lists align 0.96); fp 0.00; runner-up 0.17


// Fishing
DO_APP_FUNC(0x0, void, MoleMole_FishingModule_RequestFishCastRod, (void* __this, uint32_t baitId, uint32_t rodId, Vector3 pos, uint32_t rodEntityId, MethodInfo* method));  // RELIC-TODO-16 class BCGKNHJGBDJ not matched in 1.6

DO_APP_FUNC(0x0, void, MoleMole_FishingModule_RequestFishBite, (void* __this, MethodInfo* method));  // RELIC-TODO-16 class BCGKNHJGBDJ not matched in 1.6
DO_APP_FUNC(0x0, void, MoleMole_FishingModule_OnFishBiteRsp, (void* __this, FishBiteRsp* rsp, MethodInfo* method));  // RELIC-TODO-16 class BCGKNHJGBDJ not matched in 1.6

DO_APP_FUNC(0x0, void, MoleMole_FishingModule_RequestFishBattleBegin, (void* __this, MethodInfo* method));  // RELIC-TODO-16 class BCGKNHJGBDJ not matched in 1.6
DO_APP_FUNC(0x0, void, MoleMole_FishingModule_OnFishBattleBeginRsp, (void* __this, FishBattleBeginRsp* rsp, MethodInfo* method));  // RELIC-TODO-16 class BCGKNHJGBDJ not matched in 1.6

DO_APP_FUNC(0x0, void, MoleMole_FishingModule_RequestFishBattleEnd, (void* __this, FishBattleResult__Enum result, bool isAlwaysBonus, float mxBonusTime, MethodInfo* method));  // RELIC-TODO-16 class BCGKNHJGBDJ not matched in 1.6
DO_APP_FUNC(0x0, void, MoleMole_FishingModule_OnFishBattleEndRsp, (void* __this, FishBattleEndRsp* rsp, MethodInfo* method));  // RELIC-TODO-16 class BCGKNHJGBDJ not matched in 1.6

DO_APP_FUNC(0x0, void, MoleMole_FishingModule_OnExitFishingRsp, (void* __this, void* rsp, MethodInfo* method));  // RELIC-TODO-16 class BCGKNHJGBDJ not matched in 1.6
DO_APP_FUNC(0x0, void, MoleMole_FishingModule_onFishChosenNotify, (void* __this, void* notify, MethodInfo* method));  // RELIC-TODO-16 class BCGKNHJGBDJ not matched in 1.6


// Visuals
DO_APP_FUNC(0x00F78710, void, MoleMole_SCameraModuleInitialize_SetWarningLocateRatio, (SCameraModuleInitialize* __this, double deltaTime, CameraShareData* data, MethodInfo* method));  // 1.6: M-fp (medium) OCGIDHALGJD$$NKIIGJJEHHC | fp 0.67 (2 shared strings/calls), runner-up 0.48
DO_APP_FUNC(0x03882230, void, MoleMole_VCBaseSetDitherValue_set_ManagerDitherAlphaValue, (MoleMole_VCBaseSetDitherValue* __this, float value, MethodInfo* method));  // 1.6: M-pos (medium) CANPDKBOPNE$$LEMFJIONBNI | declaration-order alignment (lists align 0.95); fp 0.00; runner-up 0.29

// Chest Indicator | RyujinZX#6666
DO_APP_FUNC(0x03579E90, bool, MoleMole_LCIndicatorPlugin_DoCheck, (LCIndicatorPlugin* __this, MethodInfo* method));  // 1.6: M-sig (high) KPAAFPPFEJF$$LIOECNAHDLD | only compatible signature in KPAAFPPFEJF; fp 0.36, 0 shared; method lists align 0.88
DO_APP_FUNC(0x03578900, void, MoleMole_LCIndicatorPlugin_ShowIcon, (LCIndicatorPlugin* __this, MethodInfo* method));  // 1.6: M-pos (medium) KPAAFPPFEJF$$FINBKOGEMJF | declaration-order alignment (lists align 0.88); fp 0.16; runner-up 0.30
DO_APP_FUNC(0x035791D0, void, MoleMole_LCIndicatorPlugin_HideIcon, (LCIndicatorPlugin* __this, MethodInfo* method));  // 1.6: M-pos (medium) KPAAFPPFEJF$$ICHJJJMPIHM | declaration-order alignment (lists align 0.88); fp 0.27; runner-up 0.23

// Auto Cooking | RyujinZX#6666
DO_APP_FUNC(0x00BF6670, void, MoleMole_PlayerModule_RequestPlayerCook, (MoleMole_PlayerModule* __this, uint32_t recipeId, uint32_t avatarId, uint32_t qteQuality, uint32_t count, MethodInfo* method));  // 1.6: M-sig (high) BOACBNICNDP$$IINCDADIBOM | only compatible signature in BOACBNICNDP; fp 0.00, 0 shared; method lists align 0.92
DO_APP_FUNC(0x00BFCC40, void, MoleMole_PlayerModule_OnPlayerCookRsp, (MoleMole_PlayerModule* __this, PlayerCookRsp* rsp, MethodInfo* method));  // 1.6: M-pos (medium) BOACBNICNDP$$LIJAGIMPBNF | declaration-order alignment (lists align 0.92); fp 0.21; runner-up 0.66
DO_APP_FUNC(0x01C69400, void, MoleMole_CookingQtePageContext_UpdateProficiency, (CookingQtePageContext* __this, MethodInfo* method));  // 1.6: M-pos (medium) JLOOJHNNGII$$MAAHEDHEKAH | declaration-order alignment (lists align 0.99); fp 0.11; runner-up 0.28
DO_APP_FUNC(0x022E1B20, uint32_t, MoleMole_Config_CookRecipeExcelConfig_CheckCookFoodMaxNum__RAW, (void* __this_unused, uint32_t UpdateCookRecipeDic, MethodInfo* method));  // 1.6: M-sig (high) AMGLPBKJHDC$$KODLCHPLCCB | only compatible signature in AMGLPBKJHDC; fp 0.28, 1 shared; method lists align 0.84
DO_APP_FUNC(0x01C64500, void, CookingQtePageContext_CloseItemGotPanel, (CookingQtePageContext* __this, MethodInfo* method));  // 1.6: M-pos (medium) JLOOJHNNGII$$CDGHEHGCDPJ | declaration-order alignment (lists align 0.99); fp 0.00; runner-up 0.25

// Profile Changer | RyujinZX#6666
DO_APP_FUNC(0x02D9E150, Button_1*, ProfilePage, (MonoInLevelPlayerProfilePage* __this, MethodInfo* method)); // MonoInLevelPlayerProfilePage_get_logoutButton // 1.6: M-name (high) MoleMole.MonoInLevelPlayerProfilePage$$get_logoutButton
DO_APP_FUNC(0x02FFA110, void, ProfileEditPage, (MonoFriendInformationDialog* __this, Sprite* value, MethodInfo* method)); // MonoFriendInformationDialog_set_icon // 1.6: M-name (high) MoleMole.MonoFriendInformationDialog$$set_icon

// Custom Weather | RyujinZX#6666
DO_APP_FUNC(0x028433F0, bool, EnviroSky_ChangeWeather, (void* /*app::EnviroSky*/ __this, String* weatherPath, float transTime, float ratio, MethodInfo* method));  // 1.6: M-name (high) MoleMole.EnviroSky$$ChangeWeather
// RELIC hand-added (1.6): MoleMole.EnviroSky.GetCurWeatherList (dump.cs:1941944, name unobfuscated on
// both versions) answers which weathers the CURRENT area offers, in SHORT form ("BigWorld/Weather_X").
// It reads only the active EnviroProfile, so it is a hint and not an inventory of the client - but it is
// the one enumeration a shipped build exposes, and the asset names exist nowhere in the binary (they
// live in Data/_ExcelBinOutput/WeatherExcelConfigData inside the encrypted bundles).
DO_APP_FUNC(0x0284C390, List_1_System_String_*, EnviroSky_GetCurWeatherList, (void* /*app::EnviroSky*/ __this, MethodInfo* method));  // 1.6: hand-verified MoleMole.EnviroSky$$GetCurWeatherList
// RELIC hand-added (1.6): MoleMole.EnviroSky.FireStormEffect (dump.cs:1941892) draws one lightning bolt
// on demand - born = pos + Vector3.up * height (get_up @0x05382E40, op_Multiply @0x053831B0,
// op_Addition @0x05382F20), then EENGMANLKGL @0x02847350 spawns the applied preset's lightning /
// lightning-cloud / lightning-impact prefabs off EnviroSky.levelEntity. It needs no server, no gadget
// and no entity - which is the point, because GIO never spawns the Storm_Lightning gadget the upstream
// feature waits for. It also creates no entity and deals no damage: the bolt is visual.
DO_APP_FUNC(0x028496A0, void, EnviroSky_FireStormEffect, (void* /*app::EnviroSky*/ __this, Vector3 pos, float height, MethodInfo* method));  // 1.6: hand-verified MoleMole.EnviroSky$$FireStormEffect
// RELIC hand-added (1.6): MoleMole.AttackResult.CreateElementAttack (dump.cs:1322727,
// HEBLMKMEBIF$$FMFJMOFFGGO(PNLBEJDMOBA, float)). Read out of the body at 0x021D77D0: allocate from the
// object pool -> Reset() @0x021D67C0 -> 0x021D6370 `mov [this+0x118], ebx` (_origElementType) ->
// 0x021D6230 `movss [this+0x11C], xmm6` (_origElementDurability). It leaves _attackerAttackProperty
// (+0x108) and modifiedAttackProperty (+0x110) NULL, which is exactly what makes get_ElementType
// @0x021D74E0 fall through to _origElementType - so the element rides on the attack itself and no
// SHARED ConfigAttackProperty is written (that is the bug at RapidFire.cpp:384).
// STATIC, so 1.6's dummy-`this` ABI applies. The game's own call site pins the registers - the Cryo
// weather mixin at 0x02C302DC does: movss xmm2,[rip] (80.0f) / xor r9d,r9d / xor ecx,ecx /
// lea edx,[r9+5] (Ice) / call 0x021D77D0.
DO_APP_FUNC(0x021D77D0, AttackResult*, MoleMole_AttackResult_CreateElementAttack__RAW, (void* __this_unused, ElementType__Enum elementType, float elementDurability, MethodInfo* method));  // 1.6: hand-verified HEBLMKMEBIF$$FMFJMOFFGGO(PNLBEJDMOBA, float)
DO_APP_FUNC(0x0285CC30, void* /*app::EnviroSky*/, EnviroSky_get_Instance__RAW, (void* __this_unused, MethodInfo* method));  // 1.6: M-name (high) MoleMole.EnviroSky$$get_Instance
 

// Free Camera
DO_APP_FUNC(0x053EBD70, float, Camera_get_fieldOfView, (Camera* __this, MethodInfo* method));  // 1.6: M-name (high) UnityEngine.Camera$$get_fieldOfView
DO_APP_FUNC(0x053ECF00, void, Camera_set_fieldOfView, (Camera* __this, float value, MethodInfo* method));  // 1.6: M-name (high) UnityEngine.Camera$$set_fieldOfView
DO_APP_FUNC(0x053E9C50, void, Camera_CopyFrom, (Camera* __this, Camera* other, MethodInfo* method));  // 1.6: M-name (high) UnityEngine.Camera$$CopyFrom

// Game Object, Component, Transform Utility
DO_APP_FUNC(0x053F52D0, GameObject*, GameObject_Find__RAW, (void* __this_unused, String* name, MethodInfo* method));  // 1.6: M-name (high) UnityEngine.GameObject$$Find
DO_APP_FUNC(0x053F55A0, Component_1*, GameObject_GetComponentByName, (GameObject* __this, String* type, MethodInfo* method));  // 1.6: M-name (high) UnityEngine.GameObject$$GetComponentByName
DO_APP_FUNC(0x053F63A0, bool, GameObject_get_active, (GameObject* __this, MethodInfo* method));  // 1.6: M-name (high) UnityEngine.GameObject$$get_active
DO_APP_FUNC(0x053F66D0, void, GameObject_set_active, (GameObject* __this, bool value, MethodInfo* method));  // 1.6: M-name (high) UnityEngine.GameObject$$set_active
DO_APP_FUNC(0x053F5F20, void, GameObject_SetActive, (GameObject* __this, bool value, MethodInfo* method));  // 1.6: M-name (high) UnityEngine.GameObject$$SetActive
DO_APP_FUNC(0x05378C80, Transform*, Transform_GetChild, (Transform* __this, int32_t index, MethodInfo* method));  // 1.6: M-name (high) UnityEngine.Transform$$GetChild
DO_APP_FUNC(0x053F0330, Component_1*, Component_1_GetComponent_1, (Component_1* __this, String* type, MethodInfo* method));  // 1.6: M-name (high) UnityEngine.Component$$GetComponent
DO_APP_FUNC(0x053F51E0, GameObject*, GameObject_CreatePrimitive__RAW, (void* __this_unused, PrimitiveType__Enum type, MethodInfo* method));  // 1.6: M-name (high) UnityEngine.GameObject$$CreatePrimitive
DO_APP_FUNC(0x053F6680, Transform*, GameObject_get_transform, (GameObject* __this, MethodInfo* method));  // 1.6: M-name (high) UnityEngine.GameObject$$get_transform
DO_APP_FUNC(0x0537BAA0, Quaternion, Transform_get_localRotation, (Transform* __this, MethodInfo* method));  // 1.6: M-name (high) UnityEngine.Transform$$get_localRotation
DO_APP_FUNC(0x053796D0, void, Transform_set_localRotation, (Transform* __this, Quaternion value, MethodInfo* method));  // 1.6: M-name (high) UnityEngine.Transform$$set_localRotation
DO_APP_FUNC(0x0537BB20, Vector3, Transform_get_localScale, (Transform* __this, MethodInfo* method));  // 1.6: M-name (high) UnityEngine.Transform$$get_localScale
DO_APP_FUNC(0x0537C680, void, Transform_set_localScale, (Transform* __this, Vector3 value, MethodInfo* method));  // 1.6: M-name (high) UnityEngine.Transform$$set_localScale
DO_APP_FUNC(0x0537BA20, Vector3, Transform_get_localPosition, (Transform* __this, MethodInfo* method));  // 1.6: M-name (high) UnityEngine.Transform$$get_localPosition
DO_APP_FUNC(0x0537C620, void, Transform_set_localPosition, (Transform* __this, Vector3 value, MethodInfo* method));  // 1.6: M-name (high) UnityEngine.Transform$$set_localPosition
DO_APP_FUNC(0x053F4FE0, Component_1*, GameObject_AddComponentInternal, (GameObject* __this, String* className, MethodInfo* method));  // 1.6: M-name (high) UnityEngine.GameObject$$AddComponentInternal
DO_APP_FUNC(0x053F5A80, Component_1*, GameObject_AddComponent, (GameObject* __this, Type* componentType, MethodInfo* method));  // 1.6: M-name (high) UnityEngine.GameObject$$AddComponent
DO_APP_FUNC(0x052C24F0, void, Object_1_DestroyImmediate_1__RAW, (void* __this_unused, Object_1* obj, MethodInfo* method));  // 1.6: M-name (high) UnityEngine.Object$$DestroyImmediate
DO_APP_FUNC(0x052C3480, Object_1*, Object_1_Instantiate_2__RAW, (void* __this_unused, Object_1* original, MethodInfo* method));  // 1.6: M-name (high) UnityEngine.Object$$Instantiate
DO_APP_FUNC(0x03BB8AD0, Object*, Object_1_Instantiate_5__RAW, (void* __this_unused, Object* original, MethodInfo* method));  // 1.6: M-generic (high) UnityEngine.Object$$Instantiate<object> (+10 instantiations sharing the body) | shared generic body of UnityEngine.Object.Instantiate<T>
DO_APP_FUNC(0x03BB8AD0, GameObject*, Object_1_Instantiate_10__RAW, (void* __this_unused, GameObject* original, MethodInfo* method));  // 1.6: M-generic (high) UnityEngine.Object$$Instantiate<object> (+10 instantiations sharing the body) | shared generic body of UnityEngine.Object.Instantiate<T>
DO_APP_FUNC(0x0537B600, int32_t, Transform_get_childCount, (Transform* __this, MethodInfo* method));  // 1.6: M-name (high) UnityEngine.Transform$$get_childCount
DO_APP_FUNC(0x053F08F0, GameObject*, Component_1_get_gameObject, (Component_1* __this, MethodInfo* method));  // 1.6: M-name (high) UnityEngine.Component$$get_gameObject
DO_APP_FUNC(0x052C3E10, String*, Object_1_get_name, (Object_1* __this, MethodInfo* method));  // 1.6: M-name (high) UnityEngine.Object$$get_name
DO_APP_FUNC(0x0536B740, Material__Array*, Renderer_GetMaterialArray, (Renderer* __this, MethodInfo* method));  // 1.6: M-name (high) UnityEngine.Renderer$$GetMaterialArray
DO_APP_FUNC(0x052B8090, void, Material_set_mainTexture, (Material* __this, Texture* value, MethodInfo* method));  // 1.6: M-name (high) UnityEngine.Material$$set_mainTexture
DO_APP_FUNC(0x05380630, Vector3, Vector3_Lerp__RAW, (void* __this_unused, Vector3 a, Vector3 b, float t, MethodInfo* method));  // 1.6: M-name (high) UnityEngine.Vector3$$Lerp
DO_APP_FUNC(0x0537B650, Vector3, Transform_get_eulerAngles, (Transform* __this, MethodInfo* method));  // 1.6: M-name (high) UnityEngine.Transform$$get_eulerAngles
DO_APP_FUNC(0x0537C2C0, void, Transform_set_eulerAngles, (Transform* __this, Vector3 value, MethodInfo* method));  // 1.6: M-name (high) UnityEngine.Transform$$set_eulerAngles
DO_APP_FUNC(0x0537BDA0, Vector3, Transform_get_right, (Transform* __this, MethodInfo* method));  // 1.6: M-name (high) UnityEngine.Transform$$get_right
DO_APP_FUNC(0x0537C870, void, Transform_set_right, (Transform* __this, Vector3 value, MethodInfo* method));  // 1.6: M-name (high) UnityEngine.Transform$$set_right
DO_APP_FUNC(0x0537C040, Vector3, Transform_get_up, (Transform* __this, MethodInfo* method));  // 1.6: M-name (high) UnityEngine.Transform$$get_up
DO_APP_FUNC(0x0537CA50, void, Transform_set_up, (Transform* __this, Vector3 value, MethodInfo* method));  // 1.6: M-name (high) UnityEngine.Transform$$set_up
DO_APP_FUNC(0x0537B700, Vector3, Transform_get_forward, (Transform* __this, MethodInfo* method));  // 1.6: M-name (high) UnityEngine.Transform$$get_forward
DO_APP_FUNC(0x0537C3A0, void, Transform_set_forward, (Transform* __this, Vector3 value, MethodInfo* method));  // 1.6: M-name (high) UnityEngine.Transform$$set_forward
DO_APP_FUNC(0x0537C9F0, void, Transform_set_rotation, (Transform* __this, Quaternion value, MethodInfo* method));  // 1.6: M-name (high) UnityEngine.Transform$$set_rotation
DO_APP_FUNC(0x052B8BB0, float, Mathf_Lerp__RAW, (void* __this_unused, float a, float b, float t, MethodInfo* method));  // 1.6: M-name (high) UnityEngine.Mathf$$Lerp
DO_APP_FUNC(0x052B1800, float, Input_GetAxis__RAW, (void* __this_unused, String* axisName, MethodInfo* method));  // 1.6: M-name (high) UnityEngine.Input$$GetAxis
DO_APP_FUNC(0x052C26D0, void, Object_1_Destroy_1__RAW, (void* __this_unused, Object_1* obj, MethodInfo* method));  // 1.6: M-name (high) UnityEngine.Object$$Destroy


// Utility
DO_APP_FUNC(0x04745BA0, String*, Text_get_text, (Text* __this, MethodInfo* method));  // 1.6: M-name (high) UnityEngine.UI.Text$$get_text
DO_APP_FUNC(0x05EC1490, void, Text_set_text, (Text* __this, String* value, MethodInfo* method));  // 1.6: M-name (high) UnityEngine.UI.Text$$set_text
DO_APP_FUNC(0x05EBB970, void, Slider_1_set_minValue, (Slider_1* __this, float value, MethodInfo* method));  // 1.6: M-name (high) UnityEngine.UI.Slider$$set_minValue
DO_APP_FUNC(0x05EBB8C0, void, Slider_1_set_maxValue, (Slider_1* __this, float value, MethodInfo* method));  // 1.6: M-name (high) UnityEngine.UI.Slider$$set_maxValue
DO_APP_FUNC(0x05EBBAD0, void, Slider_1_set_value, (Slider_1* __this, float value, MethodInfo* method));  // 1.6: M-name (high) UnityEngine.UI.Slider$$set_value
DO_APP_FUNC(0x05373430, Rect, Sprite_get_rect, (Sprite* __this, MethodInfo* method));  // 1.6: M-name (high) UnityEngine.Sprite$$get_rect
DO_APP_FUNC(0x05F73390, Texture2D*, NativeGallery_LoadImageAtPath__RAW, (void* __this_unused, String* imagePath, int32_t maxSize, bool markTextureNonReadable, bool generateMipmaps, bool linearColorSpace, MethodInfo* method));  // 1.6: M-name (high) NativeGallery$$LoadImageAtPath
DO_APP_FUNC(0x05372E70, Sprite*, Sprite_Create, (Texture2D* texture, Rect rect, Vector2 pivot, float pixelsPerUnit, MethodInfo* method));  // 1.6: M-name-arity (low) UnityEngine.Sprite$$Create | ARITY: 1.6 has 3 parameter(s) vs 4 in 2.8 (static Sprite Create(Texture2D texture, Rect rect, Vector2 pivot)); trailing arguments are ignored by the x64 ABI
DO_APP_FUNC(0x05EC0DA0, void, Text_set_alignment, (Text* __this, TextAnchor__Enum value, MethodInfo* method));  // 1.6: M-name (high) UnityEngine.UI.Text$$set_alignment
DO_APP_FUNC(0x05EC1190, void, Text_set_horizontalOverflow, (Text* __this, HorizontalWrapMode__Enum value, MethodInfo* method));  // 1.6: M-name (high) UnityEngine.UI.Text$$set_horizontalOverflow
DO_APP_FUNC(0x05EC15D0, void, Text_set_verticalOverflow, (Text* __this, VerticalWrapMode__Enum value, MethodInfo* method));  // 1.6: M-name (high) UnityEngine.UI.Text$$set_verticalOverflow
DO_APP_FUNC(0x05EC0C40, bool, Text_get_resizeTextForBestFit, (Text* __this, MethodInfo* method));  // 1.6: M-name (high) UnityEngine.UI.Text$$get_resizeTextForBestFit
DO_APP_FUNC(0x05EC1290, void, Text_set_resizeTextForBestFit, (Text* __this, bool value, MethodInfo* method));  // 1.6: M-name (high) UnityEngine.UI.Text$$set_resizeTextForBestFit
DO_APP_FUNC(0x05EC0340, int32_t, Text_get_fontSize, (Text* __this, MethodInfo* method));  // 1.6: M-name (high) UnityEngine.UI.Text$$get_fontSize
DO_APP_FUNC(0x05EC0F90, void, Text_set_fontSize, (Text* __this, int32_t value, MethodInfo* method));  // 1.6: M-name (high) UnityEngine.UI.Text$$set_fontSize

DO_APP_FUNC(0x00FF21E0, float, Miscs_CalcCurrentGroundWaterHeight__RAW, (void* __this_unused, float x, float z, MethodInfo* method));  // 1.6: M-name (high) MoleMole.Miscs$$CalcCurrentGroundWaterHeight
DO_APP_FUNC(0x00FF1B80, float, Miscs_CalcCurrentGroundHeight__RAW, (void* __this_unused, float x, float z, MethodInfo* method));  // 1.6: M-name (high) MoleMole.Miscs$$CalcCurrentGroundHeight
DO_APP_FUNC(0x00FF1900, float, Miscs_CalcCurrentGroundHeight_1__RAW, (void* __this_unused, float x, float z, float rayStartHeight, float rayDetectLength, int32_t layer, MethodInfo* method));  // 1.6: M-name (high) MoleMole.Miscs$$CalcCurrentGroundHeight
DO_APP_FUNC(0x00FF1CB0, Vector3, Miscs_CalcCurrentGroundNorm__RAW, (void* __this_unused, Vector3 pos, MethodInfo* method));  // 1.6: M-name (high) MoleMole.Miscs$$CalcCurrentGroundNorm
DO_APP_FUNC(0x00FFB930, Vector3, Miscs_GenWorldPos__RAW, (void* __this_unused, Vector2 levelMapPos, MethodInfo* method));  // 1.6: M-name (high) MoleMole.Miscs$$GenWorldPos
DO_APP_FUNC(0x00FFB3A0, Vector2, Miscs_GenLevelPos_1__RAW, (void* __this_unused, Vector3 worldPos, MethodInfo* method));  // 1.6: M-name (high) MoleMole.Miscs$$GenLevelPos
DO_APP_FUNC(0x01014040, int32_t, Miscs_GetSceneGroundLayerMask__RAW, (void* __this_unused, MethodInfo* method));  // 1.6: M-name (high) MoleMole.Miscs$$GetSceneGroundLayerMask

DO_APP_FUNC(0x042DA090, Vector3, WorldShiftManager_GetAbsolutePosition__RAW, (void* __this_unused, Vector3 pos, MethodInfo* method));  // 1.6: M-name (high) MoleMole.WorldShiftManager$$GetAbsolutePosition
DO_APP_FUNC(0x042DA330, Vector3, WorldShiftManager_GetRelativePosition__RAW, (void* __this_unused, Vector3 pos, MethodInfo* method));  // 1.6: M-name (high) MoleMole.WorldShiftManager$$GetRelativePosition

DO_APP_FUNC(0x00DBA230, Vector3, ActorUtils_GetAvatarPos__RAW, (void* __this_unused, MethodInfo* method));  // 1.6: M-name (high) MoleMole.ActorUtils$$GetAvatarPos
DO_APP_FUNC(0x00DBE630, void, ActorUtils_SetAvatarPos__RAW, (void* __this_unused, Vector3 pos, MethodInfo* method));  // 1.6: M-name (high) MoleMole.ActorUtils$$SetAvatarPos
DO_APP_FUNC(0x00DC0350, void, ActorUtils_SyncAvatarMotion__RAW, (void* __this_unused, int32_t state, MethodInfo* method));  // 1.6: M-name (high) MoleMole.ActorUtils$$SyncAvatarMotion

DO_APP_FUNC(0x02471690, Notify, Notify_CreateNotify_1__RAW, (void* __this_unused, MoleMole_NotifyTypes__Enum type, Object* body, MethodInfo* method));  // 1.6: M-pos (medium) MoleMole.Notify$$CreateNotify | declaration-order alignment (lists align 1.00); fp 0.83; runner-up 1.24

// should be 'op_Implicit' not 'get_value'
DO_APP_FUNC(0x0234F470, float, MoleMole_SafeFloat_get_Value__RAW, (void* __this_unused, SafeFloat safeFloat, MethodInfo* method));  // 1.6: M-sig (high) JLPLKELMPJG$$GJADJEFIFBE | only compatible signature in JLPLKELMPJG; fp 0.00, 0 shared; method lists align 0.91
// should be 'op_Implicit' not 'set_value'
DO_APP_FUNC(0x0234F370, SafeFloat, MoleMole_SafeFloat_set_Value__RAW, (void* __this_unused, float value, MethodInfo* method));  // 1.6: M-sig (high) JLPLKELMPJG$$GJADJEFIFBE | only compatible signature in JLPLKELMPJG; fp 0.00, 0 shared; method lists align 0.91

DO_APP_FUNC(0x03039CC0, LCBaseCombat*, MoleMole_BaseEntity_GetLogicCombatComponent_1, (BaseEntity* __this, MethodInfo* method));  // 1.6: M-generic (high) DNPPAIELOMJ$$BHEBECBAPHE<object> (+7 instantiations sharing the body) | shared generic body of DNPPAIELOMJ.BHEBECBAPHE<T>
DO_APP_FUNC_METHODINFO(0x08F6CC20, MoleMole_BaseEntity_GetLogicCombatComponent_1__MethodInfo);  // 1.6: slot via class map (high) Method$DNPPAIELOMJ.BHEBECBAPHE<PMBPGLIKLGN>()

DO_APP_FUNC(0x00CDD390, String*, MoleMole_BaseEntity_ToStringRelease, (BaseEntity* __this, MethodInfo* method));  // 1.6: M-fp (high) DNPPAIELOMJ$$EAMDEDMEOAO | fp 0.67 (7 shared strings/calls), runner-up 0.36

DO_APP_FUNC(0x00CEC7E0, void, MoleMole_BaseEntity_SetRelativePosition, (BaseEntity* __this, Vector3 position, bool forceSyncToRigidbody, MethodInfo* method));  // 1.6: M-pos (medium) DNPPAIELOMJ$$JNHEHLKIDML | declaration-order alignment (lists align 0.83); fp 0.46; runner-up 0.70
DO_APP_FUNC(0x00CF4100, void, MoleMole_BaseEntity_SetAbsolutePosition, (BaseEntity* __this, Vector3 abpos, bool forceSyncToRigidbody, MethodInfo* method));  // 1.6: M-pos (medium) DNPPAIELOMJ$$MFAHEAGFLMO | declaration-order alignment (lists align 0.83); fp 0.46; runner-up 0.54
DO_APP_FUNC(0x00CFEBA0, Vector3, MoleMole_BaseEntity_GetAbsolutePosition, (BaseEntity* __this, MethodInfo* method));  // 1.6: M-fp (medium) DNPPAIELOMJ$$PGJGLBHONMM | fp 0.56 (2 shared strings/calls), runner-up 0.86
DO_APP_FUNC(0x00CD9930, Vector3, MoleMole_BaseEntity_GetRelativePosition, (BaseEntity* __this, MethodInfo* method));  // 1.6: M-fp (medium) DNPPAIELOMJ$$CJIANEJJCPH | fp 0.56 (2 shared strings/calls), runner-up 0.65
DO_APP_FUNC(0x00CD4E70, Vector3, MoleMole_BaseEntity_GetForward, (BaseEntity* __this, MethodInfo* method));  // 1.6: M-fp (medium) DNPPAIELOMJ$$AEPFJDAHICM | fp 0.44 (2 shared strings/calls), runner-up 0.75
DO_APP_FUNC(0x00CF8F40, Vector3, MoleMole_BaseEntity_GetForwardFast, (BaseEntity* __this, MethodInfo* method));  // 1.6: M-pos (medium) DNPPAIELOMJ$$NHEGLBDHJIN | declaration-order alignment (lists align 0.83); fp 0.00; runner-up 0.64
DO_APP_FUNC(0x00CE93F0, Vector3, MoleMole_BaseEntity_GetRight, (BaseEntity* __this, MethodInfo* method));  // 1.6: M-fp (medium) DNPPAIELOMJ$$JABMFKDBNLH | fp 0.44 (2 shared strings/calls), runner-up 0.76
DO_APP_FUNC(0x00CD8110, Vector3, MoleMole_BaseEntity_GetUp, (BaseEntity* __this, MethodInfo* method));  // 1.6: M-fp (medium) DNPPAIELOMJ$$BLMDAFLAEOC | fp 0.44 (2 shared strings/calls), runner-up 0.61
DO_APP_FUNC(0x00CDDD50, bool, MoleMole_BaseEntity_IsActive, (BaseEntity* __this, MethodInfo* method));  // 1.6: M-pos (medium) DNPPAIELOMJ$$EDIIJFCFLGO | declaration-order alignment (lists align 0.83); fp 0.00; runner-up 0.20
DO_APP_FUNC(0x00CDD760, Rigidbody*, MoleMole_BaseEntity_GetRigidbody, (BaseEntity* __this, MethodInfo* method));  // 1.6: M-pos (medium) DNPPAIELOMJ$$EBGNPLOOGGL | declaration-order alignment (lists align 0.83); fp 0.00; runner-up 0.51
DO_APP_FUNC(0x00CE5B80, Animator*, MoleMole_BaseEntity_get_animator, (BaseEntity* __this, MethodInfo* method));  // 1.6: M-pos (medium) DNPPAIELOMJ$$GPBIDLOLLEF | declaration-order alignment (lists align 0.83); fp 0.00; runner-up 0.37

// type should be 'MoleMole_VCCharacterCombat' not 'MoleMole_VCBaseMove'
// function name should be 'GetVisualCombatComponent' not 'GetMoveComponent'
DO_APP_FUNC(0x03039A50, VCBaseMove*, MoleMole_BaseEntity_GetMoveComponent_1, (BaseEntity* __this, MethodInfo* method));  // 1.6: M-generic (high) DNPPAIELOMJ$$AOHJGHCLKKC<object> (+4 instantiations sharing the body) | shared generic body of DNPPAIELOMJ.AOHJGHCLKKC<T>
DO_APP_FUNC_METHODINFO(0x09064948, MoleMole_BaseEntity_GetMoveComponent_1__MethodInfo);  // 1.6: slot via class map (high) Method$DNPPAIELOMJ.AOHJGHCLKKC<INAJPJPEPNO>()

DO_APP_FUNC(0x00CF0090, List_1_MoleMole_BaseComponent_*, MoleMole_BaseEntity_GetAllLogicComponents, (BaseEntity* __this, MethodInfo* method));  // 1.6: M-pos (medium) DNPPAIELOMJ$$LFCDLDPAMKO | declaration-order alignment (lists align 0.83); fp 0.67; runner-up 0.95
DO_APP_FUNC(0x00B203E0, GameObject*, MoleMole_BaseEntity_get_gameObject, (BaseEntity* __this, MethodInfo* method));  // 1.6: M-pos (medium) DNPPAIELOMJ$$BBHNLKFJICK | declaration-order alignment (lists align 0.83); fp 0.00; runner-up 0.31
DO_APP_FUNC(0x00916760, GameObject*, MoleMole_BaseEntity_get_rootGameObject, (BaseEntity* __this, MethodInfo* method));  // 1.6: M-pos (medium) DNPPAIELOMJ$$PJFALIKMCJC | declaration-order alignment (lists align 0.83); fp 0.00; runner-up 0.11

// type should be 'MoleMole_AvatarEntity' not 'MoleMole_BaseEntity'
DO_APP_FUNC(0x02020FA0, BaseEntity*, MoleMole_EntityManager_GetLocalAvatarEntity, (MoleMole_EntityManager* __this, MethodInfo* method));  // 1.6: M-pos (medium) GIHJJEIOMJL$$IECOBEJEGIG | declaration-order alignment (lists align 0.90); fp 0.00; runner-up 0.55

DO_APP_FUNC(0x02022A20, CameraEntity*, MoleMole_EntityManager_GetMainCameraEntity, (MoleMole_EntityManager* __this, MethodInfo* method));  // 1.6: M-pos (medium) GIHJJEIOMJL$$JCHJKMCJFHM | declaration-order alignment (lists align 0.90); fp 0.00; runner-up 0.61
DO_APP_FUNC(0x02029300, BaseEntity*, MoleMole_EntityManager_GetValidEntity, (MoleMole_EntityManager* __this, uint32_t runtimeID, MethodInfo* method));  // 1.6: M-pos (medium) GIHJJEIOMJL$$MIJGCDGOLAI | declaration-order alignment (lists align 0.90); fp 0.00; runner-up 0.60
// should be: DO_APP_FUNC(0x02F5F490, void, MoleMole_EntityManager_RemoveEntity, (MoleMole_EntityManager * __this, bool entity, MethodInfo * method));
DO_APP_FUNC(0x02021060, bool, MoleMole_EntityManager_RemoveEntity, (MoleMole_EntityManager* __this, BaseEntity* entity, uint32_t specifiedRuntimeID, MethodInfo* method));  // 1.6: M-fp (medium) GIHJJEIOMJL$$IGAPFLEHPHK | fp 0.20 (2 shared strings/calls), runner-up 0.18
DO_APP_FUNC(0x0201FAF0, bool, MoleMole_EntityManager_IsCachedEntity, (MoleMole_EntityManager* __this, BaseEntity* entity, MethodInfo* method));  // 1.6: M-pos (medium) GIHJJEIOMJL$$HNDBIJDAPLE | declaration-order alignment (lists align 0.90); fp 0.30; runner-up 0.62
DO_APP_FUNC(0x0202D730, List_1_MoleMole_BaseEntity_*, MoleMole_EntityManager_GetEntities, (MoleMole_EntityManager* __this, MethodInfo* method));  // 1.6: M-pos (medium) GIHJJEIOMJL$$POFIMMDGLFE | declaration-order alignment (lists align 0.90); fp 0.00; runner-up 0.32
DO_APP_FUNC(0x0668FC80, Bounds, Utils_4_GetBounds__RAW, (void* __this_unused, GameObject* go, MethodInfo* method));  // 1.6: M-name (high) Gaia.Utils$$GetBounds

// Modify | RyujinZX#6666
DO_APP_FUNC(0x015B4090, void, MoleMole_HumanoidMoveFSM_LateTick, (HumanoidMoveFSM* __this, float deltaTime, MethodInfo* method));  // 1.6: M-name (high) NCPJNIIMLOG$$LateTick

DO_APP_FUNC(0x02B99550, bool, MoleMole_ScenePropManager_GetTreeTypeByPattern, (MoleMole_ScenePropManager* __this, String* pattern, MoleMole_Config_TreeType__Enum* treeType, MethodInfo* method));  // 1.6: M-sig (high) IGNFJKIBHOO$$DBNECNKMKOG | only compatible signature in IGNFJKIBHOO; fp 0.23, 0 shared; method lists align 0.91
DO_APP_FUNC(0x00F4AEB0, void, MoleMole_NetworkManager_RequestHitTreeDropNotify, (MoleMole_NetworkManager* __this, Vector3 position, Vector3 hitPostion, MoleMole_Config_TreeType__Enum treeType, MethodInfo* method));  // 1.6: M-sig (high) OMKJLMHHNEL$$COBCJNCFGID | only compatible signature in OMKJLMHHNEL; fp 0.00, 0 shared; method lists align 0.88
// function should be 'MoleMole_TimeUtil_get_LocalNowMsTimeStamp'
DO_APP_FUNC(0x0297D6E0, uint64_t, MoleMole_TimeUtil_get_NowTimeStamp__RAW, (void* __this_unused, MethodInfo* method));  // 1.6: M-family (low) DBOIMGBJPNK$$AEJFMHGGPID | equivalent family: ['AEJFMHGGPID', 'EBJDHHJIPIA'] are identical bodies (masked code similarity >= 0.98); the best-scored one taken

DO_APP_FUNC(0x01218E90, bool, MoleMole_LoadingManager_IsLoaded, (MoleMole_LoadingManager* __this, MethodInfo* method));  // 1.6: M-pos (medium) FFHBJKFKMOC$$BMIGCKKEJHD | declaration-order alignment (lists align 0.96); fp 0.00; runner-up 0.20

// Thanks to | RyujinZX
DO_APP_FUNC(0x018328C0, void, MoleMole_LCAbilityElement_ReduceModifierDurability, (LCAbilityElement* __this, int32_t modifierDurabilityIndex, float reduceDurability, Nullable_1_Single_ deltaTime, MethodInfo* method));  // 1.6: M-sig (medium) DHODOOJCGNL$$IDFOAMHLPLM | only compatible signature in DHODOOJCGNL; fp 0.00, 0 shared; method lists align 0.51

DO_APP_FUNC(0x02560B60, BaseEntity*, MoleMole_GadgetEntity_GetOwnerEntity, (GadgetEntity* __this, MethodInfo* method));  // 1.6: M-pos (medium) DMGNJHMMPDF$$MKJEMCGBANA | declaration-order alignment (lists align 0.84); fp 0.29; runner-up 0.80

DO_APP_FUNC(0x00B0CDA0, void, MoleMole_InLevelMapPageContext_ZoomMap, (InLevelMapPageContext* __this, float value, MethodInfo* method));  // 1.6: M-fp (medium) BPDBBEDHBCP$$MKDOMMNBHJJ | fp 0.22 (2 shared strings/calls), runner-up 0.25
DO_APP_FUNC(0x00B120F0, void, MoleMole_InLevelMapPageContext_UpdateView, (InLevelMapPageContext* __this, MethodInfo* method));  // 16: OVERRIDE BPDBBEDHBCP$$ODHLJNAONMH, 1.6 dump.cs:1812713 (public void, instance). 1.6 has NO UpdateView override: BaseContext's slot 26 is an empty hotfix stub, so the symbol is repurposed for the method that runs right after the view rect is written. FEIBBKAODPE @0xAEF790 is the only non-ctor writer of InLevelMapPageContext._mapViewRect @0x1D0 (it is MonoExUICamera.onViewChange, registered by BABICAFOOCO @0xAD99A0) and calls ADPLIDADADC then ODHLJNAONMH on every normal path after the write; ODHLJNAONMH has exactly one caller and no delegate reference. The hook (InteractiveMap.cpp, copies __this->fields._mapViewRect after CALL_ORIGIN) needs no change. Fallback of the same shape: ADPLIDADADC @0x00AD44B0. Note: the delegate is not invoked while MonoExUICamera.allowCameraAnimation (+0x170) is set, so the rect does not refresh during camera animations. 2.8 twin ELBPCIGIBIH$$EMBMMLLJHOM 0x034D6410.

DO_APP_FUNC(0x00D2F2F0, bool, MoleMole_UIManager_HasEnableMapCamera, (MoleMole_UIManager* __this, MethodInfo* method));  // 1.6: M-fp (medium) CCMGKAJLOGF$$IJFMILKLEBM | fp 0.46 (3 shared strings/calls), runner-up 0.67

DO_APP_FUNC(0x02720640, void, MonoMiniMap_Update, (MonoMiniMap* __this, MethodInfo* method));  // 1.6: M-name (high) MoleMole.MonoMiniMap$$Update
DO_APP_FUNC(0x02D951C0, MonoMiniMap*, MonoInLevelMainPage_get_miniMap, (void* __this, MethodInfo* method));  // 1.6: M-name (high) MoleMole.MonoInLevelMainPage$$get_miniMap
DO_APP_FUNC(0x014AFFA0, void, MoleMole_GadgetModule_OnGadgetInteractRsp, (void* __this, GadgetInteractRsp* notify, MethodInfo* method));  // 1.6: M-fp+param (medium) ILECJOHHNEI$$BEANFDHPKEI | joint decision: parameter type EANGNDCHMCL -> GJIMINOINGL (class score 0.45) + method fp 0.43; runner-up 0.73
DO_APP_FUNC(0x008FC2B0, float, MoleMole_InLevelMainPageContext_get_miniMapScale, (InLevelMainPageContext* __this, MethodInfo* method));  // 16: OVERRIDE KCFCJJBPLEN$$MKLHNEKDNCJ, 1.6 dump.cs:1808326 (public float, instance): IFix gate then movss xmm0,[rcx+0x4B8] - the only float() reader of _miniMapScale in the class, and the class is right (MonoMiniMap.context is typed KCFCJJBPLEN in the 1.6 dump; 'IGKEDHHIDMA' does not exist there). Every other access to 0x4B8 pairs with the 2.8 accesses to 0x500. 2.8 twin MFJCGBPOEHH$$DJGODNNFIJE 0x009E9F50.


// UnityEngine
DO_APP_FUNC(0x05367560, void, RenderSettings_set_fog__RAW, (void* __this_unused, bool value, MethodInfo* method));  // 1.6: M-name (high) UnityEngine.RenderSettings$$set_fog
DO_APP_FUNC(0x053E49D0, int32_t, Application_get_targetFrameRate__RAW, (void* __this_unused, MethodInfo* method));  // 1.6: M-name (high) UnityEngine.Application$$get_targetFrameRate
DO_APP_FUNC(0x053E4E30, void, Application_set_targetFrameRate__RAW, (void* __this_unused, int32_t value, MethodInfo* method));  // 1.6: M-name (high) UnityEngine.Application$$set_targetFrameRate

DO_APP_FUNC(0x05F6F420, bool, RectTransformUtility_ScreenPointToLocalPointInRectangle__RAW, (void* __this_unused, void* rect, Vector2 screenPoint, void* cam, Vector2* localPoint, MethodInfo* method));  // 1.6: M-name (high) UnityEngine.RectTransformUtility$$ScreenPointToLocalPointInRectangle

DO_APP_FUNC(0x0537BD20, Vector3, Transform_get_position, (Transform* __this, MethodInfo* method));  // 1.6: M-name (high) UnityEngine.Transform$$get_position
DO_APP_FUNC(0x0537C810, void, Transform_set_position, (Transform* __this, Vector3 value, MethodInfo* method));  // 1.6: M-name (high) UnityEngine.Transform$$set_position
DO_APP_FUNC(0x0537FE50, float, Vector3_Distance__RAW, (void* __this_unused, Vector3 a, Vector3 b, MethodInfo* method));  // 1.6: M-name (high) UnityEngine.Vector3$$Distance
DO_APP_FUNC(0x0537DA10, float, Vector2_Distance__RAW, (void* __this_unused, Vector2 a, Vector2 b, MethodInfo* method));  // 1.6: M-name (high) UnityEngine.Vector2$$Distance

DO_APP_FUNC(0x053F2D80, void, Cursor_set_visible__RAW, (void* __this_unused, bool value, MethodInfo* method));  // 1.6: M-name (high) UnityEngine.Cursor$$set_visible
DO_APP_FUNC(0x053F2D30, void, Cursor_set_lockState__RAW, (void* __this_unused, CursorLockMode__Enum value, MethodInfo* method));  // 1.6: M-name (high) UnityEngine.Cursor$$set_lockState
DO_APP_FUNC(0x053F2CE0, bool, Cursor_get_visible__RAW, (void* __this_unused, MethodInfo* method));  // 1.6: M-name (high) UnityEngine.Cursor$$get_visible

DO_APP_FUNC(0x0, RigidbodyConstraints__Enum, Rigidbody_get_constraints, (Rigidbody* __this, MethodInfo* method));  // RELIC-TODO-16 readable method get_constraints does not exist in the 1.6 class UnityEngine.Rigidbody (its other readable names survive) - absent or renamed in 1.6
DO_APP_FUNC(0x05EE61B0, void, Rigidbody_set_constraints, (Rigidbody* __this, RigidbodyConstraints__Enum value, MethodInfo* method));  // 1.6: M-name (high) UnityEngine.Rigidbody$$set_constraints
DO_APP_FUNC(0x05EE6150, void, Rigidbody_set_collisionDetectionMode, (Rigidbody* __this, CollisionDetectionMode__Enum value, MethodInfo* method));  // 1.6: M-name (high) UnityEngine.Rigidbody$$set_collisionDetectionMode
DO_APP_FUNC(0x05EE6210, void, Rigidbody_set_detectCollisions, (Rigidbody* __this, bool value, MethodInfo* method));  // 1.6: M-name (high) UnityEngine.Rigidbody$$set_detectCollisions
DO_APP_FUNC(0x05EE6390, void, Rigidbody_set_isKinematic, (Rigidbody* __this, bool value, MethodInfo* method));  // 1.6: M-name (high) UnityEngine.Rigidbody$$set_isKinematic
DO_APP_FUNC(0x05EE5FF0, Vector3, Rigidbody_get_velocity, (Rigidbody* __this, MethodInfo* method));  // 1.6: M-name (high) UnityEngine.Rigidbody$$get_velocity
DO_APP_FUNC(0x05EE57B0, void, Rigidbody_set_velocity, (Rigidbody* __this, Vector3 value, MethodInfo* method));  // 1.6: M-name (high) UnityEngine.Rigidbody$$set_velocity

DO_APP_FUNC(0x053782C0, float, Time_get_timeScale__RAW, (void* __this_unused, MethodInfo* method));  // 1.6: M-name (high) UnityEngine.Time$$get_timeScale
DO_APP_FUNC(0x053785C0, void, Time_set_timeScale__RAW, (void* __this_unused, float value, MethodInfo* method));  // 1.6: M-name (high) UnityEngine.Time$$set_timeScale
DO_APP_FUNC(0x05377EB0, float, Time_get_deltaTime__RAW, (void* __this_unused, MethodInfo* method));  // 1.6: M-name (high) UnityEngine.Time$$get_deltaTime

DO_APP_FUNC(0x053EB320, Vector3, Camera_WorldToScreenPoint, (Camera* __this, Vector3 position, MethodInfo* method));  // 1.6: M-name (high) UnityEngine.Camera$$WorldToScreenPoint
DO_APP_FUNC(0x053EBE10, Camera*, Camera_get_main__RAW, (void* __this_unused, MethodInfo* method));  // 1.6: M-name (high) UnityEngine.Camera$$get_main
DO_APP_FUNC(0x053EC150, int32_t, Camera_get_pixelWidth, (Camera* __this, MethodInfo* method));  // 1.6: M-name (high) UnityEngine.Camera$$get_pixelWidth
DO_APP_FUNC(0x053EC080, int32_t, Camera_get_pixelHeight, (Camera* __this, MethodInfo* method));  // 1.6: M-name (high) UnityEngine.Camera$$get_pixelHeight

DO_APP_FUNC(0x0536EE90, int32_t, Screen_get_width__RAW, (void* __this_unused, MethodInfo* method));  // 1.6: M-name (high) UnityEngine.Screen$$get_width
DO_APP_FUNC(0x0536ED30, int32_t, Screen_get_height__RAW, (void* __this_unused, MethodInfo* method));  // 1.6: M-name (high) UnityEngine.Screen$$get_height

DO_APP_FUNC(0x05F2C3C0, void, Animator_Play, (Animator* __this, String* stateName, int32_t layer, float normalizedTime, MethodInfo* method));  // 1.6: M-name (high) UnityEngine.Animator$$Play
DO_APP_FUNC(0x05F2C650, void, Animator_Rebind, (Animator* __this, MethodInfo* method));  // 1.6: M-name (high) UnityEngine.Animator$$Rebind
DO_APP_FUNC(0x05F2DA40, float, Animator_get_speed, (Animator* __this, MethodInfo* method));  // 1.6: M-name (high) UnityEngine.Animator$$get_speed
DO_APP_FUNC(0x05F2DE20, void, Animator_set_speed, (Animator* __this, float value, MethodInfo* method));  // 1.6: M-name (high) UnityEngine.Animator$$set_speed

DO_APP_FUNC(0x053E7170, bool, Behaviour_get_isActiveAndEnabled, (Behaviour* __this, MethodInfo* method));  // 1.6: M-name (high) UnityEngine.Behaviour$$get_isActiveAndEnabled

DO_APP_FUNC(0x052CD5C0, Vector3, Quaternion_ToEulerAngles__RAW, (void* __this_unused, Quaternion rotation, MethodInfo* method));  // 1.6: M-name (high) UnityEngine.Quaternion$$ToEulerAngles
DO_APP_FUNC(0x052CE080, Vector3, Quaternion_get_eulerAngles, (Quaternion__Boxed* __this, MethodInfo* method));  // 1.6: M-name (high) UnityEngine.Quaternion$$get_eulerAngles
DO_APP_FUNC(0x0537BF70, Quaternion, Transform_get_rotation, (Transform* __this, MethodInfo* method));  // 1.6: M-name (high) UnityEngine.Transform$$get_rotation
DO_APP_FUNC(0x052D1B80, Rect, RectTransform_get_rect, (RectTransform* __this, MethodInfo* method));  // 1.6: M-name (high) UnityEngine.RectTransform$$get_rect
DO_APP_FUNC(0x05F6DFF0, float, Canvas_get_scaleFactor, (/*Canvas**/void* __this, MethodInfo* method));  // 1.6: M-name (high) UnityEngine.Canvas$$get_scaleFactor


DO_APP_FUNC(0x030A1100, void, LevelTimeManager_SetInternalTimeOfDay, (/*LevelTimeManager**/void* __this, float inHours, bool force, bool refreshEnviroTime, MethodInfo* method));  // 1.6: M-name-arity (low) MoleMole.LevelTimeManager$$SetInternalTimeOfDay | ARITY: 1.6 has 2 parameter(s) vs 3 in 2.8 (void SetInternalTimeOfDay(float inHours, bool force = False)); trailing arguments are ignored by the x64 ABI


// Singletons
DO_APP_FUNC(0x05489220, void*, Singleton_GetInstance__RAW, (void* __this_unused, MethodInfo* method));  // 1.6: M-generic (high) MoleMole.Singleton<object>$$GetInstance (+7 instantiations sharing the body) | shared generic body of MoleMole.Singleton<T>.GetInstance<T>; 2.8 body shared by ['GetInstance', 'get_Instance']
DO_APP_FUNC_METHODINFO(0x08FD4780, Singleton_1_MoleMole_MapModule__get_Instance__MethodInfo);  // 1.6: slot via class map (high) Method$MoleMole.Singleton<MHGOONJMBFO>.get_Instance()
DO_APP_FUNC_METHODINFO(0x08F56680, Singleton_1_MoleMole_LoadingManager__get_Instance__MethodInfo);  // 1.6: slot via class map (high) Method$MoleMole.Singleton<FFHBJKFKMOC>.get_Instance()
DO_APP_FUNC_METHODINFO(0x08F6CE30, Singleton_1_MoleMole_EntityManager__get_Instance__MethodInfo);  // 1.6: slot via class map (high) Method$MoleMole.Singleton<GIHJJEIOMJL>.get_Instance()
DO_APP_FUNC_METHODINFO(0x08F9BAB0, Singleton_1_InteractionManager__get_Instance__MethodInfo);  // 1.6: slot via class map (high) Method$MoleMole.Singleton<InteractionManager>.get_Instance()
DO_APP_FUNC_METHODINFO(0x08F9E870, Singleton_1_MoleMole_UIManager__get_Instance__MethodInfo);  // 1.6: slot via class map (high) Method$MoleMole.Singleton<CCMGKAJLOGF>.get_Instance()
DO_APP_FUNC_METHODINFO(0x08FB6070, Singleton_1_MoleMole_ItemModule__get_Instance__MethodInfo);  // 1.6: slot via class map (high) Method$MoleMole.Singleton<GEJMEJDKBIM>.get_Instance()
DO_APP_FUNC_METHODINFO(0x08F6B140, Singleton_1_MoleMole_EventManager__get_Instance__MethodInfo);  // 1.6: slot via class map (high) Method$MoleMole.Singleton<CADNPCCFBBB>.get_Instance()
DO_APP_FUNC_METHODINFO(0x08F84128, Singleton_1_MoleMole_PlayerModule__get_Instance__MethodInfo);  // 1.6: slot via class map (high) Method$MoleMole.Singleton<BOACBNICNDP>.get_Instance()
DO_APP_FUNC_METHODINFO(0x08F51EB0, Singleton_1_MoleMole_MapManager__get_Instance__MethodInfo);  // 1.6: slot via class map (high) Method$MoleMole.Singleton<GPMEDMPGALI>.get_Instance()
DO_APP_FUNC_METHODINFO(0x08F6E360, Singleton_1_MoleMole_ScenePropManager__get_Instance__MethodInfo);  // 1.6: slot via class map (high) Method$MoleMole.Singleton<IGNFJKIBHOO>.get_Instance()
DO_APP_FUNC_METHODINFO(0x08FB7DC8, Singleton_1_MoleMole_NetworkManager__get_Instance__MethodInfo);  // 1.6: slot via class map (high) Method$MoleMole.Singleton<OMKJLMHHNEL>.get_Instance()


// ---- Relic backport: declared by the 3.3 feature code, absent from the upstream 2.8 headers ----
// 0x0 = not resolved yet for game 2.8 (becomes a null pointer; HookManager skips such hooks).
// Fill with tools/transplant.py (dump) / Release_WS scanner / manual xref, then drop the marker.
DO_APP_FUNC(0x04B18F90, String*, Marshal_PtrToStringUni__RAW, (void* __this_unused, void* ptr, MethodInfo* method));  // 1.6: M-name (high) System.Runtime.InteropServices.Marshal$$PtrToStringUni
DO_APP_FUNC(0x0, void, VCHumanoidMove_MNKKEGMDFFO, (VCHumanoidMove* __this, float JJJEOEHLNGP, MethodInfo* method));  // RELIC-TODO-16 0x0 in appdata-28 as well (never resolved for 2.8)
DO_APP_FUNC(0x014409A0, void, MoleMole_ItemModule_OnCheckAddItemExceedLimitNotify, (/*MoleMole_ItemModule* */ void* __this, Proto_CheckAddItemExceedLimitNotify* notify, MethodInfo* method));  // 1.6: M-fp (high) GEJMEJDKBIM$$IGBNMIDJCIF | fp 0.29 (5 shared strings/calls), runner-up 0.25
DO_APP_FUNC(0x00BF4A70, void, MoleMole_PlayerModule_OnWindSeedClientNotify, (MoleMole_PlayerModule* __this, Proto_WindSeedClientNotify* notify, MethodInfo* method));  // 1.6: M-pos (medium) BOACBNICNDP$$IEEFPKCKOOI | declaration-order alignment (lists align 0.92); fp 0.00; runner-up 0.23
DO_APP_FUNC(0x0, void, MoleMole_PlayerModule_OnReciveLuaShell, (MoleMole_PlayerModule* __this, Proto_PlayerLuaShellNotify* playerLuaShellNotify, MethodInfo* method));  // RELIC-TODO-16 0x0 in appdata-28 as well (never resolved for 2.8)
DO_APP_FUNC(0x00BF2170, void, MoleMole_PlayerModule_EntityAppear, (MoleMole_PlayerModule* __this, Proto_SceneEntityInfo* entity, VisionType__Enum type, uint32_t infoParam, MethodInfo* method));  // 1.6: M-pos (medium) BOACBNICNDP$$HNMGDDAJAJN | declaration-order alignment (lists align 0.92); fp 0.13; runner-up 0.31
DO_APP_FUNC(0x01674B20, void, MoleMole_LCAvatarCombat_SetSkillIndex, (LCAvatarCombat* __this, LCAvatarCombat_LCAvatarCombat_SkillInfo* skillInfo, int32_t index, int32_t priority, MethodInfo* method));  // 1.6: M-sig (high) DIIAFDKMCEE$$LCJOCLPFDMN | only compatible signature in DIIAFDKMCEE; fp 0.00, 0 shared; method lists align 0.91
// RELIC hand-fix (do not let a regeneration overwrite this): the matcher picked 0x01673E90 =
// DIIAFDKMCEE$$JJJBFMBJHPG(HKIEEJMCECJ), which is the melee/ranged targeting-bucket rebuild - HKIEEJMCECJ has
// fields only up to 0x1C, so reading SkillInfo.skillIndex at +0x108 and cdTimer at +0x20 was out of object
// (the 0xC0000005 in the 1.6 log). The real counterpart of 2.8 AADPEKIMEML @0x026EEF50 is
// DIIAFDKMCEE$$LBBIBLMOFFL @0x016749A0: same two callers (the CD tick GGNKBOAJDAH @0x016724A0 and
// IPLLMGJNJMA @0x01673810, twins of 2.8 NNFHBMAPCBN / BNIBNADAPEA), same body (cd < 0 guard, then the
// ready-notify through this+0x160). 1.6 passes the _skillInfoMap key as a LEADING uint that 2.8 reads out of
// the SkillInfo - the extra parameter is deliberate, so any attempt to re-install this hook on 1.6 fails to
// compile instead of hooking a differently-shaped method (ShowSkillCD does not install it on 1.6 at all).
DO_APP_FUNC(0x016749A0, void, MoleMole_LCAvatarCombat_CheckCDTimer, (LCAvatarCombat* __this, uint32_t skillID, LCAvatarCombat_LCAvatarCombat_SkillInfo* info, MethodInfo* method));  // 1.6: hand-verified DIIAFDKMCEE$$LBBIBLMOFFL  // 1.6: M-sig (low) DIIAFDKMCEE$$JJJBFMBJHPG | IDENTITY-CONFLICT: a matched 2.8 parameter type is not the type the 1.6 method takes (check the class match); only compatible signature in DIIAFDKMCEE; fp 0.00, 0 shared; method lists align 0.91
DO_APP_FUNC(0x0166F0D0, int32_t, MoleMole_LCAvatarCombat_GetSkillMaxChargesCount, (LCAvatarCombat* __this, uint32_t skillID, MethodInfo* method));  // 1.6: M-pos (medium) DIIAFDKMCEE$$BLMKGEAHONC | declaration-order alignment (lists align 0.91); fp 0.72; runner-up 1.02
DO_APP_FUNC(0x0166EAC0, int32_t, MoleMole_LCAvatarCombat_GetSkillCurrentChargesCount, (LCAvatarCombat* __this, uint32_t skillID, MethodInfo* method));  // 1.6: M-sig (high) DIIAFDKMCEE$$BFJNIMHPCBE | only compatible signature in DIIAFDKMCEE; fp 0.43, 0 shared; method lists align 0.91
// RELIC hand-added (1.6): DIIAFDKMCEE$$KCNMJMDPCEI(uint) returns LCAvatarCombat._currSkills[index] - the
// 6-element SkillInfo array at +0x1D0, filled by GIABONGEFCF(0..5) during the avatar's skill setup. Index 1
// is the elemental skill. Bounds-checked by the game (returns null when the index is out of range), so 1.6
// can read the live cooldown without hooking anything. ABI pinned by the game's own caller
// MonoTeamBtn$$OIAFAGIHDNN @0x0334A930: (this, index, MethodInfo = null).
DO_APP_FUNC(0x016745B0, LCAvatarCombat_LCAvatarCombat_SkillInfo*, MoleMole_LCAvatarCombat_GetSkillInfoByIndex, (LCAvatarCombat* __this, uint32_t index, MethodInfo* method));  // 1.6: hand-verified DIIAFDKMCEE$$KCNMJMDPCEI

// RELIC hand-added (1.6): MoleMole.Miscs.SetUILocalAvatarVisible does not exist in 1.6 (it was added later -
// the whole 1.6 Miscs class is unobfuscated and has no such member), so the entry above stays 0x0. 2.8's body
// is just  localAvatar.GetRendererComponent().SetRendererVisible(v, 14, true)  and 1.6 ships both halves as
// ordinary INSTANCE methods (no dummy this, no static thunk). The game itself calls them back to back in
// InteractionManager$$ResumeAvatarVisibleSet @0x01CA2810, which also proves MethodInfo may be null.
// The 'reason' is a bit index in a SimpleFixedBitStack initialised all-ones (visible = every bit set), so
// clearing one bit hides; 14 is the slot 2.8's Miscs uses and no 1.6 game code ever passes it.
DO_APP_FUNC(0x00CF5100, /*MoleMole_BaseEntityRendererComponent*/ void*, MoleMole_BaseEntity_GetRendererComponent, (BaseEntity* __this, MethodInfo* method));  // 1.6: hand-verified DNPPAIELOMJ$$MKIHLPLFIBI
DO_APP_FUNC(0x030E9970, void, MoleMole_BaseEntityRendererComponent_SetRendererVisible, (/*MoleMole_BaseEntityRendererComponent*/ void* __this, bool visible, int32_t reason, bool immediate, MethodInfo* method));  // 1.6: hand-verified HFCOBKMKNLN$$JLBIFIBAALA

// RELIC hand-added (1.6): miHoYoCamera.CameraStateMgr.FlushStateData (dump.cs:655845) is where the game
// applies the camera pose it has just computed - it runs the state position through
// WorldShiftManager.GetRelativePosition @0x042DA330 and calls Transform.set_position @0x0537C810 on the
// camera, then its rotation. Flush @0x067F2640 runs the post processer (FlushPostProcesserInternal
// @0x067F20E0) BEFORE it and PostFlushTop @0x067F2AB0 after it writes no transform, so this is the last
// writer of the camera pose in a frame. The owner is the level camera plugin (OHLKPGALLOI, dump.cs:845489:
// Camera @0x118, CinemachineBrain @0x120, CameraStateMgr @0x128, CameraStateData @0x940).
DO_APP_FUNC(0x067F2160, void, miHoYoCamera_CameraStateMgr_FlushStateData, (/*miHoYoCamera_CameraStateMgr*/ void* __this, /*CameraStateData*/ void* data, MethodInfo* method));  // 1.6: hand-verified miHoYoCamera.CameraStateMgr$$FlushStateData

DO_APP_FUNC(0x0334B490, void, MonoTeamBtn_SetupView, (MonoTeamBtn* __this, uint64_t guid, MethodInfo* method));  // 1.6: M-name (high) MoleMole.MonoTeamBtn$$SetupView
DO_APP_FUNC(0x0334C740, void, MonoTeamBtn_set_PCKey, (MonoTeamBtn* __this, String* value, MethodInfo* method));  // 1.6: M-name (high) MoleMole.MonoTeamBtn$$set_PCKey
DO_APP_FUNC(0x0334C590, /*MonoControlElement*/ void*, MonoTeamBtn_get_PS4KeyIcon, (MonoTeamBtn* __this, MethodInfo* method));  // 1.6: M-name (high) MoleMole.MonoTeamBtn$$get_PS4KeyIcon
DO_APP_FUNC(0x00D239A0, bool, MoleMole_UIManager_IsPS4Layout__RAW, (void* __this_unused, MethodInfo* method));  // 1.6: M-pos (medium) CCMGKAJLOGF$$BJOKLBKCOAC | declaration-order alignment (lists align 0.90); fp 0.28; runner-up 0.29
DO_APP_FUNC(0x01C64500, void, MoleMole_CookingQtePageContext_CloseItemGotPanel, (CookingQtePageContext* __this, MethodInfo* method));  // 1.6: M-pos (medium) JLOOJHNNGII$$CDGHEHGCDPJ | declaration-order alignment (lists align 0.99); fp 0.00; runner-up 0.25
DO_APP_FUNC(0x05378B80, Transform*, Transform_FindChild, (Transform* __this, String* name, MethodInfo* method));  // 1.6: M-name (high) UnityEngine.Transform$$FindChild
DO_APP_FUNC(0x0297D6E0, uint64_t, MoleMole_TimeUtil_get_LocalNowMsTimeStamp__RAW, (void* __this_unused, MethodInfo* method));  // 1.6: M-family (low) DBOIMGBJPNK$$AEJFMHGGPID | equivalent family: ['AEJFMHGGPID', 'EBJDHHJIPIA'] are identical bodies (masked code similarity >= 0.98); the best-scored one taken
DO_APP_FUNC(0x00D3AD70, void, MoleMole_UIManager_EnableInput, (MoleMole_UIManager* __this, bool playerInput, bool clearCurInputState, bool ignoreTouch, MethodInfo* method));  // 1.6: M-sig (high) CCMGKAJLOGF$$OFCOFHGIEBP | only compatible signature in CCMGKAJLOGF; fp 0.13, 1 shared; method lists align 0.90
DO_APP_FUNC(0x00D224D0, void, MoleMole_UIManager_TryShowNormalMessage, (MoleMole_UIManager* __this, String* content, Color bgColor, bool showBackground, MethodInfo* method));  // 1.6: M-sig (high) CCMGKAJLOGF$$AMMDOENOHPI | only compatible signature in CCMGKAJLOGF; fp 0.19, 1 shared; method lists align 0.90
DO_APP_FUNC(0x00D36AC0, void, MoleMole_UIManager_TryShowInfoMessageWithoutBlockInput, (MoleMole_UIManager* __this, String* content, bool discardIfDuplicated, UIShowPriority__Enum priority, MethodInfo* method));  // 1.6: M-pos (medium) CCMGKAJLOGF$$MECNJBPKLDM | declaration-order alignment (lists align 0.90); fp 0.19; runner-up 0.55
DO_APP_FUNC(0x01109DD0, /*MoleMole_GeneralDialogContext*/void*, MoleMole_UIUtil_TryShowGeneralDialog, (String* title, String* desc, /*Action_1_Boolean_*/void* callback, UIType__Enum uiType, /*MoleMole_WaitForGeneralDialog*/void* yieldIns, GeneralDialogContext_GeneralDialogType__Enum dialogType, UIShowPriority__Enum mode, bool showNormalCloseBtn, bool isToggleDialog, bool MCJCBLMKDKC, MethodInfo* method));  // 1.6: M-sig-prefix (medium) IOOBEBKPMCG$$CJDEABFHJLF | ARITY: 1.6 has 7 parameter(s) vs 9 in 2.8 (static PLOHPHPOILP CJDEABFHJLF(string LEMGFIKGOHK, string DENLJFJIJKL, Action<bool> DNKEMICDGHG, KGCKAOEEOOD JFDLHNCMBPE = 3, DBHMKCHIJPM DNONELIGJLN, PLOHPHPOILP.CNFEDCJIGLL KBGHBFPNHGN = 0, CFPGAMCFIHO MJCNGFNIFCP = 0)); trailing arguments are ignored by the x64 ABI; only compatible signature in IOOBEBKPMCG; fp 0.15, 0 shared; method lists align 0.75
DO_APP_FUNC(0x01108380, /*MoleMole_GeneralDialogContext*/void*, MoleMole_UIUtil_TryShowSimpleGeneralDialog_1__RAW, (void* __this_unused, String* title, String* content, /*Action*/void* buttonCallback, MethodInfo* method));  // 1.6: M-sig-ret (low) IOOBEBKPMCG$$BJJJNMNEJKA | RETURN differs: 1.6 static void BJJJNMNEJKA(string LEMGFIKGOHK, string DENLJFJIJKL, Action DNKEMICDGHG) (2.8 returned IIMLFCEABPO); the caller must not use the return value; fp 0.00
DO_APP_FUNC(0x053E4980, SystemLanguage__Enum, Application_get_systemLanguage__RAW, (void* __this_unused, MethodInfo* method));  // 1.6: M-name (high) UnityEngine.Application$$get_systemLanguage
DO_APP_FUNC(0x053E46A0, bool, Application_get_IsFocused__RAW, (void* __this_unused, MethodInfo* method));  // 1.6: M-name (high) UnityEngine.Application$$get_isFocused
DO_APP_FUNC(0x068611F0, void, EmoSync_ResetEmotion, (EmoSync* __this, bool playPost, MethodInfo* method));  // 1.6: M-name (high) miHoYoEmotion.EmoSync$$ResetEmotion
DO_APP_FUNC(0x06861760, void, EmoSync_SetEmotion, (EmoSync* __this, String* emotionName, float blendTime, MethodInfo* method));  // 1.6: M-name (high) miHoYoEmotion.EmoSync$$SetEmotion
DO_APP_FUNC(0x06861360, void, EmoSync_ResetPhoneme, (EmoSync* __this, bool playPost, MethodInfo* method));  // 1.6: M-name (high) miHoYoEmotion.EmoSync$$ResetPhoneme
DO_APP_FUNC(0x06861D90, void, EmoSync_SetPhoneme, (EmoSync* __this, String* phonemeName, float blendTime, MethodInfo* method));  // 1.6: M-name (high) miHoYoEmotion.EmoSync$$SetPhoneme
DO_APP_FUNC(0x06860060, void, EmoSync_EmoFinish, (EmoSync* __this, MethodInfo* method));  // 1.6: M-name (high) miHoYoEmotion.EmoSync$$EmoFinish
DO_APP_FUNC(0x06860920, void, EmoSync_PhoFinish, (EmoSync* __this, MethodInfo* method));  // 1.6: M-name (high) miHoYoEmotion.EmoSync$$PhoFinish
DO_APP_FUNC(0x05F2D510, Avatar*, Animator_get_avatar, (Animator* __this, MethodInfo* method));  // 1.6: M-name (high) UnityEngine.Animator$$get_avatar
DO_APP_FUNC(0x044D20A0, String*, Extension_GetCurrentStateName__RAW, (void* __this_unused, Animator* animator, int32_t layer, AnimatorController* animCont, MethodInfo* method));  // 1.6: M-name (high) Extension$$GetCurrentStateName
DO_APP_FUNC(0x045A9C80, void, Action_Invoke, (/*Action*/ void* __this, MethodInfo* method));  // 1.6: M-name (high) System.Action$$Invoke
DO_APP_FUNC(0x00BDC950, void, MoleMole_PlayerModule_ChangeGameTime, (MoleMole_PlayerModule* __this, float value, bool force, bool forceLocal, MethodInfo* method));  // 1.6: M-sig (high) BOACBNICNDP$$ANAMNJEELGA | only compatible signature in BOACBNICNDP; fp 0.39, 2 shared; method lists align 0.92
DO_APP_FUNC(0x0, void, Miscs_SetUILocalAvatarVisible, (bool visible, MethodInfo* method));  // RELIC-TODO-16 readable method SetUILocalAvatarVisible does not exist in the 1.6 class MoleMole.Miscs (its other readable names survive) - absent or renamed in 1.6
DO_APP_FUNC(0x0, bool, MoleMole_InLevelMainPageContext_DoTeamCountDown_c_Iterator0__MoveNext, (InLevelMainPageContext_DoTeamCountDown_Iterator* __this, MethodInfo* method));  // RELIC-TODO-16 0x0 in appdata-28 as well (never resolved for 2.8)
DO_APP_FUNC(0x00FEA900, void, MoleMole_InLevelPlayerProfilePageContext_SetupView, (/*MoleMole_InLevelPlayerProfilePageContext*/void* __this, MethodInfo* method));  // 1.6: M-name (high) JNJKKGKJING$$SetupView
DO_APP_FUNC(0x00FE08A0, void, MoleMole_InLevelPlayerProfilePageContext_ClearView, (/*MoleMole_InLevelPlayerProfilePageContext*/void* __this, MethodInfo* method));  // 1.6: M-name (high) JNJKKGKJING$$ClearView
DO_APP_FUNC(0x018048C0, void, MoleMole_EquipLevelUpDialogContext_SetupView, (MoleMole_EquipLevelUpDialogContext* __this, MethodInfo* method));  // 1.6: M-name (high) KOKEHCPDJKC$$SetupView
DO_APP_FUNC(0x0, void, MoleMole_EquipLevelUpDialogContext_ShowReturnedMaterialAndCloseDialog, (/*MoleMole_EquipLevelUpDialogContext*/ void* __this, MethodInfo* method));  // RELIC-TODO-16 0x0 in appdata-28 as well (never resolved for 2.8)
DO_APP_FUNC(0x01314810, void, MoleMole_EquipOverviewPageContext_PlayExpAddAnimation, (/*MoleMole_EquipOverviewPageContext*/ void* __this, float startPer, float endPer, /*Action*/ void* callback, MethodInfo* method));  // 1.6: M-sig (high) LJIGGMFPJIA$$GLONBFKBPPN | only compatible signature in LJIGGMFPJIA; fp 0.13, 0 shared; method lists align 0.97
DO_APP_FUNC(0x0, void, MoleMole_EquipOverviewPageContext_PlayLevelUpSuccessShow, (/*MoleMole_EquipOverviewPageContext*/ void* __this, /*Action*/ void* refreshViewAction, MethodInfo* method));  // RELIC-TODO-16 0x0 in appdata-28 as well (never resolved for 2.8)
DO_APP_FUNC(0x04F91B10, void, RSA_FromXmlString, (RSA* __this, String* xmlString, MethodInfo* method));  // 1.6: M-name (high) System.Security.Cryptography.RSA$$FromXmlString
DO_APP_FUNC(0x014AB510, void, MoleMole_GadgetModule_DoOnGadgetStateNotify, (GadgetModule* __this, uint32_t gadgetEntityId, uint32_t gadgetState, bool isEnableInteract, MethodInfo* method));  // 1.6: M-sig (high) ILECJOHHNEI$$AKDHJJBIBIC | only compatible signature in ILECJOHHNEI; fp 0.05, 0 shared; method lists align 0.89
DO_APP_FUNC(0x00E3B4D0, void, MoleMole_LevelModule_OnSceneEntityAppear, (LevelModule* __this, Proto_SceneEntityAppearNotify* notify, uint32_t JOODHPBLPMA, MethodInfo* method));  // 1.6: M-fp-prefix (low) HKGIPLLFJCJ$$CFEJFANLJLF | ARITY: 1.6 has 1 parameter(s) vs 2 in 2.8 (void CFEJFANLJLF(HDIOJNDADCH KCKOAHDGJGH)); trailing arguments are ignored by the x64 ABI; weak fp 0.32, margin 0.36
DO_APP_FUNC(0x00E43FA0, void, MoleMole_LevelModule_OnSceneEntityAppearAsync, (LevelModule* __this, Proto_SceneEntityAppearNotify* notify, uint32_t JOODHPBLPMA, MethodInfo* method));  // 1.6: M-sig-prefix (medium) HKGIPLLFJCJ$$MKLEBGLDODB | ARITY: 1.6 has 1 parameter(s) vs 2 in 2.8 (void MKLEBGLDODB(HDIOJNDADCH KCKOAHDGJGH)); trailing arguments are ignored by the x64 ABI; only compatible signature in HKGIPLLFJCJ; fp 0.15, 0 shared; method lists align 0.72

// RELIC: UnityEngine.Rendering.PostProcessing.PostProcessLayer inner-resolution scale - the game's
// "Render Resolution" setting, after every clamp. SetupInnerResolution -> UpdateInnerTarget computes
// FloorToInt(w * innerResolutionScale * ratio) x FloorToInt(h * innerResolutionScale) and allocates that
// through RenderTexture.GetTemporary as the camera's target texture, so a value above 1.0 is genuine
// supersampling. The setter carries no clamp and no equality guard and is the only code path that writes
// the field, so hooking it defeats all three ceilings sitting above it: the data-driven option table the
// settings menu reads (whose last entry is 1.5), Mathf.Min(v, 2.0f), and the desktop-resolution gate that
// silently forces the scale down above 2560x1440. Instance method with the same ABI on 1.6 and 2.8.
DO_APP_FUNC(0x06790640, void, PostProcessLayer_set_innerResolutionScale, (/*PostProcessLayer*/ void* __this, float value, MethodInfo* method));  // 1.6: M-name (high) UnityEngine.Rendering.PostProcessing.PostProcessLayer$$set_innerResolutionScale (dump.cs:692180)
DO_APP_FUNC(0x067901F0, float, PostProcessLayer_get_innerResolutionScale, (/*PostProcessLayer*/ void* __this, MethodInfo* method));  // 1.6: M-name (high) UnityEngine.Rendering.PostProcessing.PostProcessLayer$$get_innerResolutionScale (dump.cs:692176)

// RELIC: "Render Distance" (visuals/RenderDistance.cpp) - see the same block in appdata-28. The UnityEngine names
// are unobfuscated and matched by name; the profile holder JBPNDKLFIFM (dump.cs:1961564) is pinned by the same five
// "Data/LevelStreamingConfig/..." const strings and the same field/property/method shape as 2.8's KIFKAIFDIIC, and
// SECTR_StreamingProfile itself has identical field offsets on both versions (dump.cs:1961468). The getter and the
// shadow setter are STATIC, so 1.6 passes a leading dummy `this`: the getter takes the __RAW + inline-wrapper shape
// (il2cpp-static-thunks.h), the setter is HOOKED and therefore keeps its name (the handler carries the dummy).
// Hand decisions recorded in tools/offsets-16.overrides.json.
DO_APP_FUNC(0x0362BBA0, /*SECTR_StreamingProfile*/ void*, SECTR_Streaming_get_CurrentProfile__RAW, (void* __this_unused, MethodInfo* method));  // 1.6: M-name (high) JBPNDKLFIFM$$CKNBJAPIHJE (dump.cs:1961683)
DO_APP_FUNC(0x05F91660, /*Int32__Array*/ void*, MiHoYoGrassGlobalConfigurator_GetViewRange, (/*MiHoYoGrassGlobalConfigurator*/ void* __this, MethodInfo* method));  // 1.6: M-name (high) UnityEngine.MiHoYoGrassGlobalConfigurator$$GetViewRange (dump.cs:395627)
DO_APP_FUNC(0x05F91830, void, MiHoYoGrassGlobalConfigurator_SetViewRange, (/*MiHoYoGrassGlobalConfigurator*/ void* __this, /*Int32__Array*/ void* newData, MethodInfo* method));  // 1.6: M-name (high) UnityEngine.MiHoYoGrassGlobalConfigurator$$SetViewRange (dump.cs:395631)
DO_APP_FUNC(0x05F91520, /*Single__Array*/ void*, MiHoYoGrassGlobalConfigurator_GetLOD0DistanceSet, (/*MiHoYoGrassGlobalConfigurator*/ void* __this, MethodInfo* method));  // 1.6: M-name (high) UnityEngine.MiHoYoGrassGlobalConfigurator$$GetLOD0DistanceSet (dump.cs:395595)
DO_APP_FUNC(0x05F916B0, void, MiHoYoGrassGlobalConfigurator_SetLOD0DistanceSet, (/*MiHoYoGrassGlobalConfigurator*/ void* __this, /*Single__Array*/ void* newData, MethodInfo* method));  // 1.6: M-name (high) UnityEngine.MiHoYoGrassGlobalConfigurator$$SetLOD0DistanceSet (dump.cs:395599)
DO_APP_FUNC(0x05F91570, /*Single__Array*/ void*, MiHoYoGrassGlobalConfigurator_GetLOD1DistanceSet, (/*MiHoYoGrassGlobalConfigurator*/ void* __this, MethodInfo* method));  // 1.6: M-name (high) UnityEngine.MiHoYoGrassGlobalConfigurator$$GetLOD1DistanceSet (dump.cs:395603)
DO_APP_FUNC(0x05F91710, void, MiHoYoGrassGlobalConfigurator_SetLOD1DistanceSet, (/*MiHoYoGrassGlobalConfigurator*/ void* __this, /*Single__Array*/ void* newData, MethodInfo* method));  // 1.6: M-name (high) UnityEngine.MiHoYoGrassGlobalConfigurator$$SetLOD1DistanceSet (dump.cs:395607)
DO_APP_FUNC(0x05F915C0, /*Single__Array*/ void*, MiHoYoGrassGlobalConfigurator_GetLOD2DistanceSet, (/*MiHoYoGrassGlobalConfigurator*/ void* __this, MethodInfo* method));  // 1.6: M-name (high) UnityEngine.MiHoYoGrassGlobalConfigurator$$GetLOD2DistanceSet (dump.cs:395611)
DO_APP_FUNC(0x05F91770, void, MiHoYoGrassGlobalConfigurator_SetLOD2DistanceSet, (/*MiHoYoGrassGlobalConfigurator*/ void* __this, /*Single__Array*/ void* newData, MethodInfo* method));  // 1.6: M-name (high) UnityEngine.MiHoYoGrassGlobalConfigurator$$SetLOD2DistanceSet (dump.cs:395615)
DO_APP_FUNC(0x05F91610, /*Single__Array*/ void*, MiHoYoGrassGlobalConfigurator_GetLOD3DistanceSet, (/*MiHoYoGrassGlobalConfigurator*/ void* __this, MethodInfo* method));  // 1.6: M-name (high) UnityEngine.MiHoYoGrassGlobalConfigurator$$GetLOD3DistanceSet (dump.cs:395619)
DO_APP_FUNC(0x05F917D0, void, MiHoYoGrassGlobalConfigurator_SetLOD3DistanceSet, (/*MiHoYoGrassGlobalConfigurator*/ void* __this, /*Single__Array*/ void* newData, MethodInfo* method));  // 1.6: M-name (high) UnityEngine.MiHoYoGrassGlobalConfigurator$$SetLOD3DistanceSet (dump.cs:395623)
DO_APP_FUNC(0x052CAAC0, void, QualitySettings_set_shadowDistance, (void* __this_unused, float value, MethodInfo* method));  // 1.6: M-name (high) UnityEngine.QualitySettings$$set_shadowDistance (dump.cs:366154)  // Relic 1.6: static -> leading dummy `this` (the hook handler carries it too)
// RELIC: the live SECTR_SceneSplitterConfig getter - see appdata-28. Same holder JBPNDKLFIFM; the grass debug dialog
// (DAMGDLHDIMN.KLLPECJONLG @0x2966130) calls it and walks layerConfigs for type == 8. STATIC -> __RAW + thunk.
DO_APP_FUNC(0x0362D790, /*SECTR_SceneSplitterConfig*/ void*, SECTR_Streaming_get_SceneSplitterConfig__RAW, (void* __this_unused, MethodInfo* method));  // 1.6: M-name (high) JBPNDKLFIFM$$HAAKNBJALEP (dump.cs:1961707)
// RELIC: the streaming GlobalManager singleton slot - see appdata-28. DKKCBPEDPHF (dump.cs:1307552) is pinned by the
// same shape as 2.8's DPGBNEHAGDM (GlobalManager + IWorldShiftAgent, the job HashSet/Lists, the StreamPreloadConfig
// const) and by the job init PFLMLHGJBIM.NHIEHNGEPPP @0x2B6A0A0 calling its getter. Read-only probe.
DO_APP_FUNC_METHODINFO(0x09083430, Singleton_1_SectrStreamingManager__get_Instance__MethodInfo);  // 1.6: codexref slot Method$MoleMole.Singleton<DKKCBPEDPHF>.get_Instance()
// RELIC: current level + its layer-table build + the cascade split setter - see appdata-28. DKKCBPEDPHF.CJHCHHKIHMP
// (dump.cs:1308030) is the accessor the job init PFLMLHGJBIM.NHIEHNGEPPP @0x2B6A0A0 goes through (via
// DKKCBPEDPHF.JGJBBMLAJFF @0x14895C0 -> OICEICPMMLN.JGJBBMLAJFF @0xEF3560, a Dictionary<string, SECTR_LayerConfig>
// lookup at 0x68); OICEICPMMLN.OAFMCJKHPCK @0xEF44B0 fills that dictionary from get_SceneSplitterConfig (the public
// BGJLCFNOJFK @0xEF2050 is a plain jump to it). Instance methods. The split setter is STATIC and HOOKED, so it keeps
// its name with the dummy `this` like set_shadowDistance (the quality applier FPOAEFCHAMD.AKJJJLAOBDG @0x2738660
// calls it with rcx = 0, rdx = &split, r8 = 0). Hand decisions recorded in tools/offsets-16.overrides.json.
DO_APP_FUNC(0x0147EC80, /*OICEICPMMLN*/ void*, SECTR_StreamingManager_get_CurrentLevel, (void* __this, MethodInfo* method));  // 1.6: M-name (high) DKKCBPEDPHF$$CJHCHHKIHMP (dump.cs:1308030)
DO_APP_FUNC(0x00EF44B0, void, SECTR_StreamingLevel_BuildLayerTables, (void* __this, MethodInfo* method));  // 1.6: M-name (high) OICEICPMMLN$$OAFMCJKHPCK (dump.cs:1962790)
DO_APP_FUNC(0x052CAA20, void, QualitySettings_set_shadowCascade4Split, (void* __this_unused, Vector3 value, MethodInfo* method));  // 1.6: M-name (high) UnityEngine.QualitySettings$$set_shadowCascade4Split (dump.cs:366036)  // Relic 1.6: static -> leading dummy `this` (the hook handler carries it too)
DO_APP_FUNC(0x052CA400, Vector3, QualitySettings_get_shadowCascade4Split__RAW, (void* __this_unused, MethodInfo* method));  // 1.6: M-name (high) UnityEngine.QualitySettings$$get_shadowCascade4Split (dump.cs:366033) - static -> __RAW + thunk; Vector3 returned through the hidden pointer in rcx, dummy this in rdx (LJODCBINFMP.BDEJJPNHDDN @0x2A72280)
// RELIC: the splitter-config loader by path - see appdata-28. JBPNDKLFIFM.KJLFHILAMPB (dump.cs:1961711), called by
// the level creation DKKCBPEDPHF.IDMAGIJGNOP @0x1487220 right before OICEICPMMLN..ctor; the only caller of
// SECTR_SceneSplitterConfig.SortConfigs. STATIC and HOOKED -> keeps its name with the dummy `this`.
DO_APP_FUNC(0x0362E9C0, void, SECTR_Streaming_LoadSplitterConfig, (void* __this_unused, String* path, MethodInfo* method));  // 1.6: M-name (high) JBPNDKLFIFM$$KJLFHILAMPB (dump.cs:1961711)  // Relic 1.6: static -> leading dummy `this` (the hook handler carries it too)
