// Generated C++ file by Il2CppInspector - http://www.djkaty.com - https://github.com/djkaty
// Relic: game 1.6 TypeInfo slots generated by tools/gen_appdata16.py (tools/matcher16.py class map -> 1.6 script.json ScriptMetadata)
// Target Unity version: 2017.4.15 - 2017.4.40

// ******************************************************************************
// * IL2CPP application-specific type definition addresses
// ******************************************************************************

DO_TYPEDEF(0x08F784C8, Byte);  // 1.6: TypeInfo slot (C# keyword type) (high) byte_TypeInfo
DO_TYPEDEF(0x090A1BA8, GameManager);  // 1.6: TypeInfo slot via class map (high) MoleMole.GameManager_TypeInfo
DO_TYPEDEF(0x08F459C0, Int32);  // 1.6: TypeInfo slot (C# keyword type) (high) int_TypeInfo

// v 2.8
DO_TYPEDEF(0x09034840, LCChestPlugin);  // 1.6: TypeInfo slot via class map (high) KHBJGKPMEAP_TypeInfo
DO_TYPEDEF(0x09007270, SceneTreeObject);  // 1.6: TypeInfo slot via class map (high) FDKHDGNCKJF_TypeInfo
DO_TYPEDEF(0x0903C670, MoleMole_ActorModifier);  // 1.6: TypeInfo slot via class map (high) DFOOOKEDJPE_TypeInfo

//// v 2.6
//DO_SINGLETONEDEF(0x0B3442D8, Singleton_1_MoleMole_MapModule_);
//DO_SINGLETONEDEF(0x0B308870, Singleton_1_MoleMole_EntityManager_);
//DO_SINGLETONEDEF(0x0B316A68, Singleton_1_MoleMole_LoadingManager_);
//DO_SINGLETONEDEF(0x0B30BD10, Singleton_1_InteractionManager_);
//DO_SINGLETONEDEF(0x0B2F8038, Singleton_1_MoleMole_UIManager_);
//DO_SINGLETONEDEF(0x0B291838, Singleton_1_MoleMole_ItemModule_);
//DO_SINGLETONEDEF(0x0B309120, Singleton_1_MoleMole_EventManager_);
//DO_SINGLETONEDEF(0x0B326FF8, Singleton_1_MoleMole_PlayerModule_);
//DO_SINGLETONEDEF(0x0B2F2A38, Singleton_1_MoleMole_MapManager_);
//DO_SINGLETONEDEF(0x0B399890, Singleton_1_MoleMole_NetworkManager_);
//DO_SINGLETONEDEF(0x0B2227B8, Singleton_1_MoleMole_ScenePropManager_);

// ---- Relic backport: TypeInfo slots the 3.3 code needs, not in the 2.8 headers (0x0 = unresolved) ----
DO_TYPEDEF(0x090356B8, Proto_SceneAvatarInfo);  // 1.6: TypeInfo slot via class map (medium) COKLEGPLBEH_TypeInfo
DO_TYPEDEF(0x090359A0, Proto_SceneMonsterInfo);  // 1.6: TypeInfo slot via class map (medium) MDIFCECGKLK_TypeInfo
DO_TYPEDEF(0x09036328, Proto_SceneNpcInfo);  // 1.6: TypeInfo slot via class map (high) LJLIFNBAJJI_TypeInfo
DO_TYPEDEF(0x09036768, Proto_SceneGadgetInfo);  // 1.6: TypeInfo slot via class map (medium) PEPHGFNGHFF_TypeInfo
