// GENERATED by tools/gen_static_thunks.py - do not edit by hand.
// Game 16 compiles static methods with a leading dummy `this`; the raw pointers in
// il2cpp-functions.h carry it, these wrappers keep the 3.3 call sites unchanged.

namespace app
{
    inline uint16_t MoleMole_SimpleSafeUInt16_get_Value(SimpleSafeUInt16 v, MethodInfo* method) { return MoleMole_SimpleSafeUInt16_get_Value__RAW(nullptr, v, method); }
    inline uint32_t MoleMole_SimpleSafeUInt32_get_Value(SimpleSafeUInt32 v, MethodInfo* method) { return MoleMole_SimpleSafeUInt32_get_Value__RAW(nullptr, v, method); }
    inline String* Marshal_PtrToStringAnsi(void* ptr, MethodInfo* method) { return Marshal_PtrToStringAnsi__RAW(nullptr, ptr, method); }
    inline void MoleMole_Formula_CalcAttackResult(CombatProperty* attackCombatProperty, CombatProperty* defenseCombatProperty, AttackResult* attackResult, BaseEntity* attackerEntity, BaseEntity* attackeeEntity, MethodInfo* method) { MoleMole_Formula_CalcAttackResult__RAW(nullptr, attackCombatProperty, defenseCombatProperty, attackResult, attackerEntity, attackeeEntity, method); }
    inline Byte__Array* Application_RecordUserData(int32_t nType, MethodInfo* method) { return Application_RecordUserData__RAW(nullptr, nType, method); }
    inline void Kcp_KcpNative_kcp_packet_destroy(KcpPacket_1* packet, MethodInfo* method) { Kcp_KcpNative_kcp_packet_destroy__RAW(nullptr, packet, method); }
    inline KcpPacket_1* Kcp_KcpNative_kcp_packet_create(uint8_t* data, int32_t len, MethodInfo* method) { return Kcp_KcpNative_kcp_packet_create__RAW(nullptr, data, len, method); }
    inline void MoleMole_Packet_XorEncrypt(Byte__Array** bytes, int32_t length, MethodInfo* method) { MoleMole_Packet_XorEncrypt__RAW(nullptr, bytes, length, method); }
    inline EvtCrash* MoleMole_EventHelper_Allocate_103(MethodInfo* method) { return MoleMole_EventHelper_Allocate_103__RAW(nullptr, method); }
    inline uint32_t MoleMole_Config_CookRecipeExcelConfig_CheckCookFoodMaxNum(uint32_t UpdateCookRecipeDic, MethodInfo* method) { return MoleMole_Config_CookRecipeExcelConfig_CheckCookFoodMaxNum__RAW(nullptr, UpdateCookRecipeDic, method); }
    inline void* /*app::EnviroSky*/ EnviroSky_get_Instance(MethodInfo* method) { return EnviroSky_get_Instance__RAW(nullptr, method); }
    inline GameObject* GameObject_Find(String* name, MethodInfo* method) { return GameObject_Find__RAW(nullptr, name, method); }
    inline GameObject* GameObject_CreatePrimitive(PrimitiveType__Enum type, MethodInfo* method) { return GameObject_CreatePrimitive__RAW(nullptr, type, method); }
    inline void Object_1_DestroyImmediate_1(Object_1* obj, MethodInfo* method) { Object_1_DestroyImmediate_1__RAW(nullptr, obj, method); }
    inline Object_1* Object_1_Instantiate_2(Object_1* original, MethodInfo* method) { return Object_1_Instantiate_2__RAW(nullptr, original, method); }
    inline Object* Object_1_Instantiate_5(Object* original, MethodInfo* method) { return Object_1_Instantiate_5__RAW(nullptr, original, method); }
    inline GameObject* Object_1_Instantiate_10(GameObject* original, MethodInfo* method) { return Object_1_Instantiate_10__RAW(nullptr, original, method); }
    inline Vector3 Vector3_Lerp(Vector3 a, Vector3 b, float t, MethodInfo* method) { return Vector3_Lerp__RAW(nullptr, a, b, t, method); }
    inline AttackResult* MoleMole_AttackResult_CreateElementAttack(ElementType__Enum elementType, float elementDurability, MethodInfo* method) { return MoleMole_AttackResult_CreateElementAttack__RAW(nullptr, elementType, elementDurability, method); }
    inline float Mathf_Lerp(float a, float b, float t, MethodInfo* method) { return Mathf_Lerp__RAW(nullptr, a, b, t, method); }
    inline float Input_GetAxis(String* axisName, MethodInfo* method) { return Input_GetAxis__RAW(nullptr, axisName, method); }
    inline void Object_1_Destroy_1(Object_1* obj, MethodInfo* method) { Object_1_Destroy_1__RAW(nullptr, obj, method); }
    inline Texture2D* NativeGallery_LoadImageAtPath(String* imagePath, int32_t maxSize, bool markTextureNonReadable, bool generateMipmaps, bool linearColorSpace, MethodInfo* method) { return NativeGallery_LoadImageAtPath__RAW(nullptr, imagePath, maxSize, markTextureNonReadable, generateMipmaps, linearColorSpace, method); }
    inline float Miscs_CalcCurrentGroundWaterHeight(float x, float z, MethodInfo* method) { return Miscs_CalcCurrentGroundWaterHeight__RAW(nullptr, x, z, method); }
    inline float Miscs_CalcCurrentGroundHeight(float x, float z, MethodInfo* method) { return Miscs_CalcCurrentGroundHeight__RAW(nullptr, x, z, method); }
    inline float Miscs_CalcCurrentGroundHeight_1(float x, float z, float rayStartHeight, float rayDetectLength, int32_t layer, MethodInfo* method) { return Miscs_CalcCurrentGroundHeight_1__RAW(nullptr, x, z, rayStartHeight, rayDetectLength, layer, method); }
    inline Vector3 Miscs_CalcCurrentGroundNorm(Vector3 pos, MethodInfo* method) { return Miscs_CalcCurrentGroundNorm__RAW(nullptr, pos, method); }
    inline Vector3 Miscs_GenWorldPos(Vector2 levelMapPos, MethodInfo* method) { return Miscs_GenWorldPos__RAW(nullptr, levelMapPos, method); }
    inline Vector2 Miscs_GenLevelPos_1(Vector3 worldPos, MethodInfo* method) { return Miscs_GenLevelPos_1__RAW(nullptr, worldPos, method); }
    inline int32_t Miscs_GetSceneGroundLayerMask(MethodInfo* method) { return Miscs_GetSceneGroundLayerMask__RAW(nullptr, method); }
    inline Vector3 WorldShiftManager_GetAbsolutePosition(Vector3 pos, MethodInfo* method) { return WorldShiftManager_GetAbsolutePosition__RAW(nullptr, pos, method); }
    inline Vector3 WorldShiftManager_GetRelativePosition(Vector3 pos, MethodInfo* method) { return WorldShiftManager_GetRelativePosition__RAW(nullptr, pos, method); }
    inline Vector3 ActorUtils_GetAvatarPos(MethodInfo* method) { return ActorUtils_GetAvatarPos__RAW(nullptr, method); }
    inline void ActorUtils_SetAvatarPos(Vector3 pos, MethodInfo* method) { ActorUtils_SetAvatarPos__RAW(nullptr, pos, method); }
    inline void ActorUtils_SyncAvatarMotion(int32_t state, MethodInfo* method) { ActorUtils_SyncAvatarMotion__RAW(nullptr, state, method); }
    inline Notify Notify_CreateNotify_1(MoleMole_NotifyTypes__Enum type, Object* body, MethodInfo* method) { return Notify_CreateNotify_1__RAW(nullptr, type, body, method); }
    inline float MoleMole_SafeFloat_get_Value(SafeFloat safeFloat, MethodInfo* method) { return MoleMole_SafeFloat_get_Value__RAW(nullptr, safeFloat, method); }
    inline SafeFloat MoleMole_SafeFloat_set_Value(float value, MethodInfo* method) { return MoleMole_SafeFloat_set_Value__RAW(nullptr, value, method); }
    inline Bounds Utils_4_GetBounds(GameObject* go, MethodInfo* method) { return Utils_4_GetBounds__RAW(nullptr, go, method); }
    inline uint64_t MoleMole_TimeUtil_get_NowTimeStamp(MethodInfo* method) { return MoleMole_TimeUtil_get_NowTimeStamp__RAW(nullptr, method); }
    inline void RenderSettings_set_fog(bool value, MethodInfo* method) { RenderSettings_set_fog__RAW(nullptr, value, method); }
    inline int32_t Application_get_targetFrameRate(MethodInfo* method) { return Application_get_targetFrameRate__RAW(nullptr, method); }
    inline void Application_set_targetFrameRate(int32_t value, MethodInfo* method) { Application_set_targetFrameRate__RAW(nullptr, value, method); }
    inline bool RectTransformUtility_ScreenPointToLocalPointInRectangle(void* rect, Vector2 screenPoint, void* cam, Vector2* localPoint, MethodInfo* method) { return RectTransformUtility_ScreenPointToLocalPointInRectangle__RAW(nullptr, rect, screenPoint, cam, localPoint, method); }
    inline float Vector3_Distance(Vector3 a, Vector3 b, MethodInfo* method) { return Vector3_Distance__RAW(nullptr, a, b, method); }
    inline float Vector2_Distance(Vector2 a, Vector2 b, MethodInfo* method) { return Vector2_Distance__RAW(nullptr, a, b, method); }
    inline void Cursor_set_visible(bool value, MethodInfo* method) { Cursor_set_visible__RAW(nullptr, value, method); }
    inline void Cursor_set_lockState(CursorLockMode__Enum value, MethodInfo* method) { Cursor_set_lockState__RAW(nullptr, value, method); }
    inline bool Cursor_get_visible(MethodInfo* method) { return Cursor_get_visible__RAW(nullptr, method); }
    inline float Time_get_timeScale(MethodInfo* method) { return Time_get_timeScale__RAW(nullptr, method); }
    inline void Time_set_timeScale(float value, MethodInfo* method) { Time_set_timeScale__RAW(nullptr, value, method); }
    inline float Time_get_deltaTime(MethodInfo* method) { return Time_get_deltaTime__RAW(nullptr, method); }
    inline Camera* Camera_get_main(MethodInfo* method) { return Camera_get_main__RAW(nullptr, method); }
    inline int32_t Screen_get_width(MethodInfo* method) { return Screen_get_width__RAW(nullptr, method); }
    inline int32_t Screen_get_height(MethodInfo* method) { return Screen_get_height__RAW(nullptr, method); }
    inline Vector3 Quaternion_ToEulerAngles(Quaternion rotation, MethodInfo* method) { return Quaternion_ToEulerAngles__RAW(nullptr, rotation, method); }
    inline void* Singleton_GetInstance(MethodInfo* method) { return Singleton_GetInstance__RAW(nullptr, method); }
    inline String* Marshal_PtrToStringUni(void* ptr, MethodInfo* method) { return Marshal_PtrToStringUni__RAW(nullptr, ptr, method); }
    inline bool MoleMole_UIManager_IsPS4Layout(MethodInfo* method) { return MoleMole_UIManager_IsPS4Layout__RAW(nullptr, method); }
    inline uint64_t MoleMole_TimeUtil_get_LocalNowMsTimeStamp(MethodInfo* method) { return MoleMole_TimeUtil_get_LocalNowMsTimeStamp__RAW(nullptr, method); }
    inline /*MoleMole_GeneralDialogContext*/void* MoleMole_UIUtil_TryShowSimpleGeneralDialog_1(String* title, String* content, /*Action*/void* buttonCallback, MethodInfo* method) { return MoleMole_UIUtil_TryShowSimpleGeneralDialog_1__RAW(nullptr, title, content, buttonCallback, method); }
    inline SystemLanguage__Enum Application_get_systemLanguage(MethodInfo* method) { return Application_get_systemLanguage__RAW(nullptr, method); }
    inline bool Application_get_IsFocused(MethodInfo* method) { return Application_get_IsFocused__RAW(nullptr, method); }
    inline String* Extension_GetCurrentStateName(Animator* animator, int32_t layer, AnimatorController* animCont, MethodInfo* method) { return Extension_GetCurrentStateName__RAW(nullptr, animator, layer, animCont, method); }
    inline /*SECTR_StreamingProfile*/ void* SECTR_Streaming_get_CurrentProfile(MethodInfo* method) { return SECTR_Streaming_get_CurrentProfile__RAW(nullptr, method); }
    inline /*SECTR_SceneSplitterConfig*/ void* SECTR_Streaming_get_SceneSplitterConfig(MethodInfo* method) { return SECTR_Streaming_get_SceneSplitterConfig__RAW(nullptr, method); }
    inline Vector3 QualitySettings_get_shadowCascade4Split(MethodInfo* method) { return QualitySettings_get_shadowCascade4Split__RAW(nullptr, method); }
}
