// generated by tools/gen_types.py from the 2.8 dump - types the 3.3 feature code needs that the upstream 2.8 il2cpp-types.h lacks
// regenerate: python tools/gen_types.py --ver 28 --auto [--build-log <msbuild log>] [--types ...]   (after transplant.py; do not edit by hand)
// requested complete: GeneralDialogContext_GeneralDialogType, SystemLanguage, UIShowPriority, ConfigScenePoint__Class, GadgetType_Enum, PlayerLoginReq, Proto_SceneEntityInfo, Proto_SceneEntityAppearNotify, Proto_SceneAvatarInfo, Proto_SceneMonsterInfo, Proto_SceneNpcInfo, Proto_SceneGadgetInfo, Proto_CheckAddItemExceedLimitNotify, EmoSync, miHoYoEmotion_BaseShape, MoleMole_EquipLevelUpDialogContext, InLevelMainPageContext_DoTeamCountDown_Iterator, MonoTeamBtn, AnimatorController, Config_AvatarSkillDepotExcelConfig, RealScenePointType
// requested declared: Byte, GadgetModule, Int32, LevelModule, Material, Proto_PlayerLuaShellNotify, Proto_WindSeedClientNotify, RSA, info
// provenance per type: "2.8 dump" (fields/offsets from the dump, names aligned with appdata-33 where readable),
//   "FALLBACK appdata-33" (NOT located in the dump: compile aid only, never dereference on this version),
//   forward declarations for pointer-only use. MISSING = a 3.3 field/member the 2.8 type does not have.
#pragma once

#if !defined(_GHIDRA_) && !defined(_IDA_)
namespace app {
#endif

    // ---- forward declarations (pointer-only use) ----
    struct Action_1_AnimatorController_AnimatorController_CrossFadeInfo_;
    struct Action_1_ConfigScenePoint_;
    struct Action_1_NDGNOAAMIEM_;
    struct Animation;
    struct AnimationPhaseArray;
    struct AnimatorControllerParameter;
    struct AnimatorController__Class;
    struct BPJOPAGFOJM;
    struct BaseDialogContext__Class;
    struct BaseEmoAnimation;
    struct Byte;
    struct CanvasGroup;
    struct Config_AvatarSkillDepotExcelConfig__Class;
    struct Config_ProudSkillOpenConfig;
    struct Dictionary_2_System_Int32_CrossFadeByParameterConfig___;
    struct Dictionary_2_System_Int32_List_Int3__;
    struct Dictionary_2_System_Int32_UnityEngine_AnimatorControllerParameterType_;
    struct Dictionary_2_System_String_System_Boolean_;
    struct Dictionary_2_System_String_miHoYoEmotion_BaseShape_;
    struct Dictionary_2_UnityEngine_StateMachineBehaviour_AnimatorController_AnimatorController_StateMachineBehaviourInfo_;
    struct EmoMgrUser__Class;
    struct EmoStateManager;
    struct EmoSync_EmoSync_EmoParamCache;
    struct EmoSync__Class;
    struct EmotionSetData;
    struct GadgetModule;
    struct Google_Protobuf_Collections_MapField_2_System_UInt32_System_UInt32_;
    struct Google_Protobuf_Collections_RepeatedMessageField_1_BPJOPAGFOJM___Class;
    struct Google_Protobuf_Collections_RepeatedMessageField_1_HCJJIALBHBC___Class;
    struct Google_Protobuf_Collections_RepeatedMessageField_1_IHPBNLCBEDB___Class;
    struct Google_Protobuf_Collections_RepeatedMessageField_1_IJNEELNIOCB___Class;
    struct Google_Protobuf_Collections_RepeatedMessageField_1_KMKPNLHPNPM___Class;
    struct Google_Protobuf_Collections_RepeatedMessageField_1_MBDPBDMKHIH___Class;
    struct Google_Protobuf_Collections_RepeatedMessageField_1_NCJOAKEEJDP___Class;
    struct Google_Protobuf_Collections_RepeatedMessageField_1_NDCJOMLDDFB___Class;
    struct Google_Protobuf_Collections_RepeatedMessageField_1_Proto_SceneEntityInfo___Class;
    struct Google_Protobuf_Collections_RepeatedPrimitiveField_1_System_String___Class;
    struct Google_Protobuf_Collections_RepeatedPrimitiveField_1_System_UInt32___Class;
    struct HCJJIALBHBC;
    struct IHPBNLCBEDB;
    struct IJNEELNIOCB;
    struct ISerializationCallbackReceiver;
    struct InLevelMainPageContext_DoTeamCountDown_Iterator__Class;
    struct Int32;
    struct KMKPNLHPNPM;
    struct LevelModule;
    struct List_1_BPJOPAGFOJM___Class;
    struct List_1_HCJJIALBHBC___Class;
    struct List_1_IHPBNLCBEDB___Class;
    struct List_1_IJNEELNIOCB___Class;
    struct List_1_KMKPNLHPNPM___Class;
    struct List_1_MBDPBDMKHIH___Class;
    struct List_1_MKPHEKGEAJK___Class;
    struct List_1_NCJOAKEEJDP___Class;
    struct List_1_NDCJOMLDDFB___Class;
    struct List_1_Proto_SceneEntityInfo___Class;
    struct List_1_System_String___Class;
    struct List_1_miHoYoEmotion_BaseShape___Class;
    struct List_1_motion4hi_CrossFadeByParameterConfig___Class;
    struct List_1_motion4hi_ParamConstraint___Class;
    struct MBDPBDMKHIH;
    struct Material;
    struct MessageBase_1__Class;
    struct MoleMole_AvatarDataItem;
    struct MoleMole_BagItem;
    struct MoleMole_EditableString;
    struct MoleMole_EquipLevelUpDialogContext__Class;
    struct MoleMole_UIUtil_MoleMole_UIUtil_LevelUpItemQueue;
    struct MonoAvatarPropertyItem;
    struct MonoBattleBtn;
    struct MonoColorExchange;
    struct MonoEquipLevelUpDialog;
    struct MonoInLevelBuffInfo;
    struct MonoLongPressButton;
    struct MonoPrefabPlugin;
    struct MonoSpriteProxy__Class;
    struct MonoTeamBtn__Class;
    struct MonoUIEffect;
    struct NCJOAKEEJDP;
    struct NDCJOMLDDFB;
    struct PlayerLoginReq__Class;
    struct Proto_AvatarExcelInfo;
    struct Proto_CheckAddItemExceedLimitNotify__Class;
    struct Proto_CurVehicleInfo;
    struct Proto_EntityAuthorityInfo;
    struct Proto_EntityClientData;
    struct Proto_GadgetPlayInfo;
    struct Proto_MonsterRoute;
    struct Proto_MotionInfo;
    struct Proto_PlatformInfo;
    struct Proto_PlayerLuaShellNotify;
    struct Proto_SceneAvatarInfo__Class;
    struct Proto_SceneEntityAppearNotify__Class;
    struct Proto_SceneEntityInfo__Class;
    struct Proto_SceneGadgetInfo__Class;
    struct Proto_SceneMonsterInfo__Class;
    struct Proto_SceneNpcInfo__Class;
    struct Proto_SceneWeaponInfo;
    struct Proto_WindSeedClientNotify;
    struct RSA;
    struct SimpleText;
    struct SmoothMask;
    struct info;
    struct miHoYoEmotion_BaseShape__Class;
    struct motion4hi_CrossFadeByParameterConfig;
    struct motion4hi_ParamConstraint;

    // ---- definitions (dependency order) ----
    // GeneralDialogContext_GeneralDialogType__Enum: 2.8 dump IIMLFCEABPO.ELNMJJBPPMJ (2 members)
    enum class GeneralDialogContext_GeneralDialogType__Enum : int32_t {
        DOUBLE_BUTTON = 0x00000000,
        SINGLE_BUTTON = 0x00000001,
    };

    // SystemLanguage__Enum: 2.8 dump UnityEngine.SystemLanguage (43 members)
    enum class SystemLanguage__Enum : int32_t {
        Afrikaans = 0x00000000,
        Arabic = 0x00000001,
        Basque = 0x00000002,
        Belarusian = 0x00000003,
        Bulgarian = 0x00000004,
        Catalan = 0x00000005,
        Chinese = 0x00000006,
        Czech = 0x00000007,
        Danish = 0x00000008,
        Dutch = 0x00000009,
        English = 0x0000000A,
        Estonian = 0x0000000B,
        Faroese = 0x0000000C,
        Finnish = 0x0000000D,
        French = 0x0000000E,
        German = 0x0000000F,
        Greek = 0x00000010,
        Hebrew = 0x00000011,
        Icelandic = 0x00000013,
        Indonesian = 0x00000014,
        Italian = 0x00000015,
        Japanese = 0x00000016,
        Korean = 0x00000017,
        Latvian = 0x00000018,
        Lithuanian = 0x00000019,
        Norwegian = 0x0000001A,
        Polish = 0x0000001B,
        Portuguese = 0x0000001C,
        Romanian = 0x0000001D,
        Russian = 0x0000001E,
        SerboCroatian = 0x0000001F,
        Slovak = 0x00000020,
        Slovenian = 0x00000021,
        Spanish = 0x00000022,
        Swedish = 0x00000023,
        Thai = 0x00000024,
        Turkish = 0x00000025,
        Ukrainian = 0x00000026,
        Vietnamese = 0x00000027,
        ChineseSimplified = 0x00000028,
        ChineseTraditional = 0x00000029,
        Unknown = 0x0000002A,
        Hungarian = 0x00000012,
    };

    // UIShowPriority__Enum: 2.8 dump NDCPIENECJI (7 members)
    enum class UIShowPriority__Enum : int32_t {
        None = 0x00000000,
        Normal = 0x00000001,
        Pop = 0x00000002,
        Cutscene = 0x00000003,
        Init = 0x00000004,
        Loading = 0x00000005,
        Error = 0x00000006,
    };

    // ConfigScenePoint__Class / __VTable / __StaticFields: 2.8 dump KNDJGAIHNPM (13 vtable slots, obfuscated names taken by slot from appdata-33)
    struct ConfigScenePoint__VTable {
        VirtualInvokeData _slot0;
        VirtualInvokeData _slot1;
        VirtualInvokeData _slot2;
        VirtualInvokeData _slot3;
        VirtualInvokeData _slot4;
        VirtualInvokeData _slot5;
        VirtualInvokeData get_pointType;  // 2.8: HCEDCFBANJL (name by slot from appdata-33 ConfigScenePoint__VTable: 2 anchors)
        VirtualInvokeData ObjectContentHashOnto;
        VirtualInvokeData ForeachRefTypeMember;  // 2.8: EPIMHCIDEND (name by slot from appdata-33 ConfigScenePoint__VTable: 2 anchors)
        VirtualInvokeData Clone;  // 2.8: OKGHAMLDGJA (name by slot from appdata-33 ConfigScenePoint__VTable: 2 anchors)
        VirtualInvokeData GetHashNum;  // 2.8: BAHMLKLBKHC (name by slot from appdata-33 ConfigScenePoint__VTable: 2 anchors)
        VirtualInvokeData InitEmpty;
        VirtualInvokeData FromBinary;  // 2.8: DPAKJOBJKOD (name by slot from appdata-33 ConfigScenePoint__VTable: 2 anchors)
    };
    struct ConfigScenePoint__StaticFields {
        struct Action_1_ConfigScenePoint_* HLJALAICPJF; // 0x0
        struct Action_1_ConfigScenePoint_* CJIMFGINABB; // 0x8
    };
    struct ConfigScenePoint__Class {
        Il2CppClass_0 _0;
        Il2CppRuntimeInterfaceOffsetPair* interfaceOffsets;
        struct ConfigScenePoint__StaticFields* static_fields;
        const Il2CppRGCTXData* rgctx_data;
        Il2CppClass_1 _1;
        struct ConfigScenePoint__VTable vtable;
    };

    // GadgetType_Enum: 2.8 dump BBILONKMMBP (4 members, matched by member names)
    enum class GadgetType_Enum : int32_t {
        GADGET_NONE = 0x00000000,
        GADGET_WORLD_CHECT = 0x00000001,
        GADGET_DUNGEON_SECRET_CHEST = 0x00000002,
        GADGET_DUNGEON_PASS_CHEST = 0x00000003,
    };

    // PlayerLoginReq: wrapper for the existing PlayerLoginReq__Fields of this header (the header's own wrapper has an obfuscated name)
    struct PlayerLoginReq {
        struct PlayerLoginReq__Class* klass;
        MonitorData* monitor;
        struct PlayerLoginReq__Fields fields;
    };

    // MessageBase_1: wrapper for the existing MessageBase_1__Fields of this header (the header's own wrapper has an obfuscated name)
    struct MessageBase_1 {
        struct MessageBase_1__Class* klass;
        MonitorData* monitor;
        struct MessageBase_1__Fields fields;
    };

    // Proto_ProtEntityType__Enum: 2.8 dump FAEAIOJLBOD (15 members, 15 names from appdata-33)
    enum class Proto_ProtEntityType__Enum : int32_t {
        ProtEntityNone = 0x00000000,  // 2.8: IDFONEGLPDJ (name from appdata-33, same value)
        ProtEntityAvatar = 0x00000001,  // 2.8: KJIFFHNLEIC (name from appdata-33, same value)
        ProtEntityMonster = 0x00000002,  // 2.8: LKOCGDGECJP (name from appdata-33, same value)
        ProtEntityNpc = 0x00000003,  // 2.8: FBPNBPENCAG (name from appdata-33, same value)
        ProtEntityGadget = 0x00000004,  // 2.8: BIELHGFNNJC (name from appdata-33, same value)
        ProtEntityRegion = 0x00000005,  // 2.8: HPFHHHALAHH (name from appdata-33, same value)
        ProtEntityWeapon = 0x00000006,  // 2.8: BHKHOONALNP (name from appdata-33, same value)
        ProtEntityWeather = 0x00000007,  // 2.8: IIEKPPKIDOD (name from appdata-33, same value)
        ProtEntityScene = 0x00000008,  // 2.8: LKPBJFKKBAO (name from appdata-33, same value)
        ProtEntityTeam = 0x00000009,  // 2.8: LAKFHDCNOEK (name from appdata-33, same value)
        ProtEntityMassiveEntity = 0x0000000A,  // 2.8: NAMOCKPFIEM (name from appdata-33, same value)
        ProtEntityMpLevel = 0x0000000B,  // 2.8: LBLOJDILILF (name from appdata-33, same value)
        ProtEntityPlayTeamEntity = 0x0000000C,  // 2.8: HIGFFLLDMLK (name from appdata-33, same value)
        ProtEntityEyePoint = 0x0000000D,  // 2.8: ILGPBKDNNCI (name from appdata-33, same value)
        ProtEntityMax = 0x0000000E,  // 2.8: DFCIJFFGOJM (name from appdata-33, same value)
    };

    // IHPBNLCBEDB__Array: array of IHPBNLCBEDB
    struct IHPBNLCBEDB__Array {
        void* klass;
        MonitorData* monitor;
        Il2CppArrayBounds* bounds;
        il2cpp_array_size_t max_length;
        struct IHPBNLCBEDB* vector[32];
    };

    // List_1_IHPBNLCBEDB_: System.Collections.Generic.List<IHPBNLCBEDB> (standard layout)
    struct __declspec(align(8)) List_1_IHPBNLCBEDB___Fields {
        struct IHPBNLCBEDB__Array* _items;
        int32_t _size;
        int32_t _version;
    };
    struct List_1_IHPBNLCBEDB_ {
        struct List_1_IHPBNLCBEDB___Class* klass;
        MonitorData* monitor;
        struct List_1_IHPBNLCBEDB___Fields fields;
    };

    // Google_Protobuf_Collections_RepeatedMessageField_1_IHPBNLCBEDB_: 2.8 dump OLAOHCJGBLN<T> with T=IHPBNLCBEDB, names from appdata-33 Google_Protobuf_Collections_RepeatedMessageField_1_Proto_SceneEntityInfo_
    struct __declspec(align(8)) Google_Protobuf_Collections_RepeatedMessageField_1_IHPBNLCBEDB___Fields {
        struct List_1_IHPBNLCBEDB_* values; // (generic definition: dump order, natural layout)  // 2.8: NEJEPNGFFBJ
        bool _isInPool; // (generic definition: dump order, natural layout)  // 2.8: DFHMMNONANE
        int32_t _count; // (generic definition: dump order, natural layout)  // 2.8: OBHIGAFBKOL
    };
    struct Google_Protobuf_Collections_RepeatedMessageField_1_IHPBNLCBEDB_ {
        struct Google_Protobuf_Collections_RepeatedMessageField_1_IHPBNLCBEDB___Class* klass;
        MonitorData* monitor;
        struct Google_Protobuf_Collections_RepeatedMessageField_1_IHPBNLCBEDB___Fields fields;
    };

    // NCJOAKEEJDP__Array: array of NCJOAKEEJDP
    struct NCJOAKEEJDP__Array {
        void* klass;
        MonitorData* monitor;
        Il2CppArrayBounds* bounds;
        il2cpp_array_size_t max_length;
        struct NCJOAKEEJDP* vector[32];
    };

    // List_1_NCJOAKEEJDP_: System.Collections.Generic.List<NCJOAKEEJDP> (standard layout)
    struct __declspec(align(8)) List_1_NCJOAKEEJDP___Fields {
        struct NCJOAKEEJDP__Array* _items;
        int32_t _size;
        int32_t _version;
    };
    struct List_1_NCJOAKEEJDP_ {
        struct List_1_NCJOAKEEJDP___Class* klass;
        MonitorData* monitor;
        struct List_1_NCJOAKEEJDP___Fields fields;
    };

    // Google_Protobuf_Collections_RepeatedMessageField_1_NCJOAKEEJDP_: 2.8 dump OLAOHCJGBLN<T> with T=NCJOAKEEJDP, names from appdata-33 Google_Protobuf_Collections_RepeatedMessageField_1_Proto_SceneEntityInfo_
    struct __declspec(align(8)) Google_Protobuf_Collections_RepeatedMessageField_1_NCJOAKEEJDP___Fields {
        struct List_1_NCJOAKEEJDP_* values; // (generic definition: dump order, natural layout)  // 2.8: NEJEPNGFFBJ
        bool _isInPool; // (generic definition: dump order, natural layout)  // 2.8: DFHMMNONANE
        int32_t _count; // (generic definition: dump order, natural layout)  // 2.8: OBHIGAFBKOL
    };
    struct Google_Protobuf_Collections_RepeatedMessageField_1_NCJOAKEEJDP_ {
        struct Google_Protobuf_Collections_RepeatedMessageField_1_NCJOAKEEJDP___Class* klass;
        MonitorData* monitor;
        struct Google_Protobuf_Collections_RepeatedMessageField_1_NCJOAKEEJDP___Fields fields;
    };

    // NDCJOMLDDFB__Array: array of NDCJOMLDDFB
    struct NDCJOMLDDFB__Array {
        void* klass;
        MonitorData* monitor;
        Il2CppArrayBounds* bounds;
        il2cpp_array_size_t max_length;
        struct NDCJOMLDDFB* vector[32];
    };

    // List_1_NDCJOMLDDFB_: System.Collections.Generic.List<NDCJOMLDDFB> (standard layout)
    struct __declspec(align(8)) List_1_NDCJOMLDDFB___Fields {
        struct NDCJOMLDDFB__Array* _items;
        int32_t _size;
        int32_t _version;
    };
    struct List_1_NDCJOMLDDFB_ {
        struct List_1_NDCJOMLDDFB___Class* klass;
        MonitorData* monitor;
        struct List_1_NDCJOMLDDFB___Fields fields;
    };

    // Google_Protobuf_Collections_RepeatedMessageField_1_NDCJOMLDDFB_: 2.8 dump OLAOHCJGBLN<T> with T=NDCJOMLDDFB, names from appdata-33 Google_Protobuf_Collections_RepeatedMessageField_1_Proto_SceneEntityInfo_
    struct __declspec(align(8)) Google_Protobuf_Collections_RepeatedMessageField_1_NDCJOMLDDFB___Fields {
        struct List_1_NDCJOMLDDFB_* values; // (generic definition: dump order, natural layout)  // 2.8: NEJEPNGFFBJ
        bool _isInPool; // (generic definition: dump order, natural layout)  // 2.8: DFHMMNONANE
        int32_t _count; // (generic definition: dump order, natural layout)  // 2.8: OBHIGAFBKOL
    };
    struct Google_Protobuf_Collections_RepeatedMessageField_1_NDCJOMLDDFB_ {
        struct Google_Protobuf_Collections_RepeatedMessageField_1_NDCJOMLDDFB___Class* klass;
        MonitorData* monitor;
        struct Google_Protobuf_Collections_RepeatedMessageField_1_NDCJOMLDDFB___Fields fields;
    };

    // IJNEELNIOCB__Array: array of IJNEELNIOCB
    struct IJNEELNIOCB__Array {
        void* klass;
        MonitorData* monitor;
        Il2CppArrayBounds* bounds;
        il2cpp_array_size_t max_length;
        struct IJNEELNIOCB* vector[32];
    };

    // List_1_IJNEELNIOCB_: System.Collections.Generic.List<IJNEELNIOCB> (standard layout)
    struct __declspec(align(8)) List_1_IJNEELNIOCB___Fields {
        struct IJNEELNIOCB__Array* _items;
        int32_t _size;
        int32_t _version;
    };
    struct List_1_IJNEELNIOCB_ {
        struct List_1_IJNEELNIOCB___Class* klass;
        MonitorData* monitor;
        struct List_1_IJNEELNIOCB___Fields fields;
    };

    // Google_Protobuf_Collections_RepeatedMessageField_1_IJNEELNIOCB_: 2.8 dump OLAOHCJGBLN<T> with T=IJNEELNIOCB, names from appdata-33 Google_Protobuf_Collections_RepeatedMessageField_1_Proto_SceneEntityInfo_
    struct __declspec(align(8)) Google_Protobuf_Collections_RepeatedMessageField_1_IJNEELNIOCB___Fields {
        struct List_1_IJNEELNIOCB_* values; // (generic definition: dump order, natural layout)  // 2.8: NEJEPNGFFBJ
        bool _isInPool; // (generic definition: dump order, natural layout)  // 2.8: DFHMMNONANE
        int32_t _count; // (generic definition: dump order, natural layout)  // 2.8: OBHIGAFBKOL
    };
    struct Google_Protobuf_Collections_RepeatedMessageField_1_IJNEELNIOCB_ {
        struct Google_Protobuf_Collections_RepeatedMessageField_1_IJNEELNIOCB___Class* klass;
        MonitorData* monitor;
        struct Google_Protobuf_Collections_RepeatedMessageField_1_IJNEELNIOCB___Fields fields;
    };

    // Google_Protobuf_Collections_RepeatedPrimitiveField_1_System_String_: 2.8 dump IAPEAPLCFJO<T> with T=string
    struct __declspec(align(8)) Google_Protobuf_Collections_RepeatedPrimitiveField_1_System_String___Fields {
        struct String__Array* FPKGJJGNALL; // (generic definition: dump order, natural layout)
        int32_t IIKODCNGOIM; // (generic definition: dump order, natural layout)
    };
    struct Google_Protobuf_Collections_RepeatedPrimitiveField_1_System_String_ {
        struct Google_Protobuf_Collections_RepeatedPrimitiveField_1_System_String___Class* klass;
        MonitorData* monitor;
        struct Google_Protobuf_Collections_RepeatedPrimitiveField_1_System_String___Fields fields;
    };

    // MBDPBDMKHIH__Array: array of MBDPBDMKHIH
    struct MBDPBDMKHIH__Array {
        void* klass;
        MonitorData* monitor;
        Il2CppArrayBounds* bounds;
        il2cpp_array_size_t max_length;
        struct MBDPBDMKHIH* vector[32];
    };

    // List_1_MBDPBDMKHIH_: System.Collections.Generic.List<MBDPBDMKHIH> (standard layout)
    struct __declspec(align(8)) List_1_MBDPBDMKHIH___Fields {
        struct MBDPBDMKHIH__Array* _items;
        int32_t _size;
        int32_t _version;
    };
    struct List_1_MBDPBDMKHIH_ {
        struct List_1_MBDPBDMKHIH___Class* klass;
        MonitorData* monitor;
        struct List_1_MBDPBDMKHIH___Fields fields;
    };

    // Google_Protobuf_Collections_RepeatedMessageField_1_MBDPBDMKHIH_: 2.8 dump OLAOHCJGBLN<T> with T=MBDPBDMKHIH, names from appdata-33 Google_Protobuf_Collections_RepeatedMessageField_1_Proto_SceneEntityInfo_
    struct __declspec(align(8)) Google_Protobuf_Collections_RepeatedMessageField_1_MBDPBDMKHIH___Fields {
        struct List_1_MBDPBDMKHIH_* values; // (generic definition: dump order, natural layout)  // 2.8: NEJEPNGFFBJ
        bool _isInPool; // (generic definition: dump order, natural layout)  // 2.8: DFHMMNONANE
        int32_t _count; // (generic definition: dump order, natural layout)  // 2.8: OBHIGAFBKOL
    };
    struct Google_Protobuf_Collections_RepeatedMessageField_1_MBDPBDMKHIH_ {
        struct Google_Protobuf_Collections_RepeatedMessageField_1_MBDPBDMKHIH___Class* klass;
        MonitorData* monitor;
        struct Google_Protobuf_Collections_RepeatedMessageField_1_MBDPBDMKHIH___Fields fields;
    };

    // Proto_SceneEntityInfo_Proto_SceneEntityInfo_EntityOneofCase__Enum: 2.8 dump MNNCKCHJAJK.OEOINBNCKPD (5 members)
    enum class Proto_SceneEntityInfo_Proto_SceneEntityInfo_EntityOneofCase__Enum : int32_t {
        None = 0x00000000,
        Avatar = 0x0000000A,
        Monster = 0x0000000B,
        Npc = 0x0000000C,
        Gadget = 0x0000000D,
    };

    // Proto_SceneEntityInfo: 2.8 dump MNNCKCHJAJK, field names from appdata-33 Proto_SceneEntityInfo, 1 padding member(s)
    struct __declspec(align(8)) Proto_SceneEntityInfo__Fields {
        struct MessageBase_1__Fields _;
        Proto_ProtEntityType__Enum entityType_; // 0x20  // 2.8: ODLAFDFGLOH  // type FAEAIOJLBOD__Enum in the dump
        uint32_t entityId_; // 0x24  // 2.8: ANEEDNLMJCG
        struct String* name_; // 0x28  // 2.8: GNAODEEIPNP
        struct Proto_MotionInfo* motionInfo_; // 0x30  // 2.8: MLMGGEEPNAD  // type MotionInfo in the dump
        struct Google_Protobuf_Collections_RepeatedMessageField_1_IHPBNLCBEDB_* propList_; // 0x38  // 2.8: OCBOLFBFKKH
        struct Google_Protobuf_Collections_RepeatedMessageField_1_NCJOAKEEJDP_* fightPropList_; // 0x40  // 2.8: CFODEKIELFC
        uint32_t lifeState_; // 0x48  // 2.8: IKIMNIGDFJL
        struct Google_Protobuf_Collections_RepeatedMessageField_1_NDCJOMLDDFB_* animatorParaList_; // 0x50  // 2.8: DMOEFODLMFP
        uint32_t lastMoveSceneTimeMs_; // 0x58  // 2.8: HGMCJAPBFOJ
        uint32_t lastMoveReliableSeq_; // 0x5C  // 2.8: JMNIKPJOMGC
        struct Proto_EntityClientData* entityClientData_; // 0x60  // 2.8: MBGPBBDPJHF  // type JFDEMFAEDNH in the dump
        struct Google_Protobuf_Collections_RepeatedMessageField_1_IJNEELNIOCB_* entityEnvironmentInfoList_; // 0x68  // 2.8: GLBDNAJJCOH
        struct Proto_EntityAuthorityInfo* entityAuthorityInfo_; // 0x70  // 2.8: HFOBANIILGI  // type FEAPBAEMOHH in the dump
        struct Google_Protobuf_Collections_RepeatedPrimitiveField_1_System_String_* tagList_; // 0x78  // 2.8: GLLKFGGIDBN
        struct Google_Protobuf_Collections_RepeatedMessageField_1_MBDPBDMKHIH_* serverBuffList_; // 0x80  // 2.8: ALLBOBELHDB
        struct Object* entity_; // 0x88  // 2.8: HEKOHADPHGH
        Proto_SceneEntityInfo_Proto_SceneEntityInfo_EntityOneofCase__Enum entityCase_; // 0x90  // 2.8: FILFPDDNCEL
    };
    struct Proto_SceneEntityInfo {
        struct Proto_SceneEntityInfo__Class* klass;
        MonitorData* monitor;
        struct Proto_SceneEntityInfo__Fields fields;
    };

    // Proto_VisionType__Enum: 2.8 dump DBPOBFKGNNE (20 members, 20 names from appdata-33)
    enum class Proto_VisionType__Enum : int32_t {
        VisionNone = 0x00000000,  // 2.8: GIBLNDCKJHP (name from appdata-33, same value)
        VisionMeet = 0x00000001,  // 2.8: MFLLHOJLHAP (name from appdata-33, same value)
        VisionReborn = 0x00000002,  // 2.8: AOBBPDCCCNP (name from appdata-33, same value)
        VisionReplace = 0x00000003,  // 2.8: MDACGGCJLGO (name from appdata-33, same value)
        VisionWaypointReborn = 0x00000004,  // 2.8: AKOGBBPEDAI (name from appdata-33, same value)
        VisionMiss = 0x00000005,  // 2.8: DLIHENDKBOB (name from appdata-33, same value)
        VisionDie = 0x00000006,  // 2.8: POJIAFOGELH (name from appdata-33, same value)
        VisionGatherEscape = 0x00000007,  // 2.8: INAHMLECCGH (name from appdata-33, same value)
        VisionRefresh = 0x00000008,  // 2.8: KCHDCIFEPEP (name from appdata-33, same value)
        VisionTransport = 0x00000009,  // 2.8: LIBGHEKEFGP (name from appdata-33, same value)
        VisionReplaceDie = 0x0000000A,  // 2.8: FNELEEBDFJB (name from appdata-33, same value)
        VisionReplaceNoNotify = 0x0000000B,  // 2.8: KPFLMAIAGKJ (name from appdata-33, same value)
        VisionBorn = 0x0000000C,  // 2.8: JINNEJLECEF (name from appdata-33, same value)
        VisionPickup = 0x0000000D,  // 2.8: PBOKLPOGJMO (name from appdata-33, same value)
        VisionRemove = 0x0000000E,  // 2.8: JLCNDAGGMLI (name from appdata-33, same value)
        VisionChangeCostume = 0x0000000F,  // 2.8: LDPJMALIJHO (name from appdata-33, same value)
        VisionFishRefresh = 0x00000010,  // 2.8: MFKHJPBDGOC (name from appdata-33, same value)
        VisionFishBigShock = 0x00000011,  // 2.8: HOHIBACDBKH (name from appdata-33, same value)
        VisionFishQteSucc = 0x00000012,  // 2.8: FKGEMNPNKGA (name from appdata-33, same value)
        CHECIGAOMEO = 0x00000013,  // 2.8: MDKOKDLFLMG (name from appdata-33, same value)
    };

    // Proto_SceneEntityInfo__Array: array of Proto_SceneEntityInfo
    struct Proto_SceneEntityInfo__Array {
        void* klass;
        MonitorData* monitor;
        Il2CppArrayBounds* bounds;
        il2cpp_array_size_t max_length;
        struct Proto_SceneEntityInfo* vector[32];
    };

    // List_1_Proto_SceneEntityInfo_: System.Collections.Generic.List<Proto_SceneEntityInfo> (standard layout)
    struct __declspec(align(8)) List_1_Proto_SceneEntityInfo___Fields {
        struct Proto_SceneEntityInfo__Array* _items;
        int32_t _size;
        int32_t _version;
    };
    struct List_1_Proto_SceneEntityInfo_ {
        struct List_1_Proto_SceneEntityInfo___Class* klass;
        MonitorData* monitor;
        struct List_1_Proto_SceneEntityInfo___Fields fields;
    };

    // Google_Protobuf_Collections_RepeatedMessageField_1_Proto_SceneEntityInfo_: 2.8 dump OLAOHCJGBLN<T> with T=Proto_SceneEntityInfo, names from appdata-33 Google_Protobuf_Collections_RepeatedMessageField_1_Proto_SceneEntityInfo_
    struct __declspec(align(8)) Google_Protobuf_Collections_RepeatedMessageField_1_Proto_SceneEntityInfo___Fields {
        struct List_1_Proto_SceneEntityInfo_* values; // (generic definition: dump order, natural layout)  // 2.8: NEJEPNGFFBJ
        bool _isInPool; // (generic definition: dump order, natural layout)  // 2.8: DFHMMNONANE
        int32_t _count; // (generic definition: dump order, natural layout)  // 2.8: OBHIGAFBKOL
    };
    struct Google_Protobuf_Collections_RepeatedMessageField_1_Proto_SceneEntityInfo_ {
        struct Google_Protobuf_Collections_RepeatedMessageField_1_Proto_SceneEntityInfo___Class* klass;
        MonitorData* monitor;
        struct Google_Protobuf_Collections_RepeatedMessageField_1_Proto_SceneEntityInfo___Fields fields;
    };

    // Proto_SceneEntityAppearNotify: 2.8 dump MDLIBPLBMAB, field names from appdata-33 Proto_SceneEntityAppearNotify, 1 padding member(s)
    struct __declspec(align(8)) Proto_SceneEntityAppearNotify__Fields {
        struct MessageBase_1__Fields _;
        Proto_VisionType__Enum appearType_; // 0x20  // 2.8: EEEIEJAIPEA  // type VisionType__Enum in the dump
        uint32_t param_; // 0x24  // 2.8: BBOGJKJIBDO
        struct Google_Protobuf_Collections_RepeatedMessageField_1_Proto_SceneEntityInfo_* entityList_; // 0x28  // 2.8: HFNKPGALPJF
    };
    struct Proto_SceneEntityAppearNotify {
        struct Proto_SceneEntityAppearNotify__Class* klass;
        MonitorData* monitor;
        struct Proto_SceneEntityAppearNotify__Fields fields;
    };

    // Google_Protobuf_Collections_RepeatedPrimitiveField_1_System_UInt32_: 2.8 dump IAPEAPLCFJO<T> with T=uint
    struct __declspec(align(8)) Google_Protobuf_Collections_RepeatedPrimitiveField_1_System_UInt32___Fields {
        struct UInt32__Array* FPKGJJGNALL; // (generic definition: dump order, natural layout)
        int32_t IIKODCNGOIM; // (generic definition: dump order, natural layout)
    };
    struct Google_Protobuf_Collections_RepeatedPrimitiveField_1_System_UInt32_ {
        struct Google_Protobuf_Collections_RepeatedPrimitiveField_1_System_UInt32___Class* klass;
        MonitorData* monitor;
        struct Google_Protobuf_Collections_RepeatedPrimitiveField_1_System_UInt32___Fields fields;
    };

    // KMKPNLHPNPM__Array: array of KMKPNLHPNPM
    struct KMKPNLHPNPM__Array {
        void* klass;
        MonitorData* monitor;
        Il2CppArrayBounds* bounds;
        il2cpp_array_size_t max_length;
        struct KMKPNLHPNPM* vector[32];
    };

    // List_1_KMKPNLHPNPM_: System.Collections.Generic.List<KMKPNLHPNPM> (standard layout)
    struct __declspec(align(8)) List_1_KMKPNLHPNPM___Fields {
        struct KMKPNLHPNPM__Array* _items;
        int32_t _size;
        int32_t _version;
    };
    struct List_1_KMKPNLHPNPM_ {
        struct List_1_KMKPNLHPNPM___Class* klass;
        MonitorData* monitor;
        struct List_1_KMKPNLHPNPM___Fields fields;
    };

    // Google_Protobuf_Collections_RepeatedMessageField_1_KMKPNLHPNPM_: 2.8 dump OLAOHCJGBLN<T> with T=KMKPNLHPNPM, names from appdata-33 Google_Protobuf_Collections_RepeatedMessageField_1_Proto_SceneEntityInfo_
    struct __declspec(align(8)) Google_Protobuf_Collections_RepeatedMessageField_1_KMKPNLHPNPM___Fields {
        struct List_1_KMKPNLHPNPM_* values; // (generic definition: dump order, natural layout)  // 2.8: NEJEPNGFFBJ
        bool _isInPool; // (generic definition: dump order, natural layout)  // 2.8: DFHMMNONANE
        int32_t _count; // (generic definition: dump order, natural layout)  // 2.8: OBHIGAFBKOL
    };
    struct Google_Protobuf_Collections_RepeatedMessageField_1_KMKPNLHPNPM_ {
        struct Google_Protobuf_Collections_RepeatedMessageField_1_KMKPNLHPNPM___Class* klass;
        MonitorData* monitor;
        struct Google_Protobuf_Collections_RepeatedMessageField_1_KMKPNLHPNPM___Fields fields;
    };

    // Proto_SceneAvatarInfo: 2.8 dump IPALCLOCNCI, field names from appdata-33 Proto_SceneAvatarInfo, 1 padding member(s)
    struct __declspec(align(8)) Proto_SceneAvatarInfo__Fields {
        struct MessageBase_1__Fields _;
        uint32_t uid_; // 0x20  // 2.8: HKAMKHGDDMF
        uint32_t avatarId_; // 0x24  // 2.8: IGKBAOHNAHP
        uint64_t guid_; // 0x28  // 2.8: JLABOMPFKJL
        uint32_t peerId_; // 0x30  // 2.8: AMCAKPDBOCK
        struct Google_Protobuf_Collections_RepeatedPrimitiveField_1_System_UInt32_* equipIdList_; // 0x38  // 2.8: HOAGPLANEDA
        uint32_t skillDepotId_; // 0x40  // 2.8: NHDOLDHGJDD
        struct Google_Protobuf_Collections_RepeatedPrimitiveField_1_System_UInt32_* talentIdList_; // 0x48  // 2.8: GBHJHHOKIHL
        struct Proto_SceneWeaponInfo* weapon_; // 0x50  // 2.8: MAEEJEEMIDB  // type HCJJIALBHBC in the dump
        struct Google_Protobuf_Collections_RepeatedMessageField_1_KMKPNLHPNPM_* reliquaryList_; // 0x58  // 2.8: DNHPBMIOFPG
        uint32_t coreProudSkillLevel_; // 0x60  // 2.8: IJJAMOMMGFL
        struct Google_Protobuf_Collections_RepeatedPrimitiveField_1_System_UInt32_* inherentProudSkillList_; // 0x68  // 2.8: JKCPLPAFHOG
        struct Google_Protobuf_Collections_MapField_2_System_UInt32_System_UInt32_* skillLevelMap_; // 0x70  // 2.8: KCKGDLIHILG
        struct Google_Protobuf_Collections_MapField_2_System_UInt32_System_UInt32_* proudSkillExtraLevelMap_; // 0x78  // 2.8: APIEDKHKNND
        struct Google_Protobuf_Collections_RepeatedMessageField_1_MBDPBDMKHIH_* serverBuffList_; // 0x80  // 2.8: ALLBOBELHDB
        struct Google_Protobuf_Collections_RepeatedPrimitiveField_1_System_UInt32_* teamResonanceList_; // 0x88  // 2.8: AINPFLJHPHA
        uint32_t wearingFlycloakId_; // 0x90  // 2.8: CICKHGGFPFG
        uint32_t bornTime_; // 0x94  // 2.8: POCNLPEOJMJ
        uint32_t costumeId_; // 0x98  // 2.8: GONBCDPBMHO
        struct Proto_CurVehicleInfo* curVehicleInfo_; // 0xA0  // 2.8: ODBNOLJKGHA  // type PEELPAACBBH in the dump
        struct Proto_AvatarExcelInfo* excelInfo_; // 0xA8  // 2.8: GMKHPHPAFIE  // type OLCKFOHLAKA in the dump
        uint32_t animHash_; // 0xB0  // 2.8: MHLMCCDNGNK
    };
    struct Proto_SceneAvatarInfo {
        struct Proto_SceneAvatarInfo__Class* klass;
        MonitorData* monitor;
        struct Proto_SceneAvatarInfo__Fields fields;
    };

    // HCJJIALBHBC__Array: array of HCJJIALBHBC
    struct HCJJIALBHBC__Array {
        void* klass;
        MonitorData* monitor;
        Il2CppArrayBounds* bounds;
        il2cpp_array_size_t max_length;
        struct HCJJIALBHBC* vector[32];
    };

    // List_1_HCJJIALBHBC_: System.Collections.Generic.List<HCJJIALBHBC> (standard layout)
    struct __declspec(align(8)) List_1_HCJJIALBHBC___Fields {
        struct HCJJIALBHBC__Array* _items;
        int32_t _size;
        int32_t _version;
    };
    struct List_1_HCJJIALBHBC_ {
        struct List_1_HCJJIALBHBC___Class* klass;
        MonitorData* monitor;
        struct List_1_HCJJIALBHBC___Fields fields;
    };

    // Google_Protobuf_Collections_RepeatedMessageField_1_HCJJIALBHBC_: 2.8 dump OLAOHCJGBLN<T> with T=HCJJIALBHBC, names from appdata-33 Google_Protobuf_Collections_RepeatedMessageField_1_Proto_SceneEntityInfo_
    struct __declspec(align(8)) Google_Protobuf_Collections_RepeatedMessageField_1_HCJJIALBHBC___Fields {
        struct List_1_HCJJIALBHBC_* values; // (generic definition: dump order, natural layout)  // 2.8: NEJEPNGFFBJ
        bool _isInPool; // (generic definition: dump order, natural layout)  // 2.8: DFHMMNONANE
        int32_t _count; // (generic definition: dump order, natural layout)  // 2.8: OBHIGAFBKOL
    };
    struct Google_Protobuf_Collections_RepeatedMessageField_1_HCJJIALBHBC_ {
        struct Google_Protobuf_Collections_RepeatedMessageField_1_HCJJIALBHBC___Class* klass;
        MonitorData* monitor;
        struct Google_Protobuf_Collections_RepeatedMessageField_1_HCJJIALBHBC___Fields fields;
    };

    // Proto_MonsterBornType__Enum: 2.8 dump BPPHCBIEOFP (3 members, 3 names from appdata-33)
    enum class Proto_MonsterBornType__Enum : int32_t {
        MonsterBornNone = 0x00000000,  // 2.8: KJJLNAMIPMF (name from appdata-33, same value)
        MonsterBornDefault = 0x00000001,  // 2.8: DOIBGBPOBKK (name from appdata-33, same value)
        MonsterBornRandom = 0x00000002,  // 2.8: NLHBLMAHCJD (name from appdata-33, same value)
    };

    // Proto_SceneMonsterInfo_Proto_SceneMonsterInfo_ContentOneofCase__Enum: 2.8 dump FKKAOBCHKGG.KMFJJOCHBNJ (2 members)
    enum class Proto_SceneMonsterInfo_Proto_SceneMonsterInfo_ContentOneofCase__Enum : int32_t {
        None = 0x00000000,
        FishInfo = 0x00000032,
    };

    // Proto_SceneMonsterInfo: 2.8 dump FKKAOBCHKGG, field names from appdata-33 Proto_SceneMonsterInfo, 1 padding member(s)
    struct __declspec(align(8)) Proto_SceneMonsterInfo__Fields {
        struct MessageBase_1__Fields _;
        uint32_t monsterId_; // 0x20  // 2.8: PAMOEJKKAFD
        uint32_t groupId_; // 0x24  // 2.8: EPHMEJIMHDI
        uint32_t configId_; // 0x28  // 2.8: KLMFMDJPFIE
        struct Google_Protobuf_Collections_RepeatedMessageField_1_HCJJIALBHBC_* weaponList_; // 0x30  // 2.8: FFNHFIOAMHE
        uint32_t authorityPeerId_; // 0x38  // 2.8: NBBHEINOCII
        struct Google_Protobuf_Collections_RepeatedPrimitiveField_1_System_UInt32_* affixList_; // 0x40  // 2.8: FNMAGLPALAE
        bool isElite_; // 0x48  // 2.8: EGJBAIAAINP
        uint32_t ownerEntityId_; // 0x4C  // 2.8: PGLKGFMNMMJ
        uint32_t summonedTag_; // 0x50  // 2.8: DHGPBINFBMO
        struct Google_Protobuf_Collections_MapField_2_System_UInt32_System_UInt32_* summonTagMap_; // 0x58  // 2.8: COPOGLDCOID
        uint32_t poseId_; // 0x60  // 2.8: KEAADNEEEHA
        Proto_MonsterBornType__Enum bornType_; // 0x64  // 2.8: IFEGBBABING  // type BPPHCBIEOFP__Enum in the dump
        uint32_t blockId_; // 0x68  // 2.8: HGHIGDCCDJC
        uint32_t markFlag_; // 0x6C  // 2.8: IFHAPGKHEPP
        uint32_t titleId_; // 0x70  // 2.8: JDHBMBECJBL
        uint32_t specialNameId_; // 0x74  // 2.8: MPDNIJDMDDA
        uint32_t attackTargetId_; // 0x78  // 2.8: LGCICHEBCGK
        struct Proto_MonsterRoute* monsterRoute_; // 0x80  // 2.8: PKALCPENIDA  // type OFGBPLHHKHI in the dump
        uint32_t aiConfigId_; // 0x88  // 2.8: NNBJCLDEHLH
        uint32_t levelRouteId_; // 0x8C  // 2.8: INJPLIAOPKO
        uint32_t initPoseId_; // 0x90  // 2.8: MGILCGHLPOM
        bool BCPILKFDHJK; // 0x94  // not in appdata-33
        struct Object* content_; // 0x98  // 2.8: BCGGIFMLNLA
        Proto_SceneMonsterInfo_Proto_SceneMonsterInfo_ContentOneofCase__Enum contentCase_; // 0xA0  // 2.8: GNDENDEPIJG
    };
    struct Proto_SceneMonsterInfo {
        struct Proto_SceneMonsterInfo__Class* klass;
        MonitorData* monitor;
        struct Proto_SceneMonsterInfo__Fields fields;
    };

    // Proto_SceneNpcInfo: 2.8 dump LGHFLDFNNFG, field names from appdata-33 Proto_SceneNpcInfo, 1 padding member(s)
    struct __declspec(align(8)) Proto_SceneNpcInfo__Fields {
        struct MessageBase_1__Fields _;
        uint32_t npcId_; // 0x20  // 2.8: BKDLHBEEMLK
        uint32_t roomId_; // 0x24  // 2.8: LBAEDDDJDOA
        uint32_t parentQuestId_; // 0x28  // 2.8: HPABHBANKJG
        uint32_t blockId_; // 0x2C  // 2.8: HGHIGDCCDJC
    };
    struct Proto_SceneNpcInfo {
        struct Proto_SceneNpcInfo__Class* klass;
        MonitorData* monitor;
        struct Proto_SceneNpcInfo__Fields fields;
    };

    // Proto_GadgetBornType__Enum: 2.8 dump CMODCDKOKPB (7 members, 7 names from appdata-33)
    enum class Proto_GadgetBornType__Enum : int32_t {
        GadgetBornNone = 0x00000000,  // 2.8: NMBCAKFHOFP (name from appdata-33, same value)
        GadgetBornInAir = 0x00000001,  // 2.8: GIIJCEMHCOC (name from appdata-33, same value)
        GadgetBornPlayer = 0x00000002,  // 2.8: CJIICKMGINC (name from appdata-33, same value)
        GadgetBornMonsterHit = 0x00000003,  // 2.8: IKLLAIEAHMK (name from appdata-33, same value)
        GadgetBornMonsterDie = 0x00000004,  // 2.8: PKJGBIFBPAB (name from appdata-33, same value)
        GadgetBornGadget = 0x00000005,  // 2.8: JDMNLJEDBLL (name from appdata-33, same value)
        GadgetBornGround = 0x00000006,  // 2.8: DELMELIFOOG (name from appdata-33, same value)
    };

    // Proto_SceneGadgetInfo_ContentOneofCase__Enum: 2.8 dump HNHNJOMEBNM.JNHLCMGOJNF (21 members)
    enum class Proto_SceneGadgetInfo_ContentOneofCase__Enum : int32_t {
        None = 0x00000000,
        TrifleItem = 0x0000000C,
        GatherGadget = 0x0000000D,
        Worktop = 0x0000000E,
        ClientGadget = 0x0000000F,
        Weather = 0x00000011,
        AbilityGadget = 0x00000012,
        StatueGadget = 0x00000013,
        BossChest = 0x00000014,
        BlossomChest = 0x00000029,
        MpPlayReward = 0x0000002A,
        GeneralReward = 0x0000002B,
        OfferingInfo = 0x0000002C,
        FoundationInfo = 0x0000002D,
        VehicleInfo = 0x0000002E,
        ShellInfo = 0x0000002F,
        ScreenInfo = 0x00000030,
        FishPoolInfo = 0x0000003B,
        CustomGadgetTreeInfo = 0x0000003C,
        RoguelikeGadgetInfo = 0x0000003D,
        NightCrowGadgetInfo = 0x0000003E,
    };

    // Proto_SceneGadgetInfo: 2.8 dump HNHNJOMEBNM, field names from appdata-33 Proto_SceneGadgetInfo, 1 padding member(s)
    struct __declspec(align(8)) Proto_SceneGadgetInfo__Fields {
        struct MessageBase_1__Fields _;
        uint32_t gadgetId_; // 0x20  // 2.8: DLHJFLJKNLG
        uint32_t groupId_; // 0x24  // 2.8: EPHMEJIMHDI
        uint32_t configId_; // 0x28  // 2.8: KLMFMDJPFIE
        uint32_t ownerEntityId_; // 0x2C  // 2.8: PGLKGFMNMMJ
        Proto_GadgetBornType__Enum bornType_; // 0x30  // 2.8: IFEGBBABING  // type CMODCDKOKPB__Enum in the dump
        uint32_t gadgetState_; // 0x34  // 2.8: EKHKOIJOILL
        uint32_t gadgetType_; // 0x38  // 2.8: EKPCIEMOIFK
        bool isShowCutscene_; // 0x3C  // 2.8: FEIGPDHEDNE
        uint32_t authorityPeerId_; // 0x40  // 2.8: NBBHEINOCII
        bool isEnableInteract_; // 0x44  // 2.8: AHGBNNKBKIH
        uint32_t interactId_; // 0x48  // 2.8: JOMCLLEFAAE
        uint32_t markFlag_; // 0x4C  // 2.8: IFHAPGKHEPP
        uint32_t propOwnerEntityId_; // 0x50  // 2.8: DLPEDDPHICF
        struct Proto_PlatformInfo* platform_; // 0x58  // 2.8: CLMKNPDCDDM  // type CKKNNPDJKLB in the dump
        struct Google_Protobuf_Collections_RepeatedPrimitiveField_1_System_UInt32_* interactUidList_; // 0x60  // 2.8: GPKFNBMAEEC
        uint32_t draftId_; // 0x68  // 2.8: PHMFEHBMMCM
        uint32_t gadgetTalkState_; // 0x6C  // 2.8: JCEKOMDABJE
        struct Proto_GadgetPlayInfo* playInfo_; // 0x70  // 2.8: LFDMFNCFFJI  // type EAPEIPGHJKI in the dump
        struct Object* content_; // 0x78  // 2.8: BCGGIFMLNLA
        Proto_SceneGadgetInfo_ContentOneofCase__Enum contentCase_; // 0x80  // 2.8: GNDENDEPIJG
    };
    struct Proto_SceneGadgetInfo {
        struct Proto_SceneGadgetInfo__Class* klass;
        MonitorData* monitor;
        struct Proto_SceneGadgetInfo__Fields fields;
    };

    // Proto_CheckAddItemExceedLimitNotify_ItemExceedLimitMsgType__Enum: 2.8 dump PALNNHJMIPA.KPMLDPGOFAM.KLFKPOKGGNJ (4 members, 4 names from appdata-33)
    enum class Proto_CheckAddItemExceedLimitNotify_ItemExceedLimitMsgType__Enum : int32_t {
        ITEM_EXCEED_LIMIT_MSG_TYPE_DEFAULT = 0x00000000,  // 2.8: MOGGLBGINLK (name from appdata-33, same value)
        ITEM_EXCEED_LIMIT_MSG_TYPE_TEXT = 0x00000001,  // 2.8: FMHAPKAFBLN (name from appdata-33, same value)
        ITEM_EXCEED_LIMIT_MSG_TYPE_DIALOG = 0x00000002,  // 2.8: DMAKABFKGBO (name from appdata-33, same value)
        ITEM_EXCEED_LIMIT_MSG_TYPE_DIALOG_NONBLOCK = 0x00000003,  // 2.8: PNJMDPEJLPI (name from appdata-33, same value)
    };

    // Proto_CheckAddItemExceedLimitNotify: 2.8 dump PALNNHJMIPA, field names from appdata-33 Proto_CheckAddItemExceedLimitNotify, 1 padding member(s)
    struct __declspec(align(8)) Proto_CheckAddItemExceedLimitNotify__Fields {
        struct MessageBase_1__Fields _;
        bool is_drop_; // 0x20  // 2.8: GMLNAHNDLMH
        struct Google_Protobuf_Collections_RepeatedPrimitiveField_1_System_UInt32_* exceededItemTypeList_; // 0x28  // 2.8: BEMKDNMDEJK
        struct Google_Protobuf_Collections_RepeatedPrimitiveField_1_System_UInt32_* exceededItemList_; // 0x30  // 2.8: FLDBMCCOIEG
        Proto_CheckAddItemExceedLimitNotify_ItemExceedLimitMsgType__Enum msgType_; // 0x38  // 2.8: LIFFFDANDBH
    };
    struct Proto_CheckAddItemExceedLimitNotify {
        struct Proto_CheckAddItemExceedLimitNotify__Class* klass;
        MonitorData* monitor;
        struct Proto_CheckAddItemExceedLimitNotify__Fields fields;
    };

    // ElementManager_Type__Enum: 2.8 dump ElementManager.Type (3 members)
    enum class ElementManager_Type__Enum : int32_t {
        NONE = 0xFFFFFFFF,
        CLIP = 0x00000000,
        FRAME = 0x00000001,
    };

    // EmoMgrUser: 2.8 dump miHoYoEmotion.EmoMgrUser, field names from appdata-33 EmoMgrUser, 1 padding member(s)
    struct __declspec(align(8)) EmoMgrUser__Fields {
        uint8_t _pad18[8];
        ElementManager_Type__Enum _type; // 0x18
        struct BaseEmoAnimation* _emoAnim; // 0x20
        struct EmoStateManager* _emoState; // 0x28
        bool _isTickable; // 0x30
    };
    struct EmoMgrUser {
        struct EmoMgrUser__Class* klass;
        MonitorData* monitor;
        struct EmoMgrUser__Fields fields;
    };

    // miHoYoEmotion_BaseShape__Array: array of miHoYoEmotion_BaseShape
    struct miHoYoEmotion_BaseShape__Array {
        void* klass;
        MonitorData* monitor;
        Il2CppArrayBounds* bounds;
        il2cpp_array_size_t max_length;
        struct miHoYoEmotion_BaseShape* vector[32];
    };

    // List_1_miHoYoEmotion_BaseShape_: System.Collections.Generic.List<miHoYoEmotion_BaseShape> (standard layout)
    struct __declspec(align(8)) List_1_miHoYoEmotion_BaseShape___Fields {
        struct miHoYoEmotion_BaseShape__Array* _items;
        int32_t _size;
        int32_t _version;
    };
    struct List_1_miHoYoEmotion_BaseShape_ {
        struct List_1_miHoYoEmotion_BaseShape___Class* klass;
        MonitorData* monitor;
        struct List_1_miHoYoEmotion_BaseShape___Fields fields;
    };

    // EmoSync: 2.8 dump miHoYoEmotion.EmoSync, field names from appdata-33 EmoSync
    struct __declspec(align(8)) EmoSync__Fields {
        struct EmoMgrUser__Fields _;
        bool isManekin; // 0x38
        struct String* defaultEmotion; // 0x40
        struct String* resetEmotion; // 0x48
        struct String* resetPhoneme; // 0x50
        struct EmotionSetData* _setData; // 0x58
        struct List_1_miHoYoEmotion_BaseShape_* phonemes; // 0x60
        struct List_1_miHoYoEmotion_BaseShape_* emotions; // 0x68
        struct Dictionary_2_System_String_miHoYoEmotion_BaseShape_* _phonemeCache; // 0x70
        struct Dictionary_2_System_String_miHoYoEmotion_BaseShape_* _emotionCahce; // 0x78
        struct String* _curEmotion; // 0x80
        struct String* _preEmotion; // 0x88
        struct String* _lastEmotion; // 0x90
        struct String* _curPhoneme; // 0x98
        struct String* _prePhoneme; // 0xA0
        struct EmoSync_EmoSync_EmoParamCache* _emoParamCache; // 0xA8
        bool _emotionFromTemplate; // 0xB0
    };
    struct EmoSync {
        struct EmoSync__Class* klass;
        MonitorData* monitor;
        struct EmoSync__Fields fields;
    };

    // List_1_System_String_: System.Collections.Generic.List<System_String> (standard layout)
    struct __declspec(align(8)) List_1_System_String___Fields {
        struct String__Array* _items;
        int32_t _size;
        int32_t _version;
    };
    struct List_1_System_String_ {
        struct List_1_System_String___Class* klass;
        MonitorData* monitor;
        struct List_1_System_String___Fields fields;
    };

    // miHoYoEmotion_BaseShape: 2.8 dump miHoYoEmotion.BaseShape
    struct __declspec(align(8)) miHoYoEmotion_BaseShape__Fields {
        struct String* name; // 0x10
        struct List_1_System_String_* elements; // 0x18
    };
    struct miHoYoEmotion_BaseShape {
        struct miHoYoEmotion_BaseShape__Class* klass;
        MonitorData* monitor;
        struct miHoYoEmotion_BaseShape__Fields fields;
    };

    // BaseDialogContext: wrapper for the existing BaseDialogContext__Fields of this header (the header's own wrapper has an obfuscated name)
    struct BaseDialogContext {
        struct BaseDialogContext__Class* klass;
        MonitorData* monitor;
        struct BaseDialogContext__Fields fields;
    };

    // KMDDMCEDPDL__Enum: 2.8 dump KMDDMCEDPDL (2 members)
    enum class KMDDMCEDPDL__Enum : int32_t {
        Normal = 0x00000000,
        Extra = 0x00000001,
    };

    // ADHHDEGMPLB__Enum: 2.8 dump ADHHDEGMPLB (94 members)
    enum class ADHHDEGMPLB__Enum : int32_t {
        FIGHT_PROP_NONE = 0x00000000,
        FIGHT_PROP_BASE_HP = 0x00000001,
        FIGHT_PROP_HP = 0x00000002,
        FIGHT_PROP_HP_PERCENT = 0x00000003,
        FIGHT_PROP_BASE_ATTACK = 0x00000004,
        FIGHT_PROP_ATTACK = 0x00000005,
        FIGHT_PROP_ATTACK_PERCENT = 0x00000006,
        FIGHT_PROP_BASE_DEFENSE = 0x00000007,
        FIGHT_PROP_DEFENSE = 0x00000008,
        FIGHT_PROP_DEFENSE_PERCENT = 0x00000009,
        FIGHT_PROP_BASE_SPEED = 0x0000000A,
        FIGHT_PROP_SPEED_PERCENT = 0x0000000B,
        FIGHT_PROP_HP_MP_PERCENT = 0x0000000C,
        FIGHT_PROP_ATTACK_MP_PERCENT = 0x0000000D,
        FIGHT_PROP_CRITICAL = 0x00000014,
        FIGHT_PROP_ANTI_CRITICAL = 0x00000015,
        FIGHT_PROP_CRITICAL_HURT = 0x00000016,
        FIGHT_PROP_CHARGE_EFFICIENCY = 0x00000017,
        FIGHT_PROP_ADD_HURT = 0x00000018,
        FIGHT_PROP_SUB_HURT = 0x00000019,
        FIGHT_PROP_HEAL_ADD = 0x0000001A,
        FIGHT_PROP_HEALED_ADD = 0x0000001B,
        FIGHT_PROP_ELEMENT_MASTERY = 0x0000001C,
        FIGHT_PROP_PHYSICAL_SUB_HURT = 0x0000001D,
        FIGHT_PROP_PHYSICAL_ADD_HURT = 0x0000001E,
        FIGHT_PROP_DEFENCE_IGNORE_RATIO = 0x0000001F,
        FIGHT_PROP_DEFENCE_IGNORE_DELTA = 0x00000020,
        FIGHT_PROP_FIRE_ADD_HURT = 0x00000028,
        FIGHT_PROP_ELEC_ADD_HURT = 0x00000029,
        FIGHT_PROP_WATER_ADD_HURT = 0x0000002A,
        FIGHT_PROP_GRASS_ADD_HURT = 0x0000002B,
        FIGHT_PROP_WIND_ADD_HURT = 0x0000002C,
        FIGHT_PROP_ROCK_ADD_HURT = 0x0000002D,
        FIGHT_PROP_ICE_ADD_HURT = 0x0000002E,
        FIGHT_PROP_HIT_HEAD_ADD_HURT = 0x0000002F,
        FIGHT_PROP_FIRE_SUB_HURT = 0x00000032,
        FIGHT_PROP_ELEC_SUB_HURT = 0x00000033,
        FIGHT_PROP_WATER_SUB_HURT = 0x00000034,
        FIGHT_PROP_GRASS_SUB_HURT = 0x00000035,
        FIGHT_PROP_WIND_SUB_HURT = 0x00000036,
        FIGHT_PROP_ROCK_SUB_HURT = 0x00000037,
        FIGHT_PROP_ICE_SUB_HURT = 0x00000038,
        FIGHT_PROP_EFFECT_HIT = 0x0000003C,
        FIGHT_PROP_EFFECT_RESIST = 0x0000003D,
        FIGHT_PROP_FREEZE_RESIST = 0x0000003E,
        FIGHT_PROP_DIZZY_RESIST = 0x00000040,
        FIGHT_PROP_FREEZE_SHORTEN = 0x00000041,
        FIGHT_PROP_DIZZY_SHORTEN = 0x00000043,
        FIGHT_PROP_MAX_FIRE_ENERGY = 0x00000046,
        FIGHT_PROP_MAX_ELEC_ENERGY = 0x00000047,
        FIGHT_PROP_MAX_WATER_ENERGY = 0x00000048,
        FIGHT_PROP_MAX_GRASS_ENERGY = 0x00000049,
        FIGHT_PROP_MAX_WIND_ENERGY = 0x0000004A,
        FIGHT_PROP_MAX_ICE_ENERGY = 0x0000004B,
        FIGHT_PROP_MAX_ROCK_ENERGY = 0x0000004C,
        FIGHT_PROP_SKILL_CD_MINUS_RATIO = 0x00000050,
        FIGHT_PROP_SHIELD_COST_MINUS_RATIO = 0x00000051,
        FIGHT_PROP_CUR_FIRE_ENERGY = 0x000003E8,
        FIGHT_PROP_CUR_ELEC_ENERGY = 0x000003E9,
        FIGHT_PROP_CUR_WATER_ENERGY = 0x000003EA,
        FIGHT_PROP_CUR_GRASS_ENERGY = 0x000003EB,
        FIGHT_PROP_CUR_WIND_ENERGY = 0x000003EC,
        FIGHT_PROP_CUR_ICE_ENERGY = 0x000003ED,
        FIGHT_PROP_CUR_ROCK_ENERGY = 0x000003EE,
        FIGHT_PROP_CUR_HP = 0x000003F2,
        FIGHT_PROP_MAX_HP = 0x000007D0,
        FIGHT_PROP_CUR_ATTACK = 0x000007D1,
        FIGHT_PROP_CUR_DEFENSE = 0x000007D2,
        FIGHT_PROP_CUR_SPEED = 0x000007D3,
        FIGHT_PROP_NONEXTRA_ATTACK = 0x00000BB8,
        FIGHT_PROP_NONEXTRA_DEFENSE = 0x00000BB9,
        FIGHT_PROP_NONEXTRA_CRITICAL = 0x00000BBA,
        FIGHT_PROP_NONEXTRA_ANTI_CRITICAL = 0x00000BBB,
        FIGHT_PROP_NONEXTRA_CRITICAL_HURT = 0x00000BBC,
        FIGHT_PROP_NONEXTRA_CHARGE_EFFICIENCY = 0x00000BBD,
        FIGHT_PROP_NONEXTRA_ELEMENT_MASTERY = 0x00000BBE,
        FIGHT_PROP_NONEXTRA_PHYSICAL_SUB_HURT = 0x00000BBF,
        FIGHT_PROP_NONEXTRA_FIRE_ADD_HURT = 0x00000BC0,
        FIGHT_PROP_NONEXTRA_ELEC_ADD_HURT = 0x00000BC1,
        FIGHT_PROP_NONEXTRA_WATER_ADD_HURT = 0x00000BC2,
        FIGHT_PROP_NONEXTRA_GRASS_ADD_HURT = 0x00000BC3,
        FIGHT_PROP_NONEXTRA_WIND_ADD_HURT = 0x00000BC4,
        FIGHT_PROP_NONEXTRA_ROCK_ADD_HURT = 0x00000BC5,
        FIGHT_PROP_NONEXTRA_ICE_ADD_HURT = 0x00000BC6,
        FIGHT_PROP_NONEXTRA_FIRE_SUB_HURT = 0x00000BC7,
        FIGHT_PROP_NONEXTRA_ELEC_SUB_HURT = 0x00000BC8,
        FIGHT_PROP_NONEXTRA_WATER_SUB_HURT = 0x00000BC9,
        FIGHT_PROP_NONEXTRA_GRASS_SUB_HURT = 0x00000BCA,
        FIGHT_PROP_NONEXTRA_WIND_SUB_HURT = 0x00000BCB,
        FIGHT_PROP_NONEXTRA_ROCK_SUB_HURT = 0x00000BCC,
        FIGHT_PROP_NONEXTRA_ICE_SUB_HURT = 0x00000BCD,
        FIGHT_PROP_NONEXTRA_SKILL_CD_MINUS_RATIO = 0x00000BCE,
        FIGHT_PROP_NONEXTRA_SHIELD_COST_MINUS_RATIO = 0x00000BCF,
        FIGHT_PROP_NONEXTRA_PHYSICAL_ADD_HURT = 0x00000BD0,
    };

    // MKPHEKGEAJK: 2.8 dump MKPHEKGEAJK (value type)
    struct MKPHEKGEAJK {
        KMDDMCEDPDL__Enum MEGDMNAOMAG; // 0x0
        ADHHDEGMPLB__Enum JLLCGIDLCKC; // 0x4
        struct String* GGFNAEAFAMH; // 0x8
        float PCJAKCJLMEJ; // 0x10
        float OEKHCDABKHE; // 0x14
        bool LPNBCECPLLF; // 0x18
        bool COBBFMHIEHH; // 0x19
    };

    // MKPHEKGEAJK__Array: array of MKPHEKGEAJK
    struct MKPHEKGEAJK__Array {
        void* klass;
        MonitorData* monitor;
        Il2CppArrayBounds* bounds;
        il2cpp_array_size_t max_length;
        struct MKPHEKGEAJK vector[32];
    };

    // List_1_MKPHEKGEAJK_: System.Collections.Generic.List<MKPHEKGEAJK> (standard layout)
    struct __declspec(align(8)) List_1_MKPHEKGEAJK___Fields {
        struct MKPHEKGEAJK__Array* _items;
        int32_t _size;
        int32_t _version;
    };
    struct List_1_MKPHEKGEAJK_ {
        struct List_1_MKPHEKGEAJK___Class* klass;
        MonitorData* monitor;
        struct List_1_MKPHEKGEAJK___Fields fields;
    };

    // MoleMole_Config_ItemType__Enum: 2.8 dump EEFAPEFLCHB (7 members)
    enum class MoleMole_Config_ItemType__Enum : int32_t {
        ITEM_NONE = 0x00000000,
        ITEM_VIRTUAL = 0x00000001,
        ITEM_MATERIAL = 0x00000002,
        ITEM_RELIQUARY = 0x00000003,
        ITEM_WEAPON = 0x00000004,
        ITEM_DISPLAY = 0x00000005,
        ITEM_FURNITURE = 0x00000006,
    };

    // BPJOPAGFOJM__Array: array of BPJOPAGFOJM
    struct BPJOPAGFOJM__Array {
        void* klass;
        MonitorData* monitor;
        Il2CppArrayBounds* bounds;
        il2cpp_array_size_t max_length;
        struct BPJOPAGFOJM* vector[32];
    };

    // List_1_BPJOPAGFOJM_: System.Collections.Generic.List<BPJOPAGFOJM> (standard layout)
    struct __declspec(align(8)) List_1_BPJOPAGFOJM___Fields {
        struct BPJOPAGFOJM__Array* _items;
        int32_t _size;
        int32_t _version;
    };
    struct List_1_BPJOPAGFOJM_ {
        struct List_1_BPJOPAGFOJM___Class* klass;
        MonitorData* monitor;
        struct List_1_BPJOPAGFOJM___Fields fields;
    };

    // Google_Protobuf_Collections_RepeatedMessageField_1_BPJOPAGFOJM_: 2.8 dump OLAOHCJGBLN<T> with T=BPJOPAGFOJM, names from appdata-33 Google_Protobuf_Collections_RepeatedMessageField_1_Proto_SceneEntityInfo_
    struct __declspec(align(8)) Google_Protobuf_Collections_RepeatedMessageField_1_BPJOPAGFOJM___Fields {
        struct List_1_BPJOPAGFOJM_* values; // (generic definition: dump order, natural layout)  // 2.8: NEJEPNGFFBJ
        bool _isInPool; // (generic definition: dump order, natural layout)  // 2.8: DFHMMNONANE
        int32_t _count; // (generic definition: dump order, natural layout)  // 2.8: OBHIGAFBKOL
    };
    struct Google_Protobuf_Collections_RepeatedMessageField_1_BPJOPAGFOJM_ {
        struct Google_Protobuf_Collections_RepeatedMessageField_1_BPJOPAGFOJM___Class* klass;
        MonitorData* monitor;
        struct Google_Protobuf_Collections_RepeatedMessageField_1_BPJOPAGFOJM___Fields fields;
    };

    // MoleMole_EquipLevelUpDialogContext: 2.8 dump FNJDLPPBNPM, field names from appdata-33 MoleMole_EquipLevelUpDialogContext
    struct __declspec(align(8)) MoleMole_EquipLevelUpDialogContext__Fields {
        struct BaseDialogContext__Fields _;
        struct MonoAvatarPropertyItem* _propertyItemPrefab; // 0x198  // 2.8: AJKAOPEHNMO
        uint32_t _propertyItemPrefabHandle; // 0x1A0  // 2.8: GFKLFKDEDIL
        uint32_t _mainPropItemPrefabHandle; // 0x1A4  // 2.8: FPHAJKDLCGD
        struct MonoEquipLevelUpDialog* _dialogMono; // 0x1A8  // 2.8: HNEIFGCBILK
        struct MoleMole_BagItem* _equip; // 0x1B0  // 2.8: JCLJFKCGNKM  // type NNOAKOFCAIH in the dump
        uint32_t _prevLevel; // 0x1B8  // 2.8: LMMCIDNBDDD
        uint32_t _currLevel; // 0x1BC  // 2.8: JBHLGGOCDFK
        uint32_t _powerUpRate; // 0x1C0  // 2.8: NHMDMJHHKMJ
        struct List_1_MKPHEKGEAJK_* _propertyChange; // 0x1C8  // 2.8: DCFNLMIBNGI
        MoleMole_Config_ItemType__Enum _equipType; // 0x1D0  // 2.8: NCLNHKGCGAB  // type EEFAPEFLCHB__Enum in the dump
        bool _canClose; // 0x1D4  // 2.8: FHOENDHDEPE
        struct Google_Protobuf_Collections_RepeatedMessageField_1_BPJOPAGFOJM_* _returnedMaterialList; // 0x1D8  // 2.8: ACLNIEOAEEF
    };
    struct MoleMole_EquipLevelUpDialogContext {
        struct MoleMole_EquipLevelUpDialogContext__Class* klass;
        MonitorData* monitor;
        struct MoleMole_EquipLevelUpDialogContext__Fields fields;
    };

    // InLevelMainPageContext_DoTeamCountDown_Iterator: FALLBACK appdata-33 definition (NOT located in the 2.8 dump; layout unverified - compile aid only)

    struct __declspec(align(8)) InLevelMainPageContext_DoTeamCountDown_Iterator__Fields
    {
        int32_t HGCHJINEMCM;
        struct Object* KOBKOALABHL;
        struct InLevelMainPageContext* _levelMainPageContext;
    };

    struct InLevelMainPageContext_DoTeamCountDown_Iterator
    {
        struct InLevelMainPageContext_DoTeamCountDown_Iterator__Class* klass;
        MonitorData* monitor;
        struct InLevelMainPageContext_DoTeamCountDown_Iterator__Fields fields;
    };

    // MonoSpriteProxy: wrapper for the existing MonoSpriteProxy__Fields of this header (the header's own wrapper has an obfuscated name)
    struct MonoSpriteProxy {
        struct MonoSpriteProxy__Class* klass;
        MonitorData* monitor;
        struct MonoSpriteProxy__Fields fields;
    };

    // MonoTeamBtn: 2.8 dump MoleMole.MonoTeamBtn, field names from appdata-33 MonoTeamBtn
    struct __declspec(align(8)) MonoTeamBtn__Fields {
        struct MonoSpriteProxy__Fields _;
        struct Animator* _animator; // 0x20
        struct Button_1* _actionBtn; // 0x28  // type Button in the dump
        struct Button_1* _qteButton; // 0x30  // type Button in the dump
        struct MonoBattleBtn* _energySkillButton; // 0x38
        struct Image_1* _avatarIcon; // 0x40  // type Image in the dump
        struct Material* _deadMaterial; // 0x48
        struct Text* _nameText; // 0x50
        struct SmoothMask* _hpBar; // 0x58
        struct MonoColorExchange* _hpColor; // 0x60
        struct MonoColorExchange* _hpBgColor; // 0x68
        struct GameObject* _voiceButton; // 0x70
        struct SimpleText* _changeAvatarCD; // 0x78
        struct SmoothMask* _changeAvatarCDMask; // 0x80
        struct GameObject* _trialInfo; // 0x88
        struct GameObject* _talentCD; // 0x90
        struct SmoothMask* _talentCDMask; // 0x98
        struct Image_1* _talentCDMaskImage; // 0xA0  // type Image in the dump
        struct Image_1* _talentCDBgImage; // 0xA8  // type Image in the dump
        struct Transform* _talentCDEffectTrans; // 0xB0
        struct Color _talentCDBgColor; // 0xB8
        struct Color _talentCDFillColor; // 0xC8
        struct Color _talentCDReadyBgColor; // 0xD8
        struct Color _talentCDReadyFillColor; // 0xE8
        struct GameObject* _talentCDEffect; // 0xF8
        struct MonoPrefabPlugin* _prefabPlugin; // 0x100
        struct Transform* avatarLevelUpTrans; // 0x108
        struct GameObject* avatarLevelUpGameObject; // 0x110
        struct Transform* fetterUpTrans; // 0x118
        struct GameObject* fetterUpGameObject; // 0x120
        struct RectTransform* _pcKeyGrp; // 0x128
        struct MonoInLevelBuffInfo* inlevelBuffInfo; // 0x130
        struct MonoLongPressButton* _longPressBtn; // 0x138
        struct GameObject* _longPressBarGO; // 0x140
        struct SmoothMask* _longPressBarFill; // 0x148
        uint64_t _guid; // 0x150  // 2.8: NJKFHNCPFLP
        bool _showChangeAvatarCDText; // 0x158  // 2.8: CALEGCMLKNA
        struct LCAvatarCombat* _lcCombat; // 0x160  // 2.8: AHLDICJDILN
        struct GameObject* _talentCDEffectIns; // 0x168  // 2.8: COOGOPJDJAC
        struct MoleMole_AvatarDataItem* _avatarData; // 0x170  // 2.8: AEIACACJJJL  // type GDHEHLDNHJB in the dump
        struct MoleMole_UIUtil_MoleMole_UIUtil_LevelUpItemQueue* teamLevelUpItemQueue; // 0x178  // type PAKJGCBJMOL_PAKJGCBJMOL_IACNLHKLMIE in the dump
        bool needTickBuff; // 0x180
        struct Image_1* _skillImage; // 0x188  // 2.8: FAKHANDBONG  // type Image in the dump
        struct CanvasGroup* _actionBtnCanvasGroup; // 0x190  // 2.8: OHNAAFJACCK
        struct CanvasGroup* _qteBtnCanvasGroup; // 0x198  // 2.8: LOJEIELKLCL
        struct MoleMole_EditableString* _changeAvatarCDStr; // 0x1A0  // 2.8: NDJEGKGNJKB  // type KCAOLLMIPIK in the dump
        struct Action_1_NDGNOAAMIEM_* _onEntityReadyPost; // 0x1A8  // 2.8: KJDIMOPMENI
        float _currHPRatio; // 0x1B0  // 2.8: MDCBEAKOPPH
        float _lastChangeAvatarCd; // 0x1B4  // 2.8: APPGFCJEBDO
        struct Animation* _restoreHP; // 0x1B8  // 2.8: KJBNIMNEIKC
        struct MonoUIEffect* _restoreHPEffect; // 0x1C0  // 2.8: PNJEMKCKGMK
    };
    struct MonoTeamBtn {
        struct MonoTeamBtn__Class* klass;
        MonitorData* monitor;
        struct MonoTeamBtn__Fields fields;
    };

    // Int3: 2.8 dump Int3 (value type)
    struct Int3 {
        int32_t x; // 0x0
        int32_t y; // 0x4
        int32_t z; // 0x8
    };

    // Int3__Array: array of Int3
    struct Int3__Array {
        void* klass;
        MonitorData* monitor;
        Il2CppArrayBounds* bounds;
        il2cpp_array_size_t max_length;
        struct Int3 vector[32];
    };

    // motion4hi_CrossFadeByParameterConfig__Array: array of motion4hi_CrossFadeByParameterConfig
    struct motion4hi_CrossFadeByParameterConfig__Array {
        void* klass;
        MonitorData* monitor;
        Il2CppArrayBounds* bounds;
        il2cpp_array_size_t max_length;
        struct motion4hi_CrossFadeByParameterConfig* vector[32];
    };

    // List_1_motion4hi_CrossFadeByParameterConfig_: System.Collections.Generic.List<motion4hi_CrossFadeByParameterConfig> (standard layout)
    struct __declspec(align(8)) List_1_motion4hi_CrossFadeByParameterConfig___Fields {
        struct motion4hi_CrossFadeByParameterConfig__Array* _items;
        int32_t _size;
        int32_t _version;
    };
    struct List_1_motion4hi_CrossFadeByParameterConfig_ {
        struct List_1_motion4hi_CrossFadeByParameterConfig___Class* klass;
        MonitorData* monitor;
        struct List_1_motion4hi_CrossFadeByParameterConfig___Fields fields;
    };

    // Boolean__Array: array of Boolean
    struct Boolean__Array {
        void* klass;
        MonitorData* monitor;
        Il2CppArrayBounds* bounds;
        il2cpp_array_size_t max_length;
        bool vector[32];
    };

    // AnimationPhaseArray__Array: array of AnimationPhaseArray
    struct AnimationPhaseArray__Array {
        void* klass;
        MonitorData* monitor;
        Il2CppArrayBounds* bounds;
        il2cpp_array_size_t max_length;
        struct AnimationPhaseArray* vector[32];
    };

    // Single__Array: array of Single
    struct Single__Array {
        void* klass;
        MonitorData* monitor;
        Il2CppArrayBounds* bounds;
        il2cpp_array_size_t max_length;
        float vector[32];
    };

    // motion4hi_ParamConstraint__Array: array of motion4hi_ParamConstraint
    struct motion4hi_ParamConstraint__Array {
        void* klass;
        MonitorData* monitor;
        Il2CppArrayBounds* bounds;
        il2cpp_array_size_t max_length;
        struct motion4hi_ParamConstraint* vector[32];
    };

    // List_1_motion4hi_ParamConstraint_: System.Collections.Generic.List<motion4hi_ParamConstraint> (standard layout)
    struct __declspec(align(8)) List_1_motion4hi_ParamConstraint___Fields {
        struct motion4hi_ParamConstraint__Array* _items;
        int32_t _size;
        int32_t _version;
    };
    struct List_1_motion4hi_ParamConstraint_ {
        struct List_1_motion4hi_ParamConstraint___Class* klass;
        MonitorData* monitor;
        struct List_1_motion4hi_ParamConstraint___Fields fields;
    };

    // AnimatorControllerParameter__Array: array of AnimatorControllerParameter
    struct AnimatorControllerParameter__Array {
        void* klass;
        MonitorData* monitor;
        Il2CppArrayBounds* bounds;
        il2cpp_array_size_t max_length;
        struct AnimatorControllerParameter* vector[32];
    };

    // PropSpace__Enum: 2.8 dump motion4hi.PropSpace (5 members)
    enum class PropSpace__Enum : int32_t {
        None = 0x00000000,
        World = 0x00000001,
        Body = 0x00000002,
        RightHand = 0x00000003,
        LeftHand = 0x00000004,
    };

    // AnimatorController: 2.8 dump motion4hi.AnimatorController, field names from appdata-33 AnimatorController, 1 padding member(s)
    struct __declspec(align(8)) AnimatorController__Fields {
        uint8_t _pad18[8];
        struct Action_1_AnimatorController_AnimatorController_CrossFadeInfo_* onCrossFadeTransition; // 0x18
        struct Int3__Array* _transitionProirities; // 0x20
        struct Dictionary_2_System_Int32_List_Int3__* _transitionProiritiesDict; // 0x28
        struct Dictionary_2_System_String_System_Boolean_* _stateLoop; // 0x30
        float _random; // 0x38
        bool _disableNoFadeZone; // 0x3C
        struct Dictionary_2_UnityEngine_StateMachineBehaviour_AnimatorController_AnimatorController_StateMachineBehaviourInfo_* _currentBehaviour; // 0x40
        struct List_1_motion4hi_CrossFadeByParameterConfig_* _crossfadeConfigs; // 0x48
        struct Dictionary_2_System_Int32_CrossFadeByParameterConfig___* _configsDictionary; // 0x50
        struct String__Array* _curveExtractionKeywords; // 0x58
        struct String__Array* _stateNames; // 0x60
        struct Boolean__Array* _stateLoops; // 0x68
        struct Int32__Array* _stateHashes; // 0x70
        struct Boolean__Array* _stateMirros; // 0x78
        struct Boolean__Array* _stateHasMirrors; // 0x80
        struct String__Array* _stateMirrorParams; // 0x88
        struct String__Array* _statePhaseJsonPathes; // 0x90
        struct AnimationPhaseArray__Array* _statePhaseArrays; // 0x98
        struct Single__Array* _stateDefaultDurations; // 0xA0
        struct List_1_System_String_* _serializedParamConstraints; // 0xA8
        struct List_1_motion4hi_ParamConstraint_* _paramConstraints; // 0xB0
        struct Boolean__Array* _stateTransitionedArray; // 0xB8
        struct Int3 _cfTransition; // 0xC0
        struct Vector3 _cfParams; // 0xCC
        struct Animator* _animator; // 0xD8
        int32_t _frame; // 0xE0
        struct AnimatorControllerParameter__Array* _allParams; // 0xE8
        struct Dictionary_2_System_Int32_UnityEngine_AnimatorControllerParameterType_* _allParamsTypeDictionary; // 0xF0
        PropSpace__Enum _prop1Space; // 0xF8
        struct Vector3 _crossOverStepBorderNear0; // 0xFC
        struct Vector3 _crossOverStepBorderNear1; // 0x108
        struct Vector3 _crossOverStepBorderFar0; // 0x114
        struct Vector3 _crossOverStepBorderFar1; // 0x120
        struct Vector3 _crossOverJumpBorder0; // 0x12C
        struct Vector3 _crossOverJumpBorder1; // 0x138
        struct Vector3 _crossOverPredictJumpPos; // 0x144
        struct Vector3 _crossOverPredictStepInPos; // 0x150
        struct Vector3 _crossOverDecisionJumpPos; // 0x15C
        int32_t _currentstateHash; // 0x168
        int32_t _nextstateHash; // 0x16C
        float _currentstateTime; // 0x170
        float _nextstateTime; // 0x174
    };
    struct AnimatorController {
        struct AnimatorController__Class* klass;
        MonitorData* monitor;
        struct AnimatorController__Fields fields;
    };

    // Config_ProudSkillOpenConfig__Array: array of Config_ProudSkillOpenConfig
    struct Config_ProudSkillOpenConfig__Array {
        void* klass;
        MonitorData* monitor;
        Il2CppArrayBounds* bounds;
        il2cpp_array_size_t max_length;
        struct Config_ProudSkillOpenConfig* vector[32];
    };

    // SimpleSafeUInt32__Array: array of SimpleSafeUInt32
    struct SimpleSafeUInt32__Array {
        void* klass;
        MonitorData* monitor;
        Il2CppArrayBounds* bounds;
        il2cpp_array_size_t max_length;
        struct SimpleSafeUInt32* vector[32];
    };

    // Config_AvatarSkillDepotExcelConfig: FALLBACK appdata-33 definition (NOT located in the 2.8 dump; layout unverified - compile aid only)

    struct __declspec(align(8)) Config_AvatarSkillDepotExcelConfig__Fields {
        struct SimpleSafeUInt32 idRawNum;
        struct SimpleSafeUInt32 energySkillRawNum;
        struct SimpleSafeUInt32 talentSkillRawNum;
        struct SimpleSafeUInt32__Array* _skills;
        struct SimpleSafeUInt32__Array* _subSkills;
        struct SimpleSafeUInt32 attackModeSkillRawNum;
        struct SimpleSafeUInt32 leaderTalentRawNum;
        struct String__Array* _extraAbilities;
        struct SimpleSafeUInt32__Array* _talents;
        struct String* _talentStarName;
        struct SimpleSafeUInt32 coreProudSkillGroupIdRawNum;
        struct SimpleSafeUInt32 coreProudAvatarPromoteLevelRawNum;
        struct Config_ProudSkillOpenConfig__Array* _inherentProudSkillOpens;
        struct String* _skillDepotAbilityGroup;
    };

    struct Config_AvatarSkillDepotExcelConfig {
        struct Config_AvatarSkillDepotExcelConfig__Class* klass;
        MonitorData* monitor;
        struct Config_AvatarSkillDepotExcelConfig__Fields fields;
    };

    // RealScenePointType__Enum: 2.8 dump AOAHPHDHLNA (13 members)
    enum class RealScenePointType__Enum : int32_t {
        Other = 0x00000000,
        TransPointNormal = 0x00000001,
        TransPointStatue = 0x00000002,
        TransPointPortal = 0x00000003,
        DungeonEntry = 0x00000004,
        DungeonExit = 0x00000005,
        DungeonWayPoint = 0x00000006,
        DungeonQuitPoint = 0x00000007,
        DungeonRewardPoint = 0x00000008,
        PersonalSceneJumpPoint = 0x00000009,
        SceneBuildingPoint = 0x0000000A,
        DungeonSlipRevivePoint = 0x0000000B,
        VehicleSummonPoint = 0x0000000C,
    };

    // ---- MISSING in this version (present in appdata-33; feature code reading them needs #if RELIC_GAME_VERSION >= 33) ----
    //   Proto_CheckAddItemExceedLimitNotify: reason_ (uint32_t)

#if !defined(_GHIDRA_) && !defined(_IDA_)
}
#endif
