namespace Relic.Core.Fiddler;

/// <summary>
/// The FiddlerScript (CustomRules.js) that redirects the game client to the private server and blocks
/// telemetry. Host/port are templated in. Based on the project's reference fiddler_script.txt, kept to
/// the "GIO method 5 / Grasscutter" path (rewrite host + port to the sdk/dispatch endpoint).
///
/// It also decides what gets decrypted at all: only the game's own domains. Everything else is
/// tunnelled untouched, so a running Fiddler does not break the rest of the machine's HTTPS.
/// </summary>
public static class FiddlerRules
{
    private const string Template = """
        import System;
        import System.Windows.Forms;
        import Fiddler;
        import System.Text.RegularExpressions;

        // ─── Generated by Relic — redirects the Genshin client to the private server ───
        // Server: __HOST__:__PORT__

        class Handlers
        {
            // The game's domains. The same list decides both what gets decrypted (below) and what
            // gets redirected — there is no reason to see anything else in the clear.
            static function isGameHost(h: String) {
                if (null == h) return false;
                // A CONNECT session arrives as "host:port"; only the host matters.
                var c = h.IndexOf(":");
                if (c > -1) h = h.Substring(0, c);
                var hosts = [".yuanshen.com", ".hoyoverse.com", ".mihoyo.com"];
                for (var i = 0; i < hosts.length; i++) {
                    if (h.EndsWith(hosts[i])) return true;
                }
                return false;
            }

            static function OnBeforeRequest(oS: Session) {

                // Decrypt NOTHING outside the game's domains. Without this, while Fiddler runs it
                // MITMs the whole machine's HTTPS traffic: the browser has to accept a Fiddler
                // certificate for every site, and on HSTS-preloaded sites (google, youtube) the
                // error is blocking, with no "Continue anyway". Marked on the CONNECT session, the
                // connection is only tunnelled — the browser negotiates TLS directly with the real
                // server, exactly as without a proxy.
                //
                // Compare on `hostname`, NOT on `host`: on a CONNECT session `host` is always
                // "host:443", so an EndsWith(".yuanshen.com") on `host` would never match the game's
                // hosts — we would tunnel the game too and the redirect below would die.
                if (oS.HTTPMethodIs("CONNECT")) {
                    var target = oS.hostname;
                    if (null == target || "" == target) target = oS.PathAndQuery; // "host:port"
                    if (!isGameHost(target)) {
                        oS["x-no-decrypt"] = "not a game host";
                        return;
                    }
                }

                // Block telemetry / crash / log uploads so they don't leak or spam.
                var blocks =
                    [
                    ":8888/log",
                    "/sdk/dataUpload",
                    "/common/h5log/log/batch",
                    "/crash/dataUpload"
                    ];
                for (var i = 0; i < blocks.length; i++) {
                    if (oS.uriContains(blocks[i])) {
                        oS.oRequest.FailSession(404, "Blocked", "Blocked by Relic");
                        return;
                    }
                }

                // Redirect all official endpoints to the private server.
                var redirects =
                    [
                    ".yuanshen.com",
                    ".hoyoverse.com",
                    ".mihoyo.com"
                    ];
                for (var i = 0; i < redirects.length; i++) {
                    if (oS.host.EndsWith(redirects[i])) {
                        oS.oRequest.headers.UriScheme = "http";
                        oS.host = "__HOST__";
                        oS.port = __PORT__;
                        break;
                    }
                }
            }
        };
        """;

    // Fiddler creates its root certificate ONLY from the "Decrypt HTTPS traffic" checkbox in its own
    // UI — writing the CaptureHTTPS registry pref does not do it, and neither does fetching
    // /FiddlerRoot.cer (that endpoint reads the root, it never makes one). The documented way to get
    // one headlessly is Fiddler's own script API, so we hand Fiddler a script that asks for it.
    //
    // It is a SEPARATE script from the redirect rules on purpose: a FiddlerScript that fails to
    // compile takes the whole file down with it, and the redirect rules are what the game depends on.
    // This one runs alone, once, before the real rules are written — so even a total failure here
    // costs a certificate, never the redirect.
    private const string CertBootstrap = """
        import System;
        import Fiddler;

        // ─── Generated by Relic — temporary, replaced by the redirect rules ───
        // Only job: make Fiddler mint its root certificate. It is NOT trusted here — Relic does that
        // through the standard Windows consent dialog, which is the user's decision to make.
        //
        // Deliberately NOT guarded by rootCertExists(): that check is blind to validity, so on a box
        // whose root has expired it would answer "already have one" and mint nothing, forever. Relic
        // only writes this script once it has already established there is no USABLE root, so the
        // unconditional call is the one that can actually repair that state.

        class Handlers
        {
            static function Main() {
                CertMaker.createRootCert();
            }
        };
        """;

    /// <summary>The throwaway FiddlerScript whose only effect is creating Fiddler's root certificate.
    /// Deliberately does not trust it — see <see cref="FiddlerAutomation.TrustRootCertConsented"/>.</summary>
    public static string RenderCertBootstrap() => CertBootstrap;

    /// <summary>Render the CustomRules.js for a given server host and port. Pure/deterministic.</summary>
    public static string Render(string host, int port)
    {
        if (string.IsNullOrWhiteSpace(host))
            throw new ArgumentException("server host is required", nameof(host));
        if (port is <= 0 or > 65535)
            throw new ArgumentOutOfRangeException(nameof(port));
        return Template
            .Replace("__HOST__", host)
            .Replace("__PORT__", port.ToString());
    }
}
